"""Connector Ontology Manifest compiler (CONCEPT:AU-KG.ontology.connector-manifest-compiler).

Generalizes ``ontology.leanix_metamodel``'s ``compile_leanix_metamodel`` /
``export_leanix_ttl`` / ``apply_leanix_metamodel`` (LeanIX-only) into a source-agnostic
pipeline over :class:`connector_manifest.ConnectorManifest`:

  ``compile_manifest`` — manifest -> :class:`~connector_manifest.OntologySpec` (OWL terms).
  ``export_manifest_ttl`` — spec -> Turtle (generalized ``export_leanix_ttl``).
  ``apply_manifest`` — the generalized ``apply_leanix_metamodel``: fail-closed
    integrity/signature check, anti-sprawl enforcement, then regenerate/reconcile the
    connector's ``ontology_<source>.ttl`` and register promotable node types.
  ``manifest_from_leanix_spec`` — makes LeanIX the **first caller** of this generalized
    compiler (proved lossless by the golden-file test in ``tests/``), without touching
    the existing production ``sync_leanix_ontology`` entry point.

Pure, deterministic, zero LLM calls — every transformation here is a direct structural
projection of the manifest's own declared fields.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import TYPE_CHECKING, Any

from . import ontology_integrity
from .connector_manifest import (
    ConnectorManifest,
    OntologyClassSpec,
    OntologyDatatypePropertySpec,
    OntologyObjectPropertySpec,
    OntologySpec,
)

if TYPE_CHECKING:
    from .leanix_metamodel import LeanixOntologySpec

__all__ = [
    "AntiSprawlError",
    "SignatureVerificationError",
    "compile_manifest",
    "export_manifest_ttl",
    "apply_manifest",
    "is_wired",
    "manifest_from_leanix_spec",
]


class AntiSprawlError(RuntimeError):
    """Raised when a manifest's ontology IRI is neither wired into the canonical
    ``ontology.ttl`` nor an already-federated module — the fix is a ONE-line
    ``owl:imports`` edge (or federation registration), never a new top-level ``.ttl``."""


class SignatureVerificationError(RuntimeError):
    """Raised when ``provenance.integrity``/``signature`` fails fail-closed verification."""


def _humanize(camel: str) -> str:
    s = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", " ", camel)
    return s[:1].upper() + s[1:] if s else s


def compile_manifest(manifest: ConnectorManifest) -> OntologySpec:
    """Compile a :class:`ConnectorManifest` into a source-agnostic :class:`OntologySpec`."""
    spec = OntologySpec()
    seen_dtp: set[str] = set()

    for resource in manifest.resources:
        mapping = manifest.schema_mappings.get(resource.name)
        parent = mapping.ontology_class if mapping else None
        id_prefix = resource.id_prefix or resource.name.lower()
        spec.classes.append(
            OntologyClassSpec(
                local=resource.name,
                label=resource.label or _humanize(resource.name),
                parent=parent,
                id_prefix=id_prefix,
            )
        )
        spec.type_map[resource.name] = (resource.name, id_prefix)

        if mapping is not None:
            for fname, xsd in mapping.fields.items():
                if fname in seen_dtp:
                    continue
                seen_dtp.add(fname)
                spec.datatype_properties.append(
                    OntologyDatatypePropertySpec(
                        local=fname, label=_humanize(fname), range=xsd
                    )
                )

        for rel in resource.relations:
            lpg = rel.lpg_rel_type or _upper_snake(rel.name)
            spec.object_properties.append(
                OntologyObjectPropertySpec(
                    local=rel.name,
                    label=rel.label or _humanize(rel.name),
                    domain=resource.name,
                    range=rel.target,
                    lpg_rel_type=lpg,
                )
            )
            spec.relation_map[rel.name] = (lpg, rel.target)

    return spec


def _upper_snake(name: str) -> str:
    s = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", name)
    s = re.sub(r"(?<=[A-Z])(?=[A-Z][a-z])", "_", s)
    return s.upper()


def _ttl_header(source: str) -> str:
    return f"""\
# GENERATED by agent_utilities.knowledge_graph.ontology.manifest_compiler from
# connector_manifest.yml. Do not edit by hand — regenerate via
# ``scripts/generate_connector_manifests.py --connector {source}``.
# CONCEPT:AU-KG.ontology.connector-manifest-compiler.
@prefix : <http://knuckles.team/kg#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://knuckles.team/kg/{source}> a owl:Ontology ;
    rdfs:label "{source} Ontology (generated)" ;
    rdfs:comment "OWL mirror of the {source} connector manifest — every resource, relation, and field. CONCEPT:AU-KG.ontology.connector-manifest-compiler." ;
    owl:imports <http://knuckles.team/kg> .
"""


def export_manifest_ttl(spec: OntologySpec, *, source: str) -> str:
    """Serialize a compiled :class:`OntologySpec` to Turtle (generalized ``export_leanix_ttl``)."""
    lines: list[str] = [_ttl_header(source)]

    for c in sorted(spec.classes, key=lambda x: x.local):
        block = [f":{c.local} a owl:Class ;", f'    rdfs:label "{c.label}" ;']
        if c.parent:
            block.append(f"    rdfs:subClassOf :{c.parent} ;")
        block.append('    rdfs:comment "Connector resource (generated)." .')
        lines.append("\n".join(block))

    for p in sorted(spec.object_properties, key=lambda x: (x.local, x.domain or "")):
        rng = p.range if p.range == "owl:Thing" else f":{p.range}"
        block = [f":{p.local} a owl:ObjectProperty ;", f'    rdfs:label "{p.label}" ;']
        if p.domain:
            block.append(f"    rdfs:domain :{p.domain} ;")
        block.append(f"    rdfs:range {rng} .")
        lines.append("\n".join(block))

    for d in sorted(spec.datatype_properties, key=lambda x: x.local):
        lines.append(
            f":{d.local} a owl:DatatypeProperty ;\n"
            f'    rdfs:label "{d.label}" ;\n'
            f"    rdfs:range {d.range} ."
        )

    return "\n\n".join(lines) + "\n"


def _canonical_ontology_path() -> Path:
    return Path(__file__).resolve().parent.parent / "ontology.ttl"


def _canonical_owl_imports() -> set[str]:
    """The IRIs the bundled canonical ``ontology.ttl`` already ``owl:imports``."""
    import rdflib

    canon = _canonical_ontology_path()
    if not canon.exists():
        return set()
    g = rdflib.Graph()
    g.parse(str(canon), format="turtle")
    imports_pred = rdflib.URIRef("http://www.w3.org/2002/07/owl#imports")
    return {str(o) for o in g.objects(predicate=imports_pred)}


def is_wired(source: str) -> bool:
    """Whether ``http://knuckles.team/kg/<source>`` is already an owl:imports target of the
    canonical ontology.ttl OR a registered federated IRI — i.e. anti-sprawl is satisfied."""
    iri = f"http://knuckles.team/kg/{source}"
    if iri in _canonical_owl_imports():
        return True
    try:
        from ..core.ontology_federation import registered_federated_iris

        return iri in registered_federated_iris()
    except Exception:  # noqa: BLE001 — federation registry is best-effort here
        return False


def apply_manifest(
    manifest: ConnectorManifest,
    spec: OntologySpec | None = None,
    *,
    ttl_path: str | Path,
    dry_run: bool = False,
    trusted_signers: tuple[str, ...] = ontology_integrity.DEFAULT_TRUSTED_SIGNERS,
) -> dict[str, Any]:
    """Generalized ``apply_leanix_metamodel``: verify, anti-sprawl-check, then emit.

    Fail-closed (CONCEPT:AU-KG.ontology.supply-chain-integrity): the ``provenance.integrity`` hash
    and ``signature`` are re-verified against ``trusted_signers`` BEFORE anything is
    written — a bad/missing/unsigned manifest raises, it is never silently skipped.
    """
    source = manifest.resolved_ontology_source
    spec = spec if spec is not None else compile_manifest(manifest)
    ttl = export_manifest_ttl(spec, source=source)

    # ── fail-closed integrity + signature verification ──────────────────────
    import rdflib

    g = rdflib.Graph()
    g.parse(data=ttl, format="turtle")
    recomputed_hash, triple_count = ontology_integrity.canonical_hash(g)
    if recomputed_hash != manifest.provenance.integrity.hash:
        raise SignatureVerificationError(
            f"{manifest.connector}: recompiled canonical hash "
            f"{recomputed_hash} does not match provenance.integrity.hash "
            f"{manifest.provenance.integrity.hash} — the manifest was hand-edited "
            "after signing, or the compiler is non-deterministic. Regenerate."
        )
    if not ontology_integrity.verify(
        manifest.provenance.integrity.hash,
        manifest.provenance.signature,
        signer_id=manifest.provenance.signer,
        allowlist=trusted_signers,
    ):
        raise SignatureVerificationError(
            f"{manifest.connector}: provenance.signature failed verification "
            f"(signer={manifest.provenance.signer!r}) against the trusted-signer "
            f"allowlist {trusted_signers!r} — refusing to emit ontology output."
        )

    # ── anti-sprawl: extend an existing wired module, never sprawl a new one ──
    path = Path(ttl_path)
    already_wired = path.exists() or is_wired(source)
    if not already_wired:
        raise AntiSprawlError(
            f"{manifest.connector}: no existing {path.name} and "
            f"<http://knuckles.team/kg/{source}> is not owl:imports-ed by "
            f"the canonical ontology.ttl (nor federated). Add ONE line to "
            f"agent_utilities/knowledge_graph/ontology.ttl's owl:imports list — "
            f"`<http://knuckles.team/kg/{source}>` — (and register it in "
            f"docs/architecture/ontology_library.md) before this manifest may compile "
            f"into an ontology artifact. Never add an un-imported top-level .ttl."
        )

    result: dict[str, Any] = {
        "connector": manifest.connector,
        "classes": len(spec.classes),
        "object_properties": len(spec.object_properties),
        "datatype_properties": len(spec.datatype_properties),
        "ttl_path": str(path),
        "triple_count": triple_count,
        "canonical_hash": recomputed_hash,
        "dry_run": dry_run,
        "promoted_types": [c.local for c in spec.classes],
    }
    if dry_run:
        result["ttl_preview"] = ttl
        return result

    from ..core.owl_bridge import register_promotable_node_types

    register_promotable_node_types(c.local for c in spec.classes)
    path.write_text(ttl, encoding="utf-8")
    return result


def manifest_from_leanix_spec(
    spec: LeanixOntologySpec, *, source: str = "leanix"
) -> ConnectorManifest:
    """Adapt an already-compiled :class:`LeanixOntologySpec` into a :class:`ConnectorManifest`.

    Makes LeanIX the **first caller** of the generalized manifest compiler
    (CONCEPT:AU-KG.ontology.connector-manifest-compiler) without touching the existing
    production ``sync_leanix_ontology``/``apply_leanix_metamodel`` entry point — this is
    the seam the golden-file regression test exercises to prove
    ``export_manifest_ttl(compile_manifest(...))`` reproduces ``export_leanix_ttl`` losslessly.
    """
    from .connector_manifest import (
        IntegrityInfo,
        ProvenanceSpec,
        ResourceRelation,
        ResourceSpec,
        SchemaMapping,
    )

    relations_by_domain: dict[str, list[ResourceRelation]] = {}
    for p in spec.object_properties:
        relations_by_domain.setdefault(p.domain, []).append(
            ResourceRelation(
                name=p.local, label=p.label, target=p.range, lpg_rel_type=p.lpg_rel_type
            )
        )

    fields: dict[str, str] = {d.local: d.range for d in spec.datatype_properties}

    resources = [
        ResourceSpec(
            name=c.local,
            label=c.label,
            id_prefix=c.id_prefix,
            relations=relations_by_domain.get(c.local, []),
        )
        for c in spec.classes
    ]
    # Matches leanix_metamodel's global (domain-free) datatype-property pool: every
    # resource's schema mapping carries the full shared field vocabulary.
    schema_mappings = {
        c.local: SchemaMapping(ontology_class=c.parent, fields=dict(fields))
        for c in spec.classes
    }

    placeholder = ProvenanceSpec(
        generated_by="manifest_from_leanix_spec",
        integrity=IntegrityInfo(hash="0" * 64),
    )
    return ConnectorManifest(
        connector=source,
        resources=resources,
        schema_mappings=schema_mappings,
        provenance=placeholder,
    )
