"""R2RML mapping generator (CONCEPT:AU-KG.ontology.r2rml-generator) deterministic TriplesMap Turtle from a ConnectorManifest, per DEC-CA-06 — CA-23.

Generates R2RML ``TriplesMap`` Turtle deterministically from a
:class:`~connector_manifest.ConnectorManifest`, per ``DEC-CA-06``'s generation-rules
table:

============================================  =================================================
Manifest field                                R2RML output
============================================  =================================================
``resources[].name``                          ``rr:TriplesMap`` subject template root
``resources[].id_prefix``                     ``rr:template`` for ``rr:subjectMap``
``resources[].relations[].name``/``target``/   ``rr:predicateObjectMap`` with an ``rr:objectMap``
``lpg_rel_type``                               ``rr:parentTriplesMap`` reference to the target
                                                resource's TriplesMap
============================================  =================================================

Pure, deterministic, zero LLM calls — the same "structural projection" design as
:func:`manifest_compiler.compile_manifest`/``export_manifest_ttl``: this module reuses
``resource.name`` as the OWL class local name the exact same way ``compile_manifest``
does, so a TriplesMap's ``rr:class`` always matches what the compiled OWL spec would
assert for the same resource.

**Unmapped relation rule (mirrors ``DEC-CA-03``'s quarantine pattern):** a relation whose
``target`` does not resolve to another resource *declared in the same manifest* (the
common case: ``target: owl:Thing`` for a relation the source ontology never attached to a
resolved ``rdfs:domain`` — see the ``review_todos`` entries every generated
``connector_manifest.yml`` carries for exactly this residue) never gets a guessed
``rr:parentTriplesMap`` — it is *never emitted*, and reported back to the caller via
:func:`generate_r2rml_report` so a pipeline can log it, not silently drop it.

**W02 measured scope note (2026-08-26):** this generator targets the R2RML/OBDA
consumer — a SQL-table-backed virtual graph evaluated by eg's
``Method.SparqlVirtual``/:class:`epistemic_graph.client.ObdaClient` (CA-13, landed). It
does *not* by itself reproduce the field-extraction-from-arbitrary-API-payload shape
``owl_bridge.stream_api_to_graph``'s inline, hand-maintained ``r2rml_mappings`` dict drives — that is a
structurally different consumer (LPG hydration from a streamed API payload, not a SQL
row exposed as RDF). :func:`derive_stream_mapping` produces the *closest* structural
equivalent from the same manifest data for the dict-parity comparison CA-23-W05 requires;
see its docstring for the measured parity gap against the 3 sources the dict covers today.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from .connector_manifest import ConnectorManifest

__all__ = [
    "R2rmlGenerationReport",
    "generate_r2rml",
    "generate_r2rml_report",
    "derive_stream_mapping",
    "unmapped_relations",
]

_RR = "http://www.w3.org/ns/r2rml#"
_KG = "http://knuckles.team/kg#"


@dataclass(frozen=True)
class R2rmlGenerationReport:
    """The Turtle output plus the bookkeeping a pipeline/test needs to log or assert on."""

    turtle: str
    mapped_resources: tuple[str, ...] = field(default_factory=tuple)
    unmapped_relations: tuple[str, ...] = field(default_factory=tuple)
    triples_map_count: int = 0
    predicate_object_map_count: int = 0


def _r2rml_header(source: str) -> str:
    return f"""\
# GENERATED by agent_utilities.knowledge_graph.ontology.r2rml_generator from
# connector_manifest.yml. Do not edit by hand — regenerate via
# ``r2rml_generator.generate_r2rml``. CONCEPT:AU-KG.ontology.r2rml-generator.
@prefix rr: <{_RR}> .
@prefix : <{_KG}> .
"""


def unmapped_relations(manifest: ConnectorManifest) -> list[str]:
    """Relations whose ``target`` does not resolve to another resource declared in
    ``manifest.resources`` — never guessed, always reported (``DEC-CA-06``)."""
    resource_names = {r.name for r in manifest.resources}
    out: list[str] = []
    for resource in manifest.resources:
        for rel in resource.relations:
            if rel.target not in resource_names:
                out.append(f"{resource.name}.{rel.name} -> {rel.target}")
    return out


def generate_r2rml_report(manifest: ConnectorManifest) -> R2rmlGenerationReport:
    """Compile ``manifest`` into R2RML Turtle plus the generation bookkeeping.

    One ``rr:TriplesMap`` per resource (``rr:logicalTable`` keyed by the resource's own
    name — the SQL table name a caller must register via
    :class:`epistemic_graph.client.QueryClient` DDL before
    :meth:`epistemic_graph.client.ObdaClient.evaluate` can resolve it, per CA-13's W02
    design note), with:

      * ``rr:subjectMap`` templated on ``id_prefix`` (falling back to the resource's
        lowercased name, matching ``manifest_compiler.compile_manifest``'s own default)
        and asserting ``rr:class`` = the resource's OWL class IRI.
      * one ``rr:predicateObjectMap`` per declared ``schema_mappings[resource].fields``
        entry (``rr:column`` = the field name — the raw R2RML column-mapping case).
      * one ``rr:predicateObjectMap`` per relation whose ``target`` resolves to another
        resource in this manifest, with ``rr:objectMap [ rr:parentTriplesMap
        <#TriplesMap_<target>> ]`` — the join case. A relation whose target does not
        resolve is skipped (see :func:`unmapped_relations`) rather than guessed.

    Resources are emitted in sorted-name order (deterministic byte-identical output for
    the same manifest, matching ``export_manifest_ttl``'s own convention).
    """
    resource_names = {r.name for r in manifest.resources}
    source = manifest.resolved_ontology_source
    lines: list[str] = [_r2rml_header(source)]
    mapped: list[str] = []
    skipped: list[str] = []
    tm_count = 0
    pom_count = 0

    for resource in sorted(manifest.resources, key=lambda r: r.name):
        id_prefix = resource.id_prefix or resource.name.lower()
        tm_name = f"TriplesMap_{resource.name}"
        block: list[str] = [
            f"<#{tm_name}>",
            f'    rr:logicalTable [ rr:tableName "{resource.name}" ] ;',
            "    rr:subjectMap [",
            f'        rr:template "http://knuckles.team/kg/{id_prefix}/{{id}}" ;',
            f"        rr:class :{resource.name} ;",
            "    ] ;",
        ]
        tm_count += 1

        poms: list[str] = []
        mapping = manifest.schema_mappings.get(resource.name)
        if mapping is not None:
            for fname in sorted(mapping.fields):
                poms.append(
                    "    rr:predicateObjectMap [ "
                    f"rr:predicate :{fname} ; "
                    f'rr:objectMap [ rr:column "{fname}" ] ] ;'
                )
                pom_count += 1

        for rel in resource.relations:
            if rel.target not in resource_names:
                skipped.append(f"{resource.name}.{rel.name} -> {rel.target}")
                continue
            poms.append(
                "    rr:predicateObjectMap [\n"
                f"        rr:predicate :{rel.name} ;\n"
                "        rr:objectMap [ "
                f"rr:parentTriplesMap <#TriplesMap_{rel.target}> ] ;\n"
                "    ] ;"
            )
            pom_count += 1

        block.extend(poms)
        # Close the TriplesMap block: last statement ends with '.', not ';'.
        block[-1] = block[-1][: block[-1].rfind(" ;")] + " ."
        lines.append("\n".join(block))
        mapped.append(resource.name)

    turtle = "\n\n".join(lines) + "\n"
    return R2rmlGenerationReport(
        turtle=turtle,
        mapped_resources=tuple(mapped),
        unmapped_relations=tuple(skipped),
        triples_map_count=tm_count,
        predicate_object_map_count=pom_count,
    )


def generate_r2rml(manifest: ConnectorManifest) -> str:
    """Return only the Turtle document — the common case for a caller (e.g.
    :mod:`pack_pipeline`, or a direct :meth:`epistemic_graph.client.ObdaClient.load`
    call) that does not need the generation report. See :func:`generate_r2rml_report`
    for the full bookkeeping (mapped resources, skipped/unmapped relations, counts)."""
    return generate_r2rml_report(manifest).turtle


def derive_stream_mapping(
    manifest: ConnectorManifest, resource_name: str
) -> dict[str, Any] | None:
    """Derive the ``owl_bridge.stream_api_to_graph``-shaped mapping dict (``class``,
    ``id_field``, ``properties``, ``edges``) for one resource, from the SAME manifest
    data :func:`generate_r2rml_report` consumes — the CA-23-W05 dict-parity comparison
    this function exists for.

    Returns ``None`` if ``resource_name`` is not declared in ``manifest.resources``.

    **Measured parity gap (CA-23-W05, 2026-08-26):** for the 3 sources
    ``owl_bridge.py``'s hand-maintained dict covers today (``servicenow:incident``,
    ``gitlab:project``, ``gitlab:pipeline``), the live ``connector_manifest.yml`` files
    declare **``relations: []``** for the corresponding resources (``Incident``,
    ``Project``, ``Pipeline``) — every edge the dict hand-encodes
    (``assigned_to``/``cmdb_ci`` on Incident, ``owner`` on Project, ``project_id`` on
    Pipeline) is present in the connector's *source* ontology only as an *unattached*
    relation, called out by name in each manifest's own ``review_todos`` (e.g.
    ``"relation 'assignedTo' has no declared rdfs:domain ... not attached to any
    resource"``) — not as a ``ResourceRelation`` on the resource itself. This function
    therefore returns an ``edges: {}`` for all 3 today: it cannot invent an edge the
    manifest does not carry (mirrors the same never-guess rule
    :func:`unmapped_relations` enforces), so it does NOT reach parity with the dict's
    edge coverage. The class/id_field mapping is reachable; the edges are not, until the
    upstream connector ontology attaches those relations' ``rdfs:domain`` and manifests
    are regenerated. Per ``DEC-CA-06``'s own rollback clause and this lane's brief:
    ``owl_bridge.py``'s dict is kept, not deleted, until that upstream gap closes —
    dropping the 4 edges above silently would be a real behavior regression.
    """
    resource = next((r for r in manifest.resources if r.name == resource_name), None)
    if resource is None:
        return None
    mapping = manifest.schema_mappings.get(resource_name)
    properties = sorted(mapping.fields) if mapping is not None else []
    edges: dict[str, tuple[str, str]] = {}
    for rel in resource.relations:
        lpg_rel_type = rel.lpg_rel_type or rel.name
        edges[rel.name] = (rel.target, lpg_rel_type)
    id_field = resource.id_prefix or resource.name.lower()
    return {
        "class": resource.name,
        "id_field": id_field,
        "properties": properties,
        "edges": edges,
    }
