apiVersion: v1
kind: Namespace
metadata:
  name: graphos-control
  labels:
    graphos.io/plane: control
    graphos.io/mtls: required
    istio-injection: enabled
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: graphos-cell
  labels:
    graphos.io/plane: cell
    graphos.io/mtls: required
    istio-injection: enabled
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
