#!/usr/bin/python
from __future__ import annotations

"""CONCEPT:AHE-3.2 — Evolutionary Variant Selection.

Manages competing variants of prompts, skills, or sub-graph configurations
using a dual-strategy generation approach (LLM-driven + parametric mutations)
and tournament-based fitness selection.

Integrates with:
    - CONCEPT:ORCH-1.1 (AHE): ``EvolveAgent`` generates LLM-driven variants
    - CONCEPT:KG-2.0 (OGM): ``KGMapper`` for declarative persistence
    - Existing KG: ``OutcomeEvaluationNode.reward`` for fitness signals
    - Existing edges: ``EVOLVED_FROM``, ``SUPERSEDES``, ``VARIANT_OF``

See docs/pillars/architecture_c4.md §CONCEPT:ORCH-1.0
"""


import logging
import random
import time
import uuid
from typing import TYPE_CHECKING, Any

from ..knowledge_graph.core.ogm import KGMapper
from ..models.knowledge_graph import (
    RegistryEdgeType,
    RegistryNode,
    SystemPromptNode,
)

if TYPE_CHECKING:
    from ..knowledge_graph.core.engine import IntelligenceGraphEngine

logger = logging.getLogger(__name__)


class VariantPool:
    """Manages competing variants with dual generation and tournament selection.

    CONCEPT:AHE-3.2 — Evolutionary Variant Selection

    This module provides a lightweight evolutionary harness that operates on
    existing Pydantic node types (``SystemPromptNode``, ``ProposedSkillNode``,
    etc.) without requiring external GP libraries. It leverages the existing
    AHE infrastructure:

    - **LLM-driven variants**: Generated by ``EvolveAgent`` from critique signals
    - **Parametric variants**: Generated by mutating configuration parameters
      (temperature, template swaps, tool subsets, model IDs)
    - **Fitness evaluation**: Aggregated from ``OutcomeEvaluationNode.reward``
      linked to episodes that used the variant
    - **Selection**: Tournament-based, with configurable pressure

    Lifecycle::

        register_variant() → evaluate_fitness() → tournament_select()
        → promote_winner() → prune_losers()

    Args:
        engine: The ``IntelligenceGraphEngine`` to query for fitness data.
    """

    def __init__(self, engine: IntelligenceGraphEngine) -> None:
        self.engine = engine
        self.ogm = KGMapper(engine)
        # CONCEPT:AHE-3.2 — per-base population-drift monitors (W1 collapse detection)
        self._drift_monitors: dict[str, Any] = {}

    def population_health(
        self,
        base_id: str,
        *,
        collapse_threshold: float = 0.05,
        patience: int = 2,
    ) -> dict[str, Any]:
        """Assess population diversity / collapse for a base's variants (CONCEPT:AHE-3.2).

        Tracks the variant-fitness distribution across calls with a
        :class:`PopulationDriftMonitor`: ``spread`` (within-generation dispersion),
        ``drift`` (W1 vs the previous generation), and ``collapsed`` (spread low
        for ``patience`` consecutive generations) — the diversity-collapse signal
        that should arm early-stop in verifier-free evolution.

        Returns:
            ``{population, spread, drift, collapsed, low_streak}``.
        """
        from ..graph.population_drift import PopulationDriftMonitor

        scores = [
            float(v.get("fitness", 0.0) or 0.0) for v in self.get_variants(base_id)
        ]
        monitor = self._drift_monitors.get(base_id)
        if monitor is None:
            monitor = PopulationDriftMonitor(
                collapse_threshold=collapse_threshold, patience=patience
            )
            self._drift_monitors[base_id] = monitor
        reading = monitor.update(scores)
        return {
            "population": reading.population,
            "spread": reading.spread,
            "drift": reading.drift,
            "collapsed": reading.collapsed,
            "low_streak": reading.low_streak,
        }

    # ── Registration ──────────────────────────────────────────────────

    def register_variant(
        self,
        base_id: str,
        variant: RegistryNode,
        generation: int = 0,
        strategy: str = "llm",
    ) -> str:
        """Register a new variant derived from a base component.

        Creates the variant node in the KG and links it to the base via
        ``VARIANT_OF`` and ``EVOLVED_FROM`` edges.

        Args:
            base_id: ID of the original (base) component.
            variant: The Pydantic model for the new variant.
            generation: The generation number (0 = first mutation).
            strategy: ``"llm"`` or ``"parametric"`` — how this variant was created.

        Returns:
            The ID of the newly registered variant.
        """
        variant.metadata = {
            **variant.metadata,
            "generation": generation,
            "strategy": strategy,
            "created_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        }

        # Persist via OGM
        self.ogm.upsert(variant)

        # Link variant → base
        self.ogm.upsert_edge(
            variant.id,
            base_id,
            RegistryEdgeType.VARIANT_OF,
            {"generation": generation, "strategy": strategy},
        )
        self.ogm.upsert_edge(
            variant.id,
            base_id,
            RegistryEdgeType.EVOLVED_FROM,
        )

        logger.info(
            "Registered variant %s (gen=%d, strategy=%s) of base %s",
            variant.id,
            generation,
            strategy,
            base_id,
        )
        return variant.id

    # ── Dual Generation ───────────────────────────────────────────────

    def generate_parametric_variant(
        self,
        base_node: RegistryNode,
        mutations: dict[str, Any],
    ) -> RegistryNode:
        """Generate a variant by applying parameterized mutations.

        Supported mutation keys depend on the node type:
            - ``temperature``: Adjust numeric confidence/threshold fields
            - ``content_prefix``: Prepend text to prompt content
            - ``content_suffix``: Append text to prompt content
            - ``metadata_overrides``: Override metadata fields

        Args:
            base_node: The original node to mutate.
            mutations: Dict of mutation type → value.

        Returns:
            A new Pydantic model instance with mutations applied.
        """
        data = base_node.model_dump()
        variant_id = f"var:{uuid.uuid4().hex[:8]}"
        data["id"] = variant_id
        data["name"] = f"{base_node.name} (variant)"

        # Apply mutations
        if "content_prefix" in mutations and "content" in data:
            data["content"] = mutations["content_prefix"] + "\n" + data["content"]
        if "content_suffix" in mutations and "content" in data:
            data["content"] = data["content"] + "\n" + mutations["content_suffix"]
        if "metadata_overrides" in mutations:
            data["metadata"] = {
                **data.get("metadata", {}),
                **mutations["metadata_overrides"],
            }

        # For SystemPromptNode, also mutate system_prompt if present
        if isinstance(base_node, SystemPromptNode):
            if "content_prefix" in mutations:
                data["content"] = (
                    mutations["content_prefix"] + "\n" + data.get("content", "")
                )
            if "content_suffix" in mutations:
                data["content"] = (
                    data.get("content", "") + "\n" + mutations["content_suffix"]
                )

        return type(base_node).model_validate(data)

    # ── Fitness Evaluation ────────────────────────────────────────────

    def evaluate_fitness(self, variant_id: str) -> float:
        """Compute fitness score for a variant from linked outcome evaluations.

        Fitness = mean(reward) across all ``OutcomeEvaluation`` nodes
        reachable via::

            (variant)-[:EVOLVED_FROM|VARIANT_OF]->...<-[:USES|EXECUTED_BY]-(episode)
            -[:PRODUCED_OUTCOME]->(evaluation)

        Falls back to 0.0 if no evaluations are found.

        Args:
            variant_id: The variant node ID.

        Returns:
            Mean reward score in [0.0, 1.0], or 0.0 if no data.
        """
        if self.engine.backend:
            query = """
            MATCH (v {id: $vid})<-[:USES|EXECUTED_BY]-(ep)
            -[:PRODUCED_OUTCOME]->(eval:OutcomeEvaluation)
            RETURN avg(eval.reward) as fitness, count(eval) as sample_size
            """
            results = self.engine.backend.execute(query, {"vid": variant_id})
            if results and results[0].get("fitness") is not None:
                fitness = float(results[0]["fitness"])
                sample_size = int(results[0].get("sample_size", 0))
                logger.debug(
                    "Fitness for %s: %.3f (n=%d)", variant_id, fitness, sample_size
                )
                return fitness

        # graph compute fallback: traverse locally
        if variant_id not in self.engine.graph:
            return 0.0

        rewards = []
        for pred in self.engine.graph.predecessors(variant_id):
            for succ in self.engine.graph.successors(pred):
                node_data = self.engine.graph.nodes.get(succ, {})
                if node_data.get("type") == "outcome_evaluation":
                    reward = node_data.get("reward", 0.0)
                    rewards.append(float(reward))

        return sum(rewards) / len(rewards) if rewards else 0.0

    # ── Selection ─────────────────────────────────────────────────────

    def get_variants(self, base_id: str) -> list[dict[str, Any]]:
        """Retrieve all variants of a base component with their fitness scores.

        Args:
            base_id: The base component node ID.

        Returns:
            List of dicts with ``id``, ``name``, ``generation``, ``fitness``.
        """
        variants: list[dict[str, Any]] = []

        if self.engine.backend:
            query = """
            MATCH (v)-[:VARIANT_OF]->(base {id: $bid})
            RETURN v.id as id, v.name as name, v.metadata as metadata
            """
            results = self.engine.backend.execute(query, {"bid": base_id})
            for row in results:
                vid = row.get("id", "")
                fitness = self.evaluate_fitness(vid)
                import json

                meta = row.get("metadata", "{}")
                if isinstance(meta, str):
                    meta = json.loads(meta)
                variants.append(
                    {
                        "id": vid,
                        "name": row.get("name", ""),
                        "generation": meta.get("generation", 0),
                        "fitness": fitness,
                    }
                )
        else:
            # graph compute fallback
            if base_id not in self.engine.graph:
                return variants
            for succ in self.engine.graph.predecessors(base_id):
                edge_data = self.engine.graph.get_edge_data(succ, base_id)
                if edge_data:
                    for _, edata in edge_data.items():
                        if edata.get("type") == RegistryEdgeType.VARIANT_OF:
                            fitness = self.evaluate_fitness(succ)
                            ndata = self.engine.graph.nodes.get(succ, {})
                            meta = ndata.get("metadata", {})
                            variants.append(
                                {
                                    "id": succ,
                                    "name": ndata.get("name", ""),
                                    "generation": meta.get("generation", 0),
                                    "fitness": fitness,
                                }
                            )

        return sorted(variants, key=lambda v: v["fitness"], reverse=True)

    def tournament_select(
        self,
        base_id: str,
        top_k: int = 3,
        tournament_size: int = 2,
        strategy: str = "tournament",
    ) -> list[str]:
        """Select the fittest variants.

        Args:
            base_id: The base component node ID.
            top_k: Number of winners to select.
            tournament_size: Competitors per tournament round (``tournament`` strategy).
            strategy: Selection operator (CONCEPT:ORCH-1.30). ``"tournament"``
                (default) keeps the stochastic tournament; ``"score"`` takes the
                top-k by mean fitness; ``"lcb"`` takes the top-k by the
                uncertainty-aware lower bound ``fitness − κ·fitness_std`` so a
                lucky high-variance variant doesn't out-promote a reliable one.

        Returns:
            List of variant IDs (winners), best first.
        """
        variants = self.get_variants(base_id)
        if len(variants) <= top_k:
            return [v["id"] for v in variants]

        if strategy in ("score", "lcb"):
            from .selection_operators import select_top_k

            return [v["id"] for v in select_top_k(variants, top_k, method=strategy)]

        winners: list[dict[str, Any]] = []
        pool = list(variants)

        for _ in range(top_k):
            if len(pool) < tournament_size:
                break
            competitors = random.sample(pool, min(tournament_size, len(pool)))  # nosec B311
            winner = max(competitors, key=lambda v: v["fitness"])
            winners.append(winner)
            pool.remove(winner)

        return [w["id"] for w in winners]

    def prune_losers(self, base_id: str, keep: int = 3) -> int:
        """Remove underperforming variants, keeping only the top ``keep``.

        Args:
            base_id: The base component node ID.
            keep: Number of top-performing variants to retain.

        Returns:
            Number of variants pruned.
        """
        variants = self.get_variants(base_id)
        if len(variants) <= keep:
            return 0

        to_prune = variants[keep:]  # Already sorted by fitness desc
        pruned = 0
        for v in to_prune:
            if self.ogm.delete(v["id"]):
                pruned += 1
                logger.info("Pruned variant %s (fitness=%.3f)", v["id"], v["fitness"])

        return pruned

    def promote_winner(self, variant_id: str, base_id: str) -> None:
        """Promote a variant to become the new baseline.

        Creates a ``SUPERSEDES`` edge from the winner to the old base,
        signaling that the variant should replace it in future routing.

        Args:
            variant_id: The winning variant's ID.
            base_id: The previous baseline's ID.
        """
        self.ogm.upsert_edge(
            variant_id,
            base_id,
            RegistryEdgeType.SUPERSEDES,
            {"promoted_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())},
        )
        logger.info("Promoted variant %s → supersedes base %s", variant_id, base_id)

    # CONCEPT:AHE-3.38 — Evolvable sampling profiles via parametric variant mutation scored by the capability-reward EMA and tournament-promoted per task-class into the live model registry.
    # The parametric-variant dimension this module's docstring has always named
    # ("mutating configuration parameters (temperature, ...)") wired into a live
    # tournament: mutate a task-class profile, score each child by the capability
    # reward EMA (record_outcome), and promote the winner back into the registry's
    # task_class_profiles — which the router/factory (ORCH-1.57) read on the next run.

    def _profile_id(self, task_class: str, profile: Any) -> str:
        """Stable reward-EMA key for a profile variant (CONCEPT:AHE-3.38)."""
        knobs = profile.model_dump(
            include={
                "temperature",
                "top_p",
                "top_k",
                "min_p",
                "repetition_penalty",
                "max_tokens",
                "presence_penalty",
                "frequency_penalty",
            }
        )
        digest = uuid.uuid5(uuid.NAMESPACE_OID, repr(sorted(knobs.items()))).hex[:8]
        return f"profile:{task_class}:{digest}"

    def mutate_profile(
        self,
        base: Any,
        *,
        count: int = 4,
        jitter: float = 0.15,
        rng: random.Random | None = None,
    ) -> list[Any]:
        """Produce ``count`` jittered child profiles within the ontology bounds.

        CONCEPT:AHE-3.38. Gaussian jitter on the float knobs and ±1-step jitter on
        the integer knobs, clamped to the pydantic field ranges and then filtered
        through the KG-2.93 value-type SHACL gate (``sampling_profile_violations``),
        so a malformed mutation can never enter the tournament. ``source`` is set to
        ``"learned"`` to mark provenance.
        """
        from agent_utilities.knowledge_graph.ontology.value_types import (
            sampling_profile_violations,
        )

        r = rng or random.Random()
        out: list[Any] = []
        for _ in range(count):
            data = base.model_dump()
            data["source"] = "learned"
            if data.get("temperature") is not None:
                data["temperature"] = min(
                    2.0, max(0.0, data["temperature"] + r.gauss(0, jitter))
                )
            if data.get("top_p") is not None:
                data["top_p"] = min(1.0, max(0.0, data["top_p"] + r.gauss(0, jitter)))
            if data.get("min_p") is not None:
                data["min_p"] = min(
                    1.0, max(0.0, data["min_p"] + r.gauss(0, jitter / 3))
                )
            if data.get("top_k") is not None:
                data["top_k"] = max(1, data["top_k"] + r.choice([-5, 0, 5, 10]))
            if data.get("repetition_penalty") is not None:
                data["repetition_penalty"] = max(
                    0.01, data["repetition_penalty"] + r.gauss(0, jitter / 3)
                )
            try:
                child = type(base).model_validate(data)
            except Exception:  # noqa: BLE001 - skip out-of-range mutations
                continue
            if sampling_profile_violations(child.model_dump()):
                continue
            out.append(child)
        return out

    def evolve_profile(
        self,
        registry: Any,
        task_class: str,
        capability_index: Any,
        evaluator: Any,
        *,
        count: int = 4,
        rng: random.Random | None = None,
    ) -> Any:
        """Run one mutate→score→tournament→promote round for a task-class profile.

        CONCEPT:AHE-3.38 — the live loop. Mutates the current
        :meth:`~agent_utilities.models.model_registry.ModelRegistry.pick_profile_for_task`
        profile, evaluates each candidate (and the incumbent) via ``evaluator``
        (a ``Callable[[SamplingProfile], float]`` returning a reward in ``[0, 1]``
        — the live eval slice that runs the agent under that profile), records the
        reward EMA via ``capability_index.record_outcome``, then promotes the
        highest-EMA candidate into ``registry.task_class_profiles`` (via
        ``set_task_profile``) so the next route picks it up. Returns the promoted
        profile (the incumbent if no challenger beat it).
        """
        incumbent = registry.pick_profile_for_task(task_class)
        candidates = [incumbent, *self.mutate_profile(incumbent, count=count, rng=rng)]

        best_profile = incumbent
        best_reward = -1.0
        for profile in candidates:
            pid = self._profile_id(task_class, profile)
            try:
                reward = float(evaluator(profile))
            except Exception:  # noqa: BLE001 - a failed eval scores as worst
                reward = 0.0
            ema = capability_index.record_outcome(pid, reward=reward)
            if ema > best_reward:
                best_reward, best_profile = ema, profile

        promoted = best_profile.model_copy(
            update={"task_class": task_class, "source": "learned"}
        )
        registry.set_task_profile(promoted)
        logger.info(
            "Evolved profile for %s → temp=%s (reward EMA=%.3f)",
            task_class,
            promoted.temperature,
            best_reward,
        )
        return promoted
