#!/usr/bin/python
"""CONCEPT:AHE-3.2 — Evolutionary Variant Selection.

Manages competing variants of prompts, skills, or sub-graph configurations
using a dual-strategy generation approach (LLM-driven + parametric mutations)
and tournament-based fitness selection.

Integrates with:
    - CONCEPT:ORCH-1.1 (AHE): ``EvolveAgent`` generates LLM-driven variants
    - CONCEPT:KG-2.0 (OGM): ``KGMapper`` for declarative persistence
    - Existing KG: ``OutcomeEvaluationNode.reward`` for fitness signals
    - Existing edges: ``EVOLVED_FROM``, ``SUPERSEDES``, ``VARIANT_OF``

See docs/emergent-architecture.md §CONCEPT:ORCH-1.0.
"""

from __future__ import annotations

import logging
import random
import time
import uuid
from typing import TYPE_CHECKING, Any

from ..knowledge_graph.ogm import KGMapper
from ..models.knowledge_graph import (
    RegistryEdgeType,
    RegistryNode,
    SystemPromptNode,
)

if TYPE_CHECKING:
    from ..knowledge_graph.engine import IntelligenceGraphEngine

logger = logging.getLogger(__name__)


class VariantPool:
    """Manages competing variants with dual generation and tournament selection.

    CONCEPT:AHE-3.2 — Evolutionary Variant Selection

    This module provides a lightweight evolutionary harness that operates on
    existing Pydantic node types (``SystemPromptNode``, ``ProposedSkillNode``,
    etc.) without requiring external GP libraries. It leverages the existing
    AHE infrastructure:

    - **LLM-driven variants**: Generated by ``EvolveAgent`` from critique signals
    - **Parametric variants**: Generated by mutating configuration parameters
      (temperature, template swaps, tool subsets, model IDs)
    - **Fitness evaluation**: Aggregated from ``OutcomeEvaluationNode.reward``
      linked to episodes that used the variant
    - **Selection**: Tournament-based, with configurable pressure

    Lifecycle::

        register_variant() → evaluate_fitness() → tournament_select()
        → promote_winner() → prune_losers()

    Args:
        engine: The ``IntelligenceGraphEngine`` to query for fitness data.
    """

    def __init__(self, engine: IntelligenceGraphEngine) -> None:
        self.engine = engine
        self.ogm = KGMapper(engine)

    # ── Registration ──────────────────────────────────────────────────

    def register_variant(
        self,
        base_id: str,
        variant: RegistryNode,
        generation: int = 0,
        strategy: str = "llm",
    ) -> str:
        """Register a new variant derived from a base component.

        Creates the variant node in the KG and links it to the base via
        ``VARIANT_OF`` and ``EVOLVED_FROM`` edges.

        Args:
            base_id: ID of the original (base) component.
            variant: The Pydantic model for the new variant.
            generation: The generation number (0 = first mutation).
            strategy: ``"llm"`` or ``"parametric"`` — how this variant was created.

        Returns:
            The ID of the newly registered variant.
        """
        variant.metadata = {
            **variant.metadata,
            "generation": generation,
            "strategy": strategy,
            "created_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        }

        # Persist via OGM
        self.ogm.upsert(variant)

        # Link variant → base
        self.ogm.upsert_edge(
            variant.id,
            base_id,
            RegistryEdgeType.VARIANT_OF,
            {"generation": generation, "strategy": strategy},
        )
        self.ogm.upsert_edge(
            variant.id,
            base_id,
            RegistryEdgeType.EVOLVED_FROM,
        )

        logger.info(
            "Registered variant %s (gen=%d, strategy=%s) of base %s",
            variant.id,
            generation,
            strategy,
            base_id,
        )
        return variant.id

    # ── Dual Generation ───────────────────────────────────────────────

    def generate_parametric_variant(
        self,
        base_node: RegistryNode,
        mutations: dict[str, Any],
    ) -> RegistryNode:
        """Generate a variant by applying parameterized mutations.

        Supported mutation keys depend on the node type:
            - ``temperature``: Adjust numeric confidence/threshold fields
            - ``content_prefix``: Prepend text to prompt content
            - ``content_suffix``: Append text to prompt content
            - ``metadata_overrides``: Override metadata fields

        Args:
            base_node: The original node to mutate.
            mutations: Dict of mutation type → value.

        Returns:
            A new Pydantic model instance with mutations applied.
        """
        data = base_node.model_dump()
        variant_id = f"var:{uuid.uuid4().hex[:8]}"
        data["id"] = variant_id
        data["name"] = f"{base_node.name} (variant)"

        # Apply mutations
        if "content_prefix" in mutations and "content" in data:
            data["content"] = mutations["content_prefix"] + "\n" + data["content"]
        if "content_suffix" in mutations and "content" in data:
            data["content"] = data["content"] + "\n" + mutations["content_suffix"]
        if "metadata_overrides" in mutations:
            data["metadata"] = {
                **data.get("metadata", {}),
                **mutations["metadata_overrides"],
            }

        # For SystemPromptNode, also mutate system_prompt if present
        if isinstance(base_node, SystemPromptNode):
            if "content_prefix" in mutations:
                data["content"] = (
                    mutations["content_prefix"] + "\n" + data.get("content", "")
                )
            if "content_suffix" in mutations:
                data["content"] = (
                    data.get("content", "") + "\n" + mutations["content_suffix"]
                )

        return type(base_node).model_validate(data)

    # ── Fitness Evaluation ────────────────────────────────────────────

    def evaluate_fitness(self, variant_id: str) -> float:
        """Compute fitness score for a variant from linked outcome evaluations.

        Fitness = mean(reward) across all ``OutcomeEvaluation`` nodes
        reachable via::

            (variant)-[:EVOLVED_FROM|VARIANT_OF]->...<-[:USES|EXECUTED_BY]-(episode)
            -[:PRODUCED_OUTCOME]->(evaluation)

        Falls back to 0.0 if no evaluations are found.

        Args:
            variant_id: The variant node ID.

        Returns:
            Mean reward score in [0.0, 1.0], or 0.0 if no data.
        """
        if self.engine.backend:
            query = """
            MATCH (v {id: $vid})<-[:USES|EXECUTED_BY]-(ep)
            -[:PRODUCED_OUTCOME]->(eval:OutcomeEvaluation)
            RETURN avg(eval.reward) as fitness, count(eval) as sample_size
            """
            results = self.engine.backend.execute(query, {"vid": variant_id})
            if results and results[0].get("fitness") is not None:
                fitness = float(results[0]["fitness"])
                sample_size = int(results[0].get("sample_size", 0))
                logger.debug(
                    "Fitness for %s: %.3f (n=%d)", variant_id, fitness, sample_size
                )
                return fitness

        # NetworkX fallback: traverse locally
        if variant_id not in self.engine.graph:
            return 0.0

        rewards = []
        for pred in self.engine.graph.predecessors(variant_id):
            for succ in self.engine.graph.successors(pred):
                node_data = self.engine.graph.nodes.get(succ, {})
                if node_data.get("type") == "outcome_evaluation":
                    reward = node_data.get("reward", 0.0)
                    rewards.append(float(reward))

        return sum(rewards) / len(rewards) if rewards else 0.0

    # ── Selection ─────────────────────────────────────────────────────

    def get_variants(self, base_id: str) -> list[dict[str, Any]]:
        """Retrieve all variants of a base component with their fitness scores.

        Args:
            base_id: The base component node ID.

        Returns:
            List of dicts with ``id``, ``name``, ``generation``, ``fitness``.
        """
        variants: list[dict[str, Any]] = []

        if self.engine.backend:
            query = """
            MATCH (v)-[:VARIANT_OF]->(base {id: $bid})
            RETURN v.id as id, v.name as name, v.metadata as metadata
            """
            results = self.engine.backend.execute(query, {"bid": base_id})
            for row in results:
                vid = row.get("id", "")
                fitness = self.evaluate_fitness(vid)
                import json

                meta = row.get("metadata", "{}")
                if isinstance(meta, str):
                    meta = json.loads(meta)
                variants.append(
                    {
                        "id": vid,
                        "name": row.get("name", ""),
                        "generation": meta.get("generation", 0),
                        "fitness": fitness,
                    }
                )
        else:
            # NetworkX fallback
            if base_id not in self.engine.graph:
                return variants
            for succ in self.engine.graph.predecessors(base_id):
                edge_data = self.engine.graph.get_edge_data(succ, base_id)
                if edge_data:
                    for _, edata in edge_data.items():
                        if edata.get("type") == RegistryEdgeType.VARIANT_OF:
                            fitness = self.evaluate_fitness(succ)
                            ndata = self.engine.graph.nodes.get(succ, {})
                            meta = ndata.get("metadata", {})
                            variants.append(
                                {
                                    "id": succ,
                                    "name": ndata.get("name", ""),
                                    "generation": meta.get("generation", 0),
                                    "fitness": fitness,
                                }
                            )

        return sorted(variants, key=lambda v: v["fitness"], reverse=True)

    def tournament_select(
        self,
        base_id: str,
        top_k: int = 3,
        tournament_size: int = 2,
    ) -> list[str]:
        """Select the fittest variants using tournament selection.

        Samples ``tournament_size`` variants at a time and keeps the winner.
        Repeats until ``top_k`` winners are collected.

        Args:
            base_id: The base component node ID.
            top_k: Number of winners to select.
            tournament_size: Number of competitors per tournament round.

        Returns:
            List of variant IDs (winners), sorted by fitness descending.
        """
        variants = self.get_variants(base_id)
        if len(variants) <= top_k:
            return [v["id"] for v in variants]

        winners: list[dict[str, Any]] = []
        pool = list(variants)

        for _ in range(top_k):
            if len(pool) < tournament_size:
                break
            competitors = random.sample(pool, min(tournament_size, len(pool)))  # nosec B311
            winner = max(competitors, key=lambda v: v["fitness"])
            winners.append(winner)
            pool.remove(winner)

        return [w["id"] for w in winners]

    def prune_losers(self, base_id: str, keep: int = 3) -> int:
        """Remove underperforming variants, keeping only the top ``keep``.

        Args:
            base_id: The base component node ID.
            keep: Number of top-performing variants to retain.

        Returns:
            Number of variants pruned.
        """
        variants = self.get_variants(base_id)
        if len(variants) <= keep:
            return 0

        to_prune = variants[keep:]  # Already sorted by fitness desc
        pruned = 0
        for v in to_prune:
            if self.ogm.delete(v["id"]):
                pruned += 1
                logger.info("Pruned variant %s (fitness=%.3f)", v["id"], v["fitness"])

        return pruned

    def promote_winner(self, variant_id: str, base_id: str) -> None:
        """Promote a variant to become the new baseline.

        Creates a ``SUPERSEDES`` edge from the winner to the old base,
        signaling that the variant should replace it in future routing.

        Args:
            variant_id: The winning variant's ID.
            base_id: The previous baseline's ID.
        """
        self.ogm.upsert_edge(
            variant_id,
            base_id,
            RegistryEdgeType.SUPERSEDES,
            {"promoted_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())},
        )
        logger.info("Promoted variant %s → supersedes base %s", variant_id, base_id)
