from __future__ import annotations

import logging
import time
import typing
import uuid

if typing.TYPE_CHECKING:
    from .._engine_protocol import _EngineProtocol

    _Base = _EngineProtocol
else:
    _Base = object

from ...models.domains.finance import (
    ExecutionSignalNode,
    KellySizingNode,
    OrderCommitRecordNode,
    TradingStrategyNode,
)

logger = logging.getLogger(__name__)


class FinanceEngineMixin(_Base):
    """Quantitative finance capabilities for the KG engine."""

    def register_trading_strategy(
        self, name: str, asset_class: str, timeframe: str
    ) -> str:
        """Register a new trading strategy into the KG."""
        strategy_id = f"start:{uuid.uuid4().hex[:8]}"
        ts = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

        node = TradingStrategyNode(
            id=strategy_id,
            name=name,
            asset_class=asset_class,
            timeframe=timeframe,
            timestamp=ts,
        )
        self.graph.add_node(node.id, **node.model_dump())

        if self.backend:
            data = self._serialize_node(node, label="TradingStrategy")
            self._upsert_node("TradingStrategy", strategy_id, data)
        return strategy_id

    def generate_execution_signal(
        self, strategy_id: str, direction: str, strength: float, target_price: float
    ) -> str:
        """Record an execution signal generated by a trading strategy."""
        signal_id = f"signal:{uuid.uuid4().hex[:8]}"
        ts = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

        node = ExecutionSignalNode(
            id=signal_id,
            name=f"Signal {direction} {strength}",
            direction=direction,
            strength=strength,
            target_price=target_price,
            timestamp=ts,
        )
        self.graph.add_node(node.id, **node.model_dump())

        if self.backend:
            data = self._serialize_node(node, label="ExecutionSignal")
            self._upsert_node("ExecutionSignal", signal_id, data)
            self.backend.execute(
                "MATCH (s:TradingStrategy {id: $sid}), (sig:ExecutionSignal {id: $sigid}) "
                "MERGE (s)-[:GENERATES_SIGNAL]->(sig)",
                {"sid": strategy_id, "sigid": signal_id},
            )
        return signal_id

    def calculate_kelly_size(
        self, signal_id: str, win_prob: float, win_loss_ratio: float
    ) -> str:
        """Calculate and attach Kelly sizing to an execution signal."""
        kelly_id = f"kelly:{uuid.uuid4().hex[:8]}"
        ts = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

        fraction = win_prob - (
            (1 - win_prob) / (win_loss_ratio if win_loss_ratio > 0 else 1)
        )
        fraction = max(0.0, min(1.0, fraction))  # cap 0-1

        node = KellySizingNode(
            id=kelly_id,
            name=f"Kelly {fraction:.2f}",
            win_probability=win_prob,
            win_loss_ratio=win_loss_ratio,
            suggested_fraction=fraction,
            timestamp=ts,
        )
        self.graph.add_node(node.id, **node.model_dump())

        if self.backend:
            data = self._serialize_node(node, label="KellySizing")
            self._upsert_node("KellySizing", kelly_id, data)
            self.backend.execute(
                "MATCH (sig:ExecutionSignal {id: $sigid}), (k:KellySizing {id: $kid}) "
                "MERGE (sig)-[:SIZED_BY]->(k)",
                {"sigid": signal_id, "kid": kelly_id},
            )
        return kelly_id

    def commit_order(self, signal_id: str, portfolio_id: str, fill_price: float) -> str:
        """Commit an executed order to the portfolio."""
        order_id = f"order_commit:{uuid.uuid4().hex[:8]}"
        ts = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

        node = OrderCommitRecordNode(
            id=order_id,
            name=f"Commit {fill_price}",
            order_id=order_id,
            status="filled",
            fill_price=fill_price,
            timestamp=ts,
        )
        self.graph.add_node(node.id, **node.model_dump())

        if self.backend:
            data = self._serialize_node(node, label="OrderCommitRecord")
            self._upsert_node("OrderCommitRecord", order_id, data)
            self.backend.execute(
                "MATCH (sig:ExecutionSignal {id: $sigid}), (o:OrderCommitRecord {id: $oid}) "
                "MERGE (sig)-[:PLACED_ORDER]->(o)",
                {"sigid": signal_id, "oid": order_id},
            )
            self.backend.execute(
                "MATCH (o:OrderCommitRecord {id: $oid}), (p {id: $pid}) "
                "MERGE (o)-[:BELONGS_TO_PORTFOLIO]->(p)",
                {"oid": order_id, "pid": portfolio_id},
            )
        return order_id
