from __future__ import annotations

"""CONCEPT:KG-2.6"""

import logging
import time
import typing
import uuid

if typing.TYPE_CHECKING:
    from .._engine_protocol import _EngineProtocol

    _Base = _EngineProtocol
else:
    _Base = object

from ...models.domains.finance import (
    ExecutionSignalNode,
    KellySizingNode,
    MarkovRegimeStateNode,
    MarkovTransitionMatrixNode,
    MicrostructureSignalNode,
    OrderCommitRecordNode,
    RegimeSignalNode,
    TradingStrategyNode,
)

logger = logging.getLogger(__name__)


class FinanceEngineMixin(_Base):
    """Quantitative finance capabilities for the KG engine."""

    def register_trading_strategy(
        self, name: str, asset_class: str, timeframe: str
    ) -> str:
        """Register a new trading strategy into the KG."""
        strategy_id = f"start:{uuid.uuid4().hex[:8]}"
        ts = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

        node = TradingStrategyNode(
            id=strategy_id,
            name=name,
            asset_class=asset_class,
            timeframe=timeframe,
            timestamp=ts,
        )
        self.graph.add_node(node.id, **node.model_dump())

        if self.backend:
            data = self._serialize_node(node, label="TradingStrategy")
            self._upsert_node("TradingStrategy", strategy_id, data)
        return strategy_id

    def record_backtest_outcome(
        self,
        signal_id: str,
        *,
        deflated_sharpe: float,
        pbo: float,
        hit_rate: float,
        n_trades: int = 0,
        name: str | None = None,
        prediction_horizon: str | None = None,
        provenance: str = "",
        asset_class: str = "equities",
    ) -> str:
        """Write measured backtest results back into a MicrostructureSignal's priors.

        CONCEPT:EE-033 — closes the loop: the backtester's measured
        ``deflated_sharpe`` / ``pbo`` / ``hit_rate`` become the stored
        ``standalone_sharpe`` / ``pbo`` / ``directional_accuracy`` priors. Creates
        the signal node when absent (MERGE semantics) and preserves existing
        descriptive fields (name, horizon, provenance) when updating. Because
        ``BayesianSignalFusion.seed_from_kg`` reads these priors live, the fusion
        weights self-adjust on the next cycle with no extra wiring.
        """
        ts = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

        # Preserve any existing descriptive fields when this is an update.
        existing: dict = {}
        try:
            if self.graph.has_node(signal_id):
                existing = dict(self.graph.nodes[signal_id])
        except Exception:  # noqa: BLE001 — best-effort read, fall back to create
            existing = {}

        node = MicrostructureSignalNode(
            id=signal_id,
            name=name or existing.get("name") or signal_id,
            prediction_horizon=(
                prediction_horizon or existing.get("prediction_horizon") or "1m"
            ),
            directional_accuracy=hit_rate,
            standalone_sharpe=deflated_sharpe,
            pbo=pbo,
            decay_regime=existing.get("decay_regime", "stationary"),
            half_life_days=existing.get("half_life_days", 0.0),
            provenance=provenance or existing.get("provenance", ""),
            asset_class=existing.get("asset_class", asset_class),
            last_validated=ts,
            timestamp=existing.get("timestamp", ts),
        )
        # Sample size travels with the priors: a Sharpe measured over 5 trades
        # must not carry the same weight as one measured over 5000.
        props = {**node.model_dump(), "n_trades": n_trades}
        self.graph.add_node(node.id, **props)

        if self.backend:
            data = self._serialize_node(node, label="MicrostructureSignal")
            data["n_trades"] = n_trades
            self._upsert_node("MicrostructureSignal", signal_id, data)
        return signal_id

    def generate_execution_signal(
        self, strategy_id: str, direction: str, strength: float, target_price: float
    ) -> str:
        """Record an execution signal generated by a trading strategy."""
        signal_id = f"signal:{uuid.uuid4().hex[:8]}"
        ts = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

        node = ExecutionSignalNode(
            id=signal_id,
            name=f"Signal {direction} {strength}",
            direction=direction,
            strength=strength,
            target_price=target_price,
            timestamp=ts,
        )
        self.graph.add_node(node.id, **node.model_dump())

        if self.backend:
            data = self._serialize_node(node, label="ExecutionSignal")
            self._upsert_node("ExecutionSignal", signal_id, data)
            self.backend.execute(
                "MATCH (s:TradingStrategy {id: $sid}), (sig:ExecutionSignal {id: $sigid}) "
                "MERGE (s)-[:GENERATES_SIGNAL]->(sig)",
                {"sid": strategy_id, "sigid": signal_id},
            )
        return signal_id

    def calculate_kelly_size(
        self, signal_id: str, win_prob: float, win_loss_ratio: float
    ) -> str:
        """Calculate and attach Kelly sizing to an execution signal."""
        kelly_id = f"kelly:{uuid.uuid4().hex[:8]}"
        ts = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

        fraction = win_prob - (
            (1 - win_prob) / (win_loss_ratio if win_loss_ratio > 0 else 1)
        )
        fraction = max(0.0, min(1.0, fraction))  # cap 0-1

        node = KellySizingNode(
            id=kelly_id,
            name=f"Kelly {fraction:.2f}",
            win_probability=win_prob,
            win_loss_ratio=win_loss_ratio,
            suggested_fraction=fraction,
            timestamp=ts,
        )
        self.graph.add_node(node.id, **node.model_dump())

        if self.backend:
            data = self._serialize_node(node, label="KellySizing")
            self._upsert_node("KellySizing", kelly_id, data)
            self.backend.execute(
                "MATCH (sig:ExecutionSignal {id: $sigid}), (k:KellySizing {id: $kid}) "
                "MERGE (sig)-[:SIZED_BY]->(k)",
                {"sigid": signal_id, "kid": kelly_id},
            )
        return kelly_id

    def commit_order(self, signal_id: str, portfolio_id: str, fill_price: float) -> str:
        """Commit an executed order to the portfolio."""
        order_id = f"order_commit:{uuid.uuid4().hex[:8]}"
        ts = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

        node = OrderCommitRecordNode(
            id=order_id,
            name=f"Commit {fill_price}",
            order_id=order_id,
            status="filled",
            fill_price=fill_price,
            timestamp=ts,
        )
        self.graph.add_node(node.id, **node.model_dump())

        if self.backend:
            data = self._serialize_node(node, label="OrderCommitRecord")
            self._upsert_node("OrderCommitRecord", order_id, data)
            self.backend.execute(
                "MATCH (sig:ExecutionSignal {id: $sigid}), (o:OrderCommitRecord {id: $oid}) "
                "MERGE (sig)-[:PLACED_ORDER]->(o)",
                {"sigid": signal_id, "oid": order_id},
            )
            self.backend.execute(
                "MATCH (o:OrderCommitRecord {id: $oid}), (p {id: $pid}) "
                "MERGE (o)-[:BELONGS_TO_PORTFOLIO]->(p)",
                {"oid": order_id, "pid": portfolio_id},
            )
        return order_id

    # --- Markov Regime Detection (CONCEPT:KG-2.6) ---

    def fit_markov_regime(
        self,
        returns: list[float],
        strategy_id: str,
        asset_class: str = "equities",
        *,
        bull_threshold: float | None = None,
        bear_threshold: float | None = None,
        window: int | None = None,
        method: str = "rolling_sum",
    ) -> str:
        """Fit a Markov regime model to returns and persist to the KG.

        Creates a ``MarkovTransitionMatrixNode`` and links it to the
        associated ``TradingStrategy``.

        Args:
            returns: List of period returns.
            strategy_id: ID of the TradingStrategy node to link to.
            asset_class: Asset class for default threshold selection.
            bull_threshold: Override bull threshold.
            bear_threshold: Override bear threshold.
            window: Override rolling window.
            method: 'rolling_sum' or 'compounding'.

        Returns:
            ID of the created MarkovTransitionMatrixNode.
        """

        import numpy as np

        from ..core.markov_regime import AssetClass, MarkovRegimeModel

        ac = (
            AssetClass(asset_class)
            if asset_class in AssetClass.__members__.values()
            else AssetClass.EQUITIES
        )
        model = MarkovRegimeModel(
            asset_class=ac,
            bull_threshold=bull_threshold,
            bear_threshold=bear_threshold,
            window=window,
            method=method,
        )
        model.fit(np.array(returns))

        matrix_id = f"markov_matrix:{uuid.uuid4().hex[:8]}"
        ts = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
        props = model.to_kg_properties()

        node = MarkovTransitionMatrixNode(
            id=matrix_id,
            name=f"Regime Matrix ({asset_class})",
            dimension=props["n_states"],
            matrix_json=props["transition_matrix"],
            sample_count=props["sample_count"],
            estimation_window=model.detector.window,
            asset_class=asset_class,
            timestamp=ts,
            metadata=props,
        )
        self.graph.add_node(node.id, **node.model_dump())

        if self.backend:
            data = self._serialize_node(node, label="MarkovTransitionMatrix")
            self._upsert_node("MarkovTransitionMatrix", matrix_id, data)
            self.backend.execute(
                """
                MATCH (m:RegistryNode {type: 'model', name: $model_name, id: $model_id})
                RETURN m
                """,
                {
                    "model_name": "MarkovRegimeModel",
                    "model_id": f"markov_regime_{asset_class}",
                },
            )
            self.backend.execute(
                "MATCH (s:TradingStrategy {id: $sid}), (m:MarkovTransitionMatrix {id: $mid}) "
                "MERGE (s)-[:MODELS_REGIME]->(m)",
                {"sid": strategy_id, "mid": matrix_id},
            )

        # Also persist the current regime state
        if model.regime_states is not None and len(model.regime_states) > 0:
            current_regime = str(model.regime_states[-1])
            regime_id = f"regime_state:{uuid.uuid4().hex[:8]}"
            signal_data = model.generate_signal(current_regime)

            regime_node = MarkovRegimeStateNode(
                id=regime_id,
                name=f"Regime: {current_regime}",
                regime_type=current_regime,
                confidence=abs(signal_data["signal"]),
                returns_window=model.detector.window,
                asset_class=asset_class,
                timestamp=ts,
            )
            self.graph.add_node(regime_node.id, **regime_node.model_dump())

            if self.backend:
                data = self._serialize_node(regime_node, label="MarkovRegimeState")
                self._upsert_node("MarkovRegimeState", regime_id, data)
                self.backend.execute(
                    "MATCH (m:MarkovTransitionMatrix {id: $mid}), (r:MarkovRegimeState {id: $rid}) "
                    "MERGE (m)-[:DETECTED_REGIME]->(r)",
                    {"mid": matrix_id, "rid": regime_id},
                )

        logger.info(
            "[CONCEPT:KG-2.6] Fitted Markov regime model for strategy %s: %s",
            strategy_id,
            matrix_id,
        )
        return matrix_id

    def forecast_regime(self, strategy_id: str, n_steps: int = 5) -> dict[str, float]:
        """Forecast regime probabilities n steps ahead.

        Loads the most recent ``MarkovTransitionMatrixNode`` linked to the
        strategy, reconstructs the model, and forecasts.

        Args:
            strategy_id: TradingStrategy node ID.
            n_steps: Number of forecast steps.

        Returns:
            Dict of {regime_state: probability}.
        """
        import json

        import numpy as np

        from ..core.markov_regime import MarkovRegimeModel

        # Find the latest regime matrix for this strategy
        matrix_data = None
        for _, data in self.graph.nodes(data=True):
            if data.get("type") == "markov_transition_matrix" and data.get(
                "asset_class"
            ):
                matrix_data = data
                break

        if self.backend:
            results = self.backend.execute(
                """
                MATCH (s:TradingStrategy {id: $sid})-[:MODELS_REGIME]->(m:MarkovTransitionMatrix)
                RETURN m ORDER BY m.timestamp DESC LIMIT 1
                """,
                {"sid": strategy_id},
            )
            if results:
                matrix_data = results[0].get("m", {})

        if not matrix_data:
            logger.warning("No Markov regime model found for strategy %s", strategy_id)
            return {}

        metadata = matrix_data.get("metadata", {})
        if isinstance(metadata, str):
            metadata = json.loads(metadata)

        ac = metadata.get("asset_class", "equities")
        model = MarkovRegimeModel(asset_class=ac)
        # Reconstruct the Markov model from the serialized transition matrix
        trans_json = metadata.get("transition_matrix", "{}")
        if isinstance(trans_json, str):
            trans_dict = json.loads(trans_json)
        else:
            trans_dict = trans_json

        if trans_dict:
            states = list(trans_dict.keys())
            n_s = len(states)
            matrix = np.zeros((n_s, n_s))
            for i, src in enumerate(states):
                for j, dst in enumerate(states):
                    matrix[i][j] = trans_dict.get(src, {}).get(dst, 0.0)

            model.markov.states = states
            model.markov._state_to_idx = {s: i for i, s in enumerate(states)}
            model.markov.transition_matrix = matrix
            model._fitted = True

        # Forecast from the current regime
        current = metadata.get("states", "[]")
        if isinstance(current, str):
            state_list = json.loads(current)
        else:
            state_list = current
        current_state = state_list[-1] if state_list else "sideways"

        return model.forecast(current_state, n_steps)

    def generate_regime_signal(self, strategy_id: str) -> str:
        """Generate and persist a regime-based trading signal.

        Args:
            strategy_id: TradingStrategy node ID.

        Returns:
            ID of the created RegimeSignalNode.
        """
        forecast = self.forecast_regime(strategy_id, n_steps=1)
        if not forecast:
            return ""

        signal_id = f"regime_sig:{uuid.uuid4().hex[:8]}"
        ts = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

        bull_p = forecast.get("bull", 0.0)
        bear_p = forecast.get("bear", 0.0)
        sideways_p = forecast.get("sideways", 0.0)
        signal_val = bull_p - bear_p

        node = RegimeSignalNode(
            id=signal_id,
            name=f"Regime Signal {signal_val:+.3f}",
            signal_value=signal_val,
            bull_prob=bull_p,
            bear_prob=bear_p,
            sideways_prob=sideways_p,
            timestamp=ts,
        )
        self.graph.add_node(node.id, **node.model_dump())

        if self.backend:
            data = self._serialize_node(node, label="RegimeSignal")
            self._upsert_node("RegimeSignal", signal_id, data)
            self.backend.execute(
                "MATCH (s:TradingStrategy {id: $sid}), (sig:RegimeSignal {id: $sigid}) "
                "MERGE (s)-[:GENERATES_SIGNAL]->(sig)",
                {"sid": strategy_id, "sigid": signal_id},
            )

        return signal_id

    def get_regime_history(self, strategy_id: str) -> list[dict]:
        """Query the KG for historical regime states linked to a strategy.

        Args:
            strategy_id: TradingStrategy node ID.

        Returns:
            List of regime state dicts ordered by timestamp.
        """
        if self.backend:
            results = self.backend.execute(
                "MATCH (s:TradingStrategy {id: $sid})-[:MODELS_REGIME]->"
                "(m:MarkovTransitionMatrix)-[:DETECTED_REGIME]->(r:MarkovRegimeState) "
                "RETURN r ORDER BY r.timestamp ASC",
                {"sid": strategy_id},
            )
            return [r.get("r", {}) for r in results] if results else []

        # Fallback to in-memory graph
        regime_nodes = []
        for _, data in self.graph.nodes(data=True):
            if data.get("type") == "markov_regime_state":
                regime_nodes.append(data)
        return sorted(regime_nodes, key=lambda x: x.get("timestamp", ""))
