#!/usr/bin/python
from __future__ import annotations

"""Codebase Map Generator — Auto-Generated Navigational Markdown.

CONCEPT:ECO-4.23 — Codebase Map Generator

Generates a lightweight markdown file at the repo root listing each
top-level folder with a one-line description extracted from module
docstrings.  Keeps the map fresh via stop hooks.
"""

import ast
import logging
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from ..knowledge_graph.core.engine import IntelligenceGraphEngine

logger = logging.getLogger(__name__)

__all__ = ["CodebaseMapGenerator", "generate_codebase_map"]

# Directories always excluded from the map
_EXCLUDED_DIRS = {
    "__pycache__", ".git", ".tox", ".mypy_cache", ".pytest_cache",
    ".ruff_cache", "node_modules", ".venv", "venv", ".eggs", "dist",
    "build", "*.egg-info", ".agents",
}


class CodebaseMapGenerator:
    """Generate navigational codebase maps from directory structure.

    CONCEPT:ECO-4.23 — Codebase Map Generator

    Usage::

        gen = CodebaseMapGenerator("/path/to/project")
        md = gen.generate(depth=2)
        gen.write("CODEBASE.md")
    """

    def __init__(
        self,
        root: str | Path,
        engine: IntelligenceGraphEngine | None = None,
    ) -> None:
        self.root = Path(root).resolve()
        self.engine = engine

    def generate(self, depth: int = 2) -> str:
        """Generate codebase map as markdown string."""
        project_name = self.root.name
        lines = [
            f"# Codebase Map — {project_name}",
            "",
            "> Auto-generated by Codebase Map Generator (CONCEPT:ECO-4.23).",
            "> Do not edit manually — regenerate with `generate_codebase_map()`.",
            "",
        ]

        # Add project-level docstring if available
        project_doc = self._get_project_docstring()
        if project_doc:
            lines.extend([project_doc, ""])

        # Walk directory tree
        lines.append("## Directory Structure\n")
        lines.extend(self._walk_tree(self.root, depth=depth, current_depth=0))

        return "\n".join(lines)

    def write(self, filename: str = "CODEBASE.md") -> Path:
        """Generate and write the codebase map to disk."""
        content = self.generate()
        path = self.root / filename
        path.write_text(content, encoding="utf-8")
        logger.info("[ECO-4.7] Codebase map written to %s", path)
        return path

    def persist_to_kg(self) -> None:
        """Store codebase map as a KG node."""
        if not self.engine:
            return
        content = self.generate()
        try:
            self.engine.add_node(
                f"codebase_map_{self.root.name}",
                "codebase_map",
                {
                    "name": f"Codebase Map: {self.root.name}",
                    "content": content[:10000],
                    "directory_count": content.count("📁"),
                    "importance_score": 0.8,
                },
            )
        except Exception as e:
            logger.debug("[ECO-4.7] KG persist failed: %s", e)

    # -- Internal --

    def _walk_tree(
        self, path: Path, depth: int, current_depth: int, prefix: str = "",
    ) -> list[str]:
        """Recursively walk directory tree and build map entries."""
        if current_depth >= depth:
            return []

        lines: list[str] = []
        try:
            entries = sorted(
                path.iterdir(),
                key=lambda e: (not e.is_dir(), e.name.lower()),
            )
        except PermissionError:
            return []

        dirs = [e for e in entries if e.is_dir() and e.name not in _EXCLUDED_DIRS
                and not e.name.startswith(".")]
        files = [e for e in entries if e.is_file() and not e.name.startswith(".")]

        for d in dirs:
            desc = self._get_dir_description(d)
            indent = "  " * current_depth
            lines.append(f"{indent}- 📁 **{d.name}/** — {desc}")

            # Recurse into subdirectories
            sub_lines = self._walk_tree(d, depth, current_depth + 1, prefix + "  ")
            lines.extend(sub_lines)

        # Only show key files at depth 0
        if current_depth == 0:
            key_files = [f for f in files if f.name in (
                "pyproject.toml", "setup.py", "Makefile", "Dockerfile",
                "docker-compose.yml", "AGENTS.md", "README.md", "CODEBASE.md",
            )]
            for f in key_files:
                lines.append(f"- 📄 **{f.name}**")

        return lines

    def _get_dir_description(self, dir_path: Path) -> str:
        """Extract a one-line description from the directory's __init__.py."""
        init_file = dir_path / "__init__.py"
        if init_file.is_file():
            doc = self._extract_docstring(init_file)
            if doc:
                first_line = doc.strip().split("\n")[0]
                return first_line[:120]

        # Try README.md
        readme = dir_path / "README.md"
        if readme.is_file():
            try:
                lines = readme.read_text(encoding="utf-8").strip().split("\n")
                for line in lines:
                    stripped = line.strip().lstrip("# ").strip()
                    if stripped and not stripped.startswith("#"):
                        return stripped[:120]
            except Exception:
                pass

        # Fallback: count contents
        try:
            children = list(dir_path.iterdir())
            py_count = sum(1 for c in children if c.suffix == ".py")
            dir_count = sum(1 for c in children if c.is_dir() and c.name != "__pycache__")
            return f"{py_count} Python files, {dir_count} subdirectories"
        except Exception:
            return "..."

    def _extract_docstring(self, py_file: Path) -> str:
        """Extract the module-level docstring from a Python file."""
        try:
            source = py_file.read_text(encoding="utf-8")
            tree = ast.parse(source)
            return ast.get_docstring(tree) or ""
        except Exception:
            return ""

    def _get_project_docstring(self) -> str:
        """Get project-level description from pyproject.toml or __init__.py."""
        # Try pyproject.toml
        pyproject = self.root / "pyproject.toml"
        if pyproject.is_file():
            try:
                import tomllib
            except ImportError:
                try:
                    import tomli as tomllib  # type: ignore[no-redef]
                except ImportError:
                    tomllib = None  # type: ignore[assignment]
            if tomllib:
                try:
                    data = tomllib.loads(pyproject.read_text(encoding="utf-8"))
                    desc = data.get("project", {}).get("description", "")
                    if desc:
                        return f"*{desc}*"
                except Exception:
                    pass

        # Try main package __init__.py
        for child in sorted(self.root.iterdir()):
            if child.is_dir() and (child / "__init__.py").exists():
                doc = self._extract_docstring(child / "__init__.py")
                if doc:
                    return doc.split("\n")[0]

        return ""


def generate_codebase_map(
    root: str | Path,
    depth: int = 2,
    output: str = "CODEBASE.md",
    engine: Any = None,
) -> str:
    """Convenience: generate and write a codebase map in one call."""
    gen = CodebaseMapGenerator(root, engine=engine)
    gen.write(output)
    if engine:
        gen.persist_to_kg()
    return gen.generate(depth=depth)
