"""Characterization tests for `DynamicVisibilityTransform._filter_components`
(agent_utilities/mcp/server_factory.py), CCN 126 -- lane CX-AU-05.

These pin OBSERVED behaviour of the function as it exists today, including any
surprising fallthroughs, so a later behaviour-preserving refactor can be
verified against them. They are written against the REAL closure-captured
method (reached via `create_mcp_server(...).mcp.transforms[0]`), not a
reimplementation, so a bug in the refactor shows up here.

Do NOT edit this file in the refactor commit -- see CX-AU-05 dispatch brief,
"two-commit discipline".
"""

from __future__ import annotations

from types import SimpleNamespace

import pytest

from agent_utilities.mcp.server_factory import create_mcp_server


class _Component:
    """Minimal stand-in for a FastMCP Tool/Resource/Prompt as `_filter_components` sees it."""

    def __init__(self, name=None, uri=None, tags=None):
        self.name = name
        self.uri = uri
        self.tags = tags

    def __repr__(self):
        return f"_Component(name={self.name!r}, uri={self.uri!r}, tags={self.tags!r})"


def _build_transform(command_args=None):
    """Build a real server and return its live DynamicVisibilityTransform."""
    _args, mcp, _mw = create_mcp_server(
        name="cx-au-05-test-server", command_args=command_args or []
    )
    transforms = [
        t for t in mcp.transforms if type(t).__name__ == "DynamicVisibilityTransform"
    ]
    assert len(transforms) == 1, "expected exactly one DynamicVisibilityTransform"
    return transforms[0]


def _names(components):
    return sorted(c.name for c in components)


@pytest.fixture
def clean_env(monkeypatch):
    """No env-based filters, no request context, no CLI overrides."""
    for key in (
        "MCP_ENABLED_TAGS",
        "MCP_DISABLED_TAGS",
        "MCP_ENABLED_TOOLS",
        "MCP_DISABLED_TOOLS",
    ):
        monkeypatch.delenv(key, raising=False)
    monkeypatch.setattr(
        "agent_utilities.mcp.server_factory._optional_http_request", lambda: None
    )
    return monkeypatch


# ---------------------------------------------------------------------------
# 1. No filters configured at all -> everything passes through unchanged.
# ---------------------------------------------------------------------------
def test_no_filters_returns_all_components(clean_env):
    transform = _build_transform()
    comps = [_Component(name="a"), _Component(name="b"), _Component(name="c")]
    out = transform._filter_components(comps)
    assert _names(out) == ["a", "b", "c"]


# ---------------------------------------------------------------------------
# 2. Env-based enabled tools whitelist.
# ---------------------------------------------------------------------------
def test_env_enabled_tools_whitelist(clean_env):
    clean_env.setenv("MCP_ENABLED_TOOLS", "a, c")
    transform = _build_transform()
    comps = [_Component(name="a"), _Component(name="b"), _Component(name="c")]
    out = transform._filter_components(comps)
    assert _names(out) == ["a", "c"]


# ---------------------------------------------------------------------------
# 3. Env-based disabled tools blacklist.
# ---------------------------------------------------------------------------
def test_env_disabled_tools_blacklist(clean_env):
    clean_env.setenv("MCP_DISABLED_TOOLS", "b")
    transform = _build_transform()
    comps = [_Component(name="a"), _Component(name="b"), _Component(name="c")]
    out = transform._filter_components(comps)
    assert _names(out) == ["a", "c"]


# ---------------------------------------------------------------------------
# 4. "all" in the enabled list resets to "expose everything".
# ---------------------------------------------------------------------------
def test_env_enabled_tools_all_keyword_exposes_everything(clean_env):
    clean_env.setenv("MCP_ENABLED_TOOLS", "all")
    transform = _build_transform()
    comps = [_Component(name="a"), _Component(name="b")]
    out = transform._filter_components(comps)
    assert _names(out) == ["a", "b"]


# ---------------------------------------------------------------------------
# 5. Env-based tag filters: enabled tag must intersect; components without
#    tags are then excluded once an enabled-tag filter is active.
# ---------------------------------------------------------------------------
def test_env_enabled_tags_require_intersection(clean_env):
    clean_env.setenv("MCP_ENABLED_TAGS", "kg")
    transform = _build_transform()
    comps = [
        _Component(name="a", tags={"kg"}),
        _Component(name="b", tags={"other"}),
        _Component(name="c", tags=None),
    ]
    out = transform._filter_components(comps)
    # "c" has no tags at all -> excluded once an enabled-tag filter is set.
    assert _names(out) == ["a"]


def test_env_disabled_tags_exclude_on_intersection(clean_env):
    clean_env.setenv("MCP_DISABLED_TAGS", "danger")
    transform = _build_transform()
    comps = [
        _Component(name="a", tags={"danger"}),
        _Component(name="b", tags={"safe"}),
        _Component(name="c", tags=None),
    ]
    out = transform._filter_components(comps)
    # disabled-tags-only: components with no tags are NOT excluded (only the
    # enabled-tags branch penalizes an untagged component).
    assert _names(out) == ["b", "c"]


# ---------------------------------------------------------------------------
# 6. A component with neither `name` nor `uri` is EXCLUDED (BUG-CX-022, fixed
#    by lane WD2-BUG-SEC). This pin previously recorded the OPPOSITE -- that
#    such a component bypassed BOTH name and tag filtering -- which was the
#    security defect itself, not behaviour worth preserving. See
#    tests/unit/mcp/test_server_factory_fail_closed.py for the full fail-closed
#    regression set.
# ---------------------------------------------------------------------------
def test_unnamed_component_is_excluded_by_filtering(clean_env):
    clean_env.setenv("MCP_ENABLED_TOOLS", "only-this-one")
    clean_env.setenv("MCP_ENABLED_TAGS", "some-tag")
    transform = _build_transform()
    anon = _Component(name=None, uri=None, tags={"unrelated"})
    named = _Component(name="only-this-one", tags={"some-tag"})
    excluded = _Component(name="excluded", tags={"some-tag"})
    out = transform._filter_components([anon, named, excluded])
    assert anon not in out
    assert named in out
    assert excluded not in out


# ---------------------------------------------------------------------------
# 7. CLI args override env-based enabled/disabled tool lists outright
#    (not merged -- replaced).
# ---------------------------------------------------------------------------
def test_cli_tools_overrides_env_enabled_tools(clean_env):
    clean_env.setenv("MCP_ENABLED_TOOLS", "a,b")
    transform = _build_transform(command_args=["--tools", "c"])
    comps = [_Component(name="a"), _Component(name="b"), _Component(name="c")]
    out = transform._filter_components(comps)
    assert _names(out) == ["c"]


def test_cli_disabled_tools_overrides_env_disabled_tools(clean_env):
    clean_env.setenv("MCP_DISABLED_TOOLS", "a")
    transform = _build_transform(command_args=["--disabled-tools", "b"])
    comps = [_Component(name="a"), _Component(name="b"), _Component(name="c")]
    out = transform._filter_components(comps)
    # CLI --disabled-tools REPLACES the env-derived disabled list, so "a"
    # (only ever disabled via env) is no longer excluded.
    assert _names(out) == ["a", "c"]


# ---------------------------------------------------------------------------
# 8. Query-parameter based filtering (HTTP/SSE transport only).
# ---------------------------------------------------------------------------
class _FakeQueryParams:
    def __init__(self, data):
        self._data = data

    def getlist(self, key):
        val = self._data.get(key)
        if val is None:
            return []
        return val if isinstance(val, list) else [val]

    def get(self, key):
        val = self._data.get(key)
        if isinstance(val, list):
            return val[0] if val else None
        return val


class _FakeHeaders:
    def __init__(self, data):
        self._data = data or {}

    def getlist(self, key):
        val = self._data.get(key)
        if val is None:
            return []
        return val if isinstance(val, list) else [val]

    def get(self, key):
        val = self._data.get(key)
        if isinstance(val, list):
            return val[0] if val else None
        return val


def _fake_request(query=None, headers=None):
    return SimpleNamespace(
        query_params=_FakeQueryParams(query or {}), headers=_FakeHeaders(headers or {})
    )


def test_query_param_tools_narrows_enabled_list(clean_env):
    clean_env.setenv("MCP_ENABLED_TOOLS", "a,b,c")
    transform = _build_transform()
    req = _fake_request(query={"tools": "b,c"})
    clean_env.setattr(
        "agent_utilities.mcp.server_factory._optional_http_request", lambda: req
    )
    comps = [_Component(name="a"), _Component(name="b"), _Component(name="c")]
    out = transform._filter_components(comps)
    assert _names(out) == ["b", "c"]


def test_query_param_disabled_tools_unions_with_disabled_list(clean_env):
    clean_env.setenv("MCP_DISABLED_TOOLS", "a")
    transform = _build_transform()
    req = _fake_request(query={"disabled_tools": "b"})
    clean_env.setattr(
        "agent_utilities.mcp.server_factory._optional_http_request", lambda: req
    )
    comps = [_Component(name="a"), _Component(name="b"), _Component(name="c")]
    out = transform._filter_components(comps)
    assert _names(out) == ["c"]


def test_headers_narrow_further_on_top_of_query_params(clean_env):
    transform = _build_transform()
    req = _fake_request(query={"tools": "a,b,c"}, headers={"x-mcp-enabled-tools": "b"})
    clean_env.setattr(
        "agent_utilities.mcp.server_factory._optional_http_request", lambda: req
    )
    comps = [_Component(name="a"), _Component(name="b"), _Component(name="c")]
    out = transform._filter_components(comps)
    # Header-derived enabled list narrows the query-derived one further.
    assert _names(out) == ["b"]


# ---------------------------------------------------------------------------
# 9. A malformed request (raises while being read) rejects everything --
#    fail-closed, never fail-open.
# ---------------------------------------------------------------------------
def test_malformed_request_rejects_all(clean_env):
    transform = _build_transform()

    def _boom():
        raise ValueError("malformed client filter")

    clean_env.setattr(
        "agent_utilities.mcp.server_factory._optional_http_request", _boom
    )
    comps = [_Component(name="a"), _Component(name="b")]
    out = transform._filter_components(comps)
    assert out == []


# ---------------------------------------------------------------------------
# 10. Semantic (`q=`) filter: no active KG engine -> reject all.
# ---------------------------------------------------------------------------
def test_semantic_query_with_no_active_engine_rejects_all(clean_env, monkeypatch):
    transform = _build_transform()
    req = _fake_request(query={"q": "dns tools"})
    monkeypatch.setattr(
        "agent_utilities.mcp.server_factory._optional_http_request", lambda: req
    )

    class _NoEngine:
        @staticmethod
        def get_active():
            return None

    monkeypatch.setattr(
        "agent_utilities.knowledge_graph.core.engine.IntelligenceGraphEngine",
        _NoEngine,
    )
    comps = [_Component(name="a"), _Component(name="b")]
    out = transform._filter_components(comps)
    assert out == []


# ---------------------------------------------------------------------------
# 11. Semantic (`q=`) filter: active engine resolves matches -> intersect
#     with the (env/cli-derived) enabled list when one is already present.
# ---------------------------------------------------------------------------
def test_semantic_query_intersects_with_existing_enabled_list(clean_env, monkeypatch):
    clean_env.setenv("MCP_ENABLED_TOOLS", "a,b,c")
    transform = _build_transform()
    req = _fake_request(query={"q": "dns tools"})
    monkeypatch.setattr(
        "agent_utilities.mcp.server_factory._optional_http_request", lambda: req
    )

    class _Engine:
        pass

    class _Orchestrator:
        def __init__(self, engine):
            pass

        def resolve_mcp_tools(self, query, server_name=None):
            return ["b", "c", "zzz-not-in-enabled"]

    monkeypatch.setattr(
        "agent_utilities.knowledge_graph.core.engine.IntelligenceGraphEngine",
        SimpleNamespace(get_active=staticmethod(lambda: _Engine())),
    )
    monkeypatch.setattr(
        "agent_utilities.tools.dynamic_tool_orchestrator.DynamicToolOrchestrator",
        _Orchestrator,
    )
    comps = [_Component(name="a"), _Component(name="b"), _Component(name="c")]
    out = transform._filter_components(comps)
    assert _names(out) == ["b", "c"]


if __name__ == "__main__":
    raise SystemExit(pytest.main([__file__, "-v"]))
