"""Characterization tests for the remaining CCN>10 functions in
agent_utilities/mcp/server_factory.py -- lane CX-AU-05:

- `_validate_network_exposure` (CCN 24)
- `mcp_network_run_kwargs` (CCN 23)
- `_hardened_jwt_verifier`'s nested `_Verifier.verify_token` (CCN 16)
- `_configure_middleware` (CCN 12) and `create_mcp_server` (CCN 22) and
  `create_mcp_parser` (CCN 13) already have substantial pre-existing
  coverage in tests/unit/mcp/test_mcp_utilities.py and
  tests/unit/mcp/test_rate_limit_client_id.py (create_mcp_server basic/
  invalid-port/delegation-error/eunomia-embedded/eunomia-remote/metrics-
  health-route paths, create_mcp_parser basic construction) -- that IS the
  reverse-dependency probe for those three and is not duplicated here.

Do NOT edit this file in the refactor commit.
"""

from __future__ import annotations

import asyncio
import time
from types import SimpleNamespace
from unittest.mock import AsyncMock

import pytest

from agent_utilities.mcp.server_factory import (
    _hardened_jwt_verifier,
    _validate_network_exposure,
    create_mcp_parser,
    mcp_network_run_kwargs,
)


def _run(coro):
    return asyncio.run(coro)


def _net_args(**overrides):
    parser = create_mcp_parser()
    args, _ = parser.parse_known_args([])
    args.transport = "streamable-http"
    args.host = "0.0.0.0"
    for key, value in overrides.items():
        setattr(args, key, value)
    return args


# ---------------------------------------------------------------------------
# _validate_network_exposure
# ---------------------------------------------------------------------------
def test_stdio_transport_is_a_noop():
    args = _net_args(transport="stdio")
    _validate_network_exposure(args)  # must not raise


def test_loopback_bind_is_a_noop():
    args = _net_args(host="127.0.0.1", auth_type="none")
    _validate_network_exposure(args)  # must not raise


def test_unauthenticated_network_listener_rejected():
    args = _net_args(auth_type="none")
    with pytest.raises(SystemExit):
        _validate_network_exposure(args)


def test_mismatched_cert_and_key_rejected(tmp_path):
    cert = tmp_path / "c.pem"
    cert.write_text("x")
    args = _net_args(auth_type="jwt", tls_certfile=str(cert), tls_keyfile="")
    with pytest.raises(SystemExit):
        _validate_network_exposure(args)


def test_missing_tls_files_on_disk_rejected(tmp_path):
    args = _net_args(
        auth_type="jwt",
        tls_certfile=str(tmp_path / "nope-cert.pem"),
        tls_keyfile=str(tmp_path / "nope-key.pem"),
    )
    with pytest.raises(SystemExit):
        _validate_network_exposure(args)


def test_terminated_without_trusted_proxy_cidrs_rejected():
    args = _net_args(
        auth_type="jwt",
        tls_certfile="",
        tls_keyfile="",
        tls_terminated=True,
        trusted_proxy_cidrs="",
    )
    with pytest.raises(SystemExit):
        _validate_network_exposure(args)


def test_no_tls_and_not_terminated_rejected():
    args = _net_args(
        auth_type="jwt",
        tls_certfile="",
        tls_keyfile="",
        tls_terminated=False,
    )
    with pytest.raises(SystemExit):
        _validate_network_exposure(args)


def test_no_allowed_hosts_rejected():
    args = _net_args(
        auth_type="jwt",
        tls_certfile="",
        tls_keyfile="",
        tls_terminated=True,
        trusted_proxy_cidrs="10.0.0.0/8",
        allowed_hosts="",
    )
    with pytest.raises(SystemExit):
        _validate_network_exposure(args)


def test_wildcard_allowed_host_rejected():
    args = _net_args(
        auth_type="jwt",
        tls_certfile="",
        tls_keyfile="",
        tls_terminated=True,
        trusted_proxy_cidrs="10.0.0.0/8",
        allowed_hosts="*.example.com",
    )
    with pytest.raises(SystemExit):
        _validate_network_exposure(args)


def test_fully_valid_network_config_passes():
    args = _net_args(
        auth_type="jwt",
        tls_certfile="",
        tls_keyfile="",
        tls_terminated=True,
        trusted_proxy_cidrs="10.0.0.0/8",
        allowed_hosts="svc.example.com",
    )
    _validate_network_exposure(args)  # must not raise


# ---------------------------------------------------------------------------
# mcp_network_run_kwargs
# ---------------------------------------------------------------------------
def test_stdio_transport_returns_empty_dict():
    args = _net_args(transport="stdio")
    assert mcp_network_run_kwargs(args) == {}


def test_non_loopback_without_allowed_hosts_raises():
    args = _net_args(allowed_hosts="")
    with pytest.raises(RuntimeError):
        mcp_network_run_kwargs(args)


def test_loopback_without_allowed_hosts_synthesizes_defaults():
    args = _net_args(host="127.0.0.1", allowed_hosts="", port=9123)
    result = mcp_network_run_kwargs(args)
    assert "middleware" in result and "uvicorn_config" in result


def test_valid_network_config_builds_middleware_and_uvicorn_config():
    args = _net_args(allowed_hosts="svc.example.com", allowed_origins="")
    result = mcp_network_run_kwargs(args)
    assert len(result["middleware"]) == 3
    assert result["uvicorn_config"]["proxy_headers"] is False
    assert "ssl_certfile" not in result["uvicorn_config"]


def test_tls_terminated_prepends_trusted_proxy_middleware():
    args = _net_args(
        allowed_hosts="svc.example.com",
        tls_terminated=True,
        trusted_proxy_cidrs="10.0.0.0/8",
    )
    result = mcp_network_run_kwargs(args)
    assert len(result["middleware"]) == 4


def test_tls_files_set_ssl_config():
    args = _net_args(
        allowed_hosts="svc.example.com",
        tls_certfile="c.pem",
        tls_keyfile="k.pem",
    )
    result = mcp_network_run_kwargs(args)
    assert result["uvicorn_config"]["ssl_certfile"] == "c.pem"
    assert result["uvicorn_config"]["ssl_keyfile"] == "k.pem"


def test_invalid_connection_bounds_raises(monkeypatch):
    monkeypatch.setenv("MCP_MAX_CONNECTIONS", "0")
    args = _net_args(allowed_hosts="svc.example.com")
    with pytest.raises(RuntimeError):
        mcp_network_run_kwargs(args)


# ---------------------------------------------------------------------------
# _hardened_jwt_verifier's nested _Verifier.verify_token
# ---------------------------------------------------------------------------
_RSA_PUBLIC_KEY_PEM = (
    "-----BEGIN PUBLIC KEY-----\n"
    "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0Z1oCjDS5Kk1x+2GJmU2\n"
    "MOCK-NOT-A-REAL-KEY-JUST-FOR-CONSTRUCTOR-VALIDATION-AAAAAAAAAAAAA\n"
    "-----END PUBLIC KEY-----\n"
)


def _build_verifier(**kwargs):
    return _hardened_jwt_verifier(
        public_key=kwargs.pop("public_key", "shared-secret-not-checked-by-shim"),
        issuer="https://idp.test",
        audience="aud",
        algorithm=kwargs.pop("algorithm", "HS256"),
        **kwargs,
    )


def _fake_super_result(claims):
    return SimpleNamespace(claims=claims)


def test_malformed_token_string_rejected_without_calling_super(monkeypatch):
    verifier = _build_verifier()
    mock_super = AsyncMock(side_effect=AssertionError("must not be called"))
    monkeypatch.setattr(
        "fastmcp.server.auth.providers.jwt.JWTVerifier.verify_token", mock_super
    )
    assert _run(verifier.verify_token("")) is None
    assert _run(verifier.verify_token(123)) is None
    assert _run(verifier.verify_token("x" * 20_000)) is None


def test_super_returning_none_is_passed_through(monkeypatch):
    verifier = _build_verifier()
    monkeypatch.setattr(
        "fastmcp.server.auth.providers.jwt.JWTVerifier.verify_token",
        AsyncMock(return_value=None),
    )
    assert _run(verifier.verify_token("tok")) is None


def test_non_dict_claims_rejected(monkeypatch):
    verifier = _build_verifier()
    monkeypatch.setattr(
        "fastmcp.server.auth.providers.jwt.JWTVerifier.verify_token",
        AsyncMock(return_value=SimpleNamespace(claims=None)),
    )
    assert _run(verifier.verify_token("tok")) is None


def test_expired_exp_claim_rejected(monkeypatch):
    verifier = _build_verifier()
    now = time.time()
    monkeypatch.setattr(
        "fastmcp.server.auth.providers.jwt.JWTVerifier.verify_token",
        AsyncMock(return_value=_fake_super_result({"exp": now - 100})),
    )
    assert _run(verifier.verify_token("tok")) is None


def test_valid_exp_claim_with_no_nbf_iat_accepted(monkeypatch):
    verifier = _build_verifier()
    now = time.time()
    result_obj = _fake_super_result({"exp": now + 3600})
    monkeypatch.setattr(
        "fastmcp.server.auth.providers.jwt.JWTVerifier.verify_token",
        AsyncMock(return_value=result_obj),
    )
    assert _run(verifier.verify_token("tok")) is result_obj


def test_nbf_too_far_in_future_rejected(monkeypatch):
    verifier = _build_verifier()
    now = time.time()
    monkeypatch.setattr(
        "fastmcp.server.auth.providers.jwt.JWTVerifier.verify_token",
        AsyncMock(
            return_value=_fake_super_result({"exp": now + 3600, "nbf": now + 300})
        ),
    )
    assert _run(verifier.verify_token("tok")) is None


def test_nbf_within_skew_tolerance_accepted(monkeypatch):
    verifier = _build_verifier()
    now = time.time()
    result_obj = _fake_super_result({"exp": now + 3600, "nbf": now + 10})
    monkeypatch.setattr(
        "fastmcp.server.auth.providers.jwt.JWTVerifier.verify_token",
        AsyncMock(return_value=result_obj),
    )
    assert _run(verifier.verify_token("tok")) is result_obj


def test_non_numeric_exp_claim_rejected(monkeypatch):
    verifier = _build_verifier()
    monkeypatch.setattr(
        "fastmcp.server.auth.providers.jwt.JWTVerifier.verify_token",
        AsyncMock(return_value=_fake_super_result({"exp": "not-a-number"})),
    )
    assert _run(verifier.verify_token("tok")) is None


if __name__ == "__main__":
    raise SystemExit(pytest.main([__file__, "-v"]))
