"""Supplementary characterization for agent_utilities/mcp/check_env_var_drift.py --
lane CX-AU-05: analyze (CCN 45), _env_names_from_tree (CCN 39),
_scan_dynamic_families (CCN 24), _scan_dynamic_family_reads (CCN 22),
_mcp_config_env_blocks (CCN 13), _compose_subst_reads (CCN 13),
_compose_env_keys (CCN 12), _module_level_string_tuples (CCN 11).

The pre-existing tests/mcp/test_check_env_var_drift.py (26 tests) already
exercises `analyze()` end to end across nearly every finding type (DEAD,
UNDOCUMENTED, MISSING_TOOL_MODE, MALFORMED_VALUE, AGENT_VAR_IN_MCP,
STALE_EXAMPLE, dynamic families, compose image/command/entrypoint
substitutions, compose environment: blocks, and known-bad-widening
regression checks) -- that IS the primary reverse-dependency probe for
this refactor. This file adds direct, function-level pins for the AST
helpers that suite only exercises indirectly, plus a couple of
integration-level pins for behaviour that suite's fixtures don't happen to
hit (a same-module env-name alias, an env block de-dup, and a compose
``environment:`` block terminated by dedent).

Do NOT edit this file in the refactor commit.
"""

from __future__ import annotations

import ast
import json
from pathlib import Path

import pytest

from agent_utilities.mcp import check_env_var_drift as drift


def _tree(src: str) -> ast.AST:
    return ast.parse(src)


# ---------------------------------------------------------------------------
# _env_names_from_tree
# ---------------------------------------------------------------------------
def test_direct_setting_call_found():
    found = drift._env_names_from_tree(_tree('setting("FOO_BAR", "")'))
    assert found == {"FOO_BAR"}


def test_os_getenv_found():
    found = drift._env_names_from_tree(_tree('import os\nos.getenv("BAZ_QUX")'))
    assert found == {"BAZ_QUX"}


def test_environ_get_and_subscript_found():
    found = drift._env_names_from_tree(
        _tree('import os\nos.environ.get("A_VAR")\nos.environ["B_VAR"]')
    )
    assert found == {"A_VAR", "B_VAR"}


def test_environ_write_not_counted_as_read():
    found = drift._env_names_from_tree(_tree('import os\nos.environ["WRITTEN"] = "x"'))
    assert found == set()


def test_same_module_alias_indirection_resolved():
    """`_LOG_LEVEL = "X_LOG_LEVEL"` then `os.getenv(_LOG_LEVEL)` -- the read is
    counted even though the literal never appears next to the reader call."""
    src = '_LOG_LEVEL = "X_LOG_LEVEL"\nimport os\nos.getenv(_LOG_LEVEL)\n'
    assert drift._env_names_from_tree(_tree(src)) == {"X_LOG_LEVEL"}


def test_unaliased_name_arg_not_counted():
    src = "value = compute()\nos.getenv(value)\n"
    assert drift._env_names_from_tree(_tree(src)) == set()


def test_field_alias_found():
    src = 'from pydantic import Field\nx: str = Field(alias="PYD_VAR")\n'
    assert drift._env_names_from_tree(_tree(src)) == {"PYD_VAR"}


def test_enable_flag_assignment_found():
    src = 'self.enable_flag = "FEATURE_ENABLED"\n'
    assert drift._env_names_from_tree(_tree(src)) == {"FEATURE_ENABLED"}


def test_string_literal_lookalike_ignored():
    src = "doc = \"setting('NOT_A_READ')\"\n"
    assert drift._env_names_from_tree(_tree(src)) == set()


# ---------------------------------------------------------------------------
# _module_level_string_tuples
# ---------------------------------------------------------------------------
def test_module_level_string_tuple_captured():
    tree = _tree('SUFFIXES = ("A", "B", "C")\n')
    assert drift._module_level_string_tuples(tree) == {"SUFFIXES": ("A", "B", "C")}


def test_module_level_tuple_with_non_literal_element_excluded():
    tree = _tree('SUFFIXES = ("A", compute(), "C")\n')
    assert drift._module_level_string_tuples(tree) == {}


def test_module_level_list_also_captured():
    tree = _tree('SUFFIXES = ["A", "B"]\n')
    assert drift._module_level_string_tuples(tree) == {"SUFFIXES": ("A", "B")}


def test_non_tuple_assignment_ignored():
    tree = _tree('NAME = "just-a-string"\n')
    assert drift._module_level_string_tuples(tree) == {}


# ---------------------------------------------------------------------------
# _scan_dynamic_families / _scan_dynamic_family_reads (direct + via analyze())
# ---------------------------------------------------------------------------
def _make_pkg(tmp_path: Path, *, env_example: str, mcp_config: dict, code: str) -> Path:
    root = tmp_path / "demo-agent"
    (root / "demo_agent").mkdir(parents=True)
    (root / ".env.example").write_text(env_example, encoding="utf-8")
    (root / "mcp_config.json").write_text(json.dumps(mcp_config), encoding="utf-8")
    (root / "demo_agent" / "auth.py").write_text(code, encoding="utf-8")
    return root


def test_scan_dynamic_families_direct(tmp_path):
    pkg = tmp_path / "pkgdirect"
    pkg.mkdir()
    (pkg / "mod.py").write_text(
        "def resolve_profile(service, other=None):\n"
        "    pass\n"
        'resolve_profile.dynamic_env_prefix_arg = "service"\n'
        'resolve_profile.dynamic_env_suffixes = ("TLS_PROFILE", "TLS_PROFILE_REF")\n',
        encoding="utf-8",
    )
    families = drift._scan_dynamic_families(pkg)
    assert "resolve_profile" in families
    prefix_arg, position, suffixes = families["resolve_profile"]
    assert prefix_arg == "service"
    assert position == 0
    assert suffixes == ("TLS_PROFILE", "TLS_PROFILE_REF")


def test_scan_dynamic_family_reads_direct(tmp_path):
    pkg = tmp_path / "pkgreads"
    pkg.mkdir()
    (pkg / "mod.py").write_text('resolve_profile("mealie")\n', encoding="utf-8")
    families = {"resolve_profile": ("service", 0, ("TLS_PROFILE", "TLS_PROFILE_REF"))}
    found = drift._scan_dynamic_family_reads(pkg, families)
    assert found == {"MEALIE_TLS_PROFILE", "MEALIE_TLS_PROFILE_REF"}


def test_scan_dynamic_family_reads_empty_families_short_circuits(tmp_path):
    pkg = tmp_path / "pkgempty"
    pkg.mkdir()
    (pkg / "mod.py").write_text('resolve_profile("mealie")\n', encoding="utf-8")
    assert drift._scan_dynamic_family_reads(pkg, {}) == set()


# ---------------------------------------------------------------------------
# _mcp_config_env_blocks
# ---------------------------------------------------------------------------
def test_mcp_config_env_blocks_dedupes_identical_blocks(tmp_path):
    pkg = tmp_path / "pkgdedupe"
    pkg.mkdir()
    cfg = {"mcpServers": {"a": {"env": {"X": "1"}}, "b": {"env": {"X": "1"}}}}
    (pkg / "mcp_config.json").write_text(json.dumps(cfg), encoding="utf-8")
    blocks = drift._mcp_config_env_blocks(pkg)
    # Two servers with an IDENTICAL env dict de-dup to one entry (same path + frozenset).
    assert len(blocks) == 1


def test_mcp_config_env_blocks_skips_data_scaffold_template(tmp_path):
    pkg = tmp_path / "pkgscaffold"
    (pkg / "agent_utilities" / "data").mkdir(parents=True)
    cfg = {"mcpServers": {"example-mcp": {"env": {"API_KEY": "x"}}}}
    (pkg / "agent_utilities" / "data" / "mcp_config.json").write_text(
        json.dumps(cfg), encoding="utf-8"
    )
    assert drift._mcp_config_env_blocks(pkg) == []


# ---------------------------------------------------------------------------
# _compose_env_keys / _compose_subst_reads
# ---------------------------------------------------------------------------
def test_compose_env_keys_block_terminated_by_dedent(tmp_path):
    pkg = tmp_path / "pkgcompose"
    pkg.mkdir()
    (pkg / "docker-compose.yml").write_text(
        "services:\n"
        "  demo:\n"
        "    environment:\n"
        "      - FOO=bar\n"
        "      - BAZ=qux\n"
        "    ports:\n"
        '      - "8080:8080"\n',
        encoding="utf-8",
    )
    keys = drift._compose_env_keys(pkg)
    assert keys == {"docker-compose.yml": {"FOO", "BAZ"}}


def test_compose_subst_reads_image_and_command(tmp_path):
    pkg = tmp_path / "pkgsubst"
    pkg.mkdir()
    (pkg / "docker-compose.yml").write_text(
        "services:\n"
        "  demo:\n"
        "    image: ${DEMO_IMAGE:?required}\n"
        "    command:\n"
        '      - "${DEMO_ARG}"\n',
        encoding="utf-8",
    )
    found = drift._compose_subst_reads(pkg)
    assert found == {"DEMO_IMAGE", "DEMO_ARG"}


def test_compose_third_party_file_skipped(tmp_path, monkeypatch):
    pkg = tmp_path / "pkgthirdparty"
    pkg.mkdir()
    fname = "postgres-compose.yml"
    monkeypatch.setattr(drift, "_THIRD_PARTY_COMPOSE_FILES", frozenset({fname}))
    (pkg / fname).write_text(
        "services:\n  db:\n    environment:\n      - POSTGRES_PASSWORD=x\n",
        encoding="utf-8",
    )
    assert drift._compose_env_keys(pkg) == {}
    assert drift._compose_subst_reads(pkg) == set()


# ---------------------------------------------------------------------------
# analyze() -- overall return shape (light integration smoke)
# ---------------------------------------------------------------------------
def test_analyze_return_shape(tmp_path):
    root = _make_pkg(
        tmp_path,
        env_example="",
        mcp_config={"mcpServers": {}},
        code="",
    )
    report = drift.analyze(root)
    assert set(report.keys()) == {"package", "code_read_count", "findings", "drift"}
    assert report["drift"] == len(report["findings"])
    assert report["package"] == "demo-agent"


if __name__ == "__main__":
    raise SystemExit(pytest.main([__file__, "-v"]))
