"""Characterization tests for `_configure_auth` (CCN 62) and supplementary
coverage of `_configure_jwt_auth` (CCN 61) in
agent_utilities/mcp/server_factory.py -- lane CX-AU-05.

`_configure_jwt_auth`'s multi-realm and resource-metadata-wrap branches
already have thorough pre-existing coverage in
tests/unit/mcp/test_multi_realm_jwt.py and
tests/unit/mcp/test_jwt_resource_metadata.py -- those files ARE the
reverse-dependency probe for this refactor and are not duplicated here.
This file only pins the branches those suites do not touch: the OIDC-
discovery JWKS fallback, the key-material/issuer/audience/audience-format
guards, the public-key-from-file and HMAC-secret paths, required-scopes
parsing, and every dispatch branch of `_configure_auth` itself (none,
static -- including the nested constant-time verifier's accept/reject
behaviour, and the missing-field guards on oauth-proxy / oidc-proxy /
remote-oauth).

Do NOT edit this file in the refactor commit.
"""

from __future__ import annotations

import asyncio
import json
from unittest.mock import MagicMock

import pytest

from agent_utilities.mcp.server_factory import (
    _configure_auth,
    _configure_jwt_auth,
    create_mcp_parser,
)


def _base_args(**overrides):
    """A real argparse.Namespace (correct defaults for every field), built
    the same way the CLI does, with a few fields overridden per scenario."""
    parser = create_mcp_parser()
    args, _ = parser.parse_known_args([])
    for key, value in overrides.items():
        setattr(args, key, value)
    return args


def _run(coro):
    return asyncio.run(coro)


# ---------------------------------------------------------------------------
# _configure_auth: top-level dispatch
# ---------------------------------------------------------------------------
def test_none_auth_type_returns_none():
    assert _configure_auth(_base_args(auth_type="none")) is None


def test_falsy_auth_type_returns_none():
    assert _configure_auth(_base_args(auth_type="")) is None


def test_delegation_without_oidc_proxy_exits(monkeypatch):
    monkeypatch.setattr(
        "agent_utilities.mcp.server_factory.mcp_auth_config",
        {
            "enable_delegation": False,
            "audience": None,
            "delegated_scopes": "api",
            "oidc_config_url": None,
            "oidc_client_id": None,
            "oidc_client_secret": None,
            "token_endpoint": None,
        },
    )
    args = _base_args(auth_type="static", enable_delegation=True, audience="x")
    with pytest.raises(SystemExit):
        _configure_auth(args)


def test_delegation_without_audience_exits(monkeypatch):
    monkeypatch.setattr(
        "agent_utilities.mcp.server_factory.mcp_auth_config",
        {
            "enable_delegation": False,
            "audience": None,
            "delegated_scopes": "api",
            "oidc_config_url": None,
            "oidc_client_id": None,
            "oidc_client_secret": None,
            "token_endpoint": None,
        },
    )
    args = _base_args(auth_type="oidc-proxy", enable_delegation=True, audience=None)
    with pytest.raises(SystemExit):
        _configure_auth(args)


# ---------------------------------------------------------------------------
# _configure_auth: static
# ---------------------------------------------------------------------------
def test_static_auth_missing_reference_exits():
    args = _base_args(auth_type="static", static_tokens_ref="")
    with pytest.raises(SystemExit):
        _configure_auth(args)


def test_static_auth_invalid_json_exits(monkeypatch):
    monkeypatch.setenv("CX_AU_05_STATIC_TOKENS", "not-json")
    args = _base_args(
        auth_type="static", static_tokens_ref="env://CX_AU_05_STATIC_TOKENS"
    )
    with pytest.raises(SystemExit):
        _configure_auth(args)


def test_static_auth_token_too_short_exits(monkeypatch):
    monkeypatch.setenv(
        "CX_AU_05_STATIC_TOKENS",
        json.dumps({"short": {"client_id": "c1", "scopes": ["read"]}}),
    )
    args = _base_args(
        auth_type="static", static_tokens_ref="env://CX_AU_05_STATIC_TOKENS"
    )
    with pytest.raises(SystemExit):
        _configure_auth(args)


def test_static_auth_valid_token_accepts_and_rejects(monkeypatch):
    good_token = "a" * 40
    monkeypatch.setenv(
        "CX_AU_05_STATIC_TOKENS",
        json.dumps({good_token: {"client_id": "c1", "scopes": ["read", "write"]}}),
    )
    args = _base_args(
        auth_type="static", static_tokens_ref="env://CX_AU_05_STATIC_TOKENS"
    )
    verifier = _configure_auth(args)
    assert verifier is not None

    accepted = _run(verifier.verify_token(good_token))
    assert accepted is not None
    assert accepted.client_id == "c1"
    assert set(accepted.scopes) == {"read", "write"}

    rejected = _run(verifier.verify_token("b" * 40))
    assert rejected is None


def test_static_auth_expired_token_rejected(monkeypatch):
    token = "e" * 40
    monkeypatch.setenv(
        "CX_AU_05_STATIC_TOKENS",
        json.dumps(
            {token: {"client_id": "c1", "scopes": [], "expires_at": 1}}
        ),  # epoch 1 -- long expired
    )
    args = _base_args(
        auth_type="static", static_tokens_ref="env://CX_AU_05_STATIC_TOKENS"
    )
    verifier = _configure_auth(args)
    assert _run(verifier.verify_token(token)) is None


# ---------------------------------------------------------------------------
# _configure_auth: redirect URI policy (shared by oauth-proxy / oidc-proxy)
# ---------------------------------------------------------------------------
def test_invalid_redirect_uri_policy_exits():
    args = _base_args(
        auth_type="static",
        static_tokens_ref="",
        allowed_client_redirect_uris="not a url, also not a url",
    )
    with pytest.raises(SystemExit):
        _configure_auth(args)


# ---------------------------------------------------------------------------
# _configure_auth: oauth-proxy / oidc-proxy / remote-oauth missing-field guards
# ---------------------------------------------------------------------------
def test_oauth_proxy_missing_fields_exits():
    args = _base_args(auth_type="oauth-proxy")
    with pytest.raises(SystemExit):
        _configure_auth(args)


def test_oidc_proxy_missing_fields_exits():
    args = _base_args(auth_type="oidc-proxy")
    with pytest.raises(SystemExit):
        _configure_auth(args)


def test_oidc_proxy_missing_audience_exits():
    args = _base_args(
        auth_type="oidc-proxy",
        oidc_config_url="https://idp.test/.well-known/openid-configuration",
        oidc_client_id="cid",
        oidc_client_secret="secret",
        oidc_base_url="https://svc.test",
        token_audience=None,
        audience=None,
    )
    with pytest.raises(SystemExit):
        _configure_auth(args)


def test_remote_oauth_missing_fields_exits():
    args = _base_args(auth_type="remote-oauth")
    with pytest.raises(SystemExit):
        _configure_auth(args)


def test_remote_oauth_too_many_auth_servers_exits():
    servers = ",".join(f"https://idp{i}.test" for i in range(17))
    args = _base_args(
        auth_type="remote-oauth",
        remote_auth_servers=servers,
        remote_base_url="https://svc.test",
        token_jwks_uri="https://idp0.test/jwks",
        token_issuer="https://idp0.test",
        token_audience="aud",
    )
    with pytest.raises(SystemExit):
        _configure_auth(args)


def test_unknown_auth_type_returns_none():
    # Falls through the elif chain -- observed, pinned behaviour.
    args = _base_args(auth_type="not-a-real-type")
    assert _configure_auth(args) is None


# ---------------------------------------------------------------------------
# _configure_jwt_auth: OIDC discovery fallback for a missing JWKS URI
# ---------------------------------------------------------------------------
def test_jwt_oidc_discovery_fills_missing_jwks_uri(monkeypatch):
    monkeypatch.setattr(
        "agent_utilities.security.oidc_discovery.jwks_uri_for",
        lambda issuer: f"{issuer}/jwks",
    )
    args = _base_args(
        auth_type="jwt",
        token_jwks_uri=None,
        token_issuer="https://idp.test/realms/one",
        token_audience="aud",
        token_public_key=None,
        token_secret_ref=None,
    )
    verifier = _configure_jwt_auth(args)
    assert verifier is not None


# ---------------------------------------------------------------------------
# _configure_jwt_auth: validation guards
# ---------------------------------------------------------------------------
def test_jwt_missing_key_material_exits():
    args = _base_args(
        auth_type="jwt",
        token_jwks_uri=None,
        token_public_key=None,
        token_secret_ref=None,
        token_issuer="https://idp.test",
        token_audience="aud",
    )
    with pytest.raises(SystemExit):
        _configure_jwt_auth(args)


def test_jwt_missing_issuer_or_audience_exits():
    args = _base_args(
        auth_type="jwt",
        token_jwks_uri="https://idp.test/jwks",
        token_issuer=None,
        token_audience="aud",
        token_secret_ref=None,
    )
    with pytest.raises(SystemExit):
        _configure_jwt_auth(args)


def test_jwt_invalid_audience_format_exits():
    args = _base_args(
        auth_type="jwt",
        token_jwks_uri="https://idp.test/jwks",
        token_issuer="https://idp.test",
        token_audience="bad\r\naudience",
        token_secret_ref=None,
    )
    with pytest.raises(SystemExit):
        _configure_jwt_auth(args)


def test_jwt_public_key_read_from_file(tmp_path):
    key_file = tmp_path / "key.pem"
    key_file.write_text("-----BEGIN PUBLIC KEY-----\nfake\n-----END PUBLIC KEY-----\n")
    args = _base_args(
        auth_type="jwt",
        token_jwks_uri=None,
        token_public_key=str(key_file),
        token_secret_ref=None,
        token_issuer="https://idp.test",
        token_audience="aud",
        token_algorithm="RS256",
    )
    verifier = _configure_jwt_auth(args)
    assert verifier is not None


def test_jwt_hmac_secret_missing_ref_exits():
    args = _base_args(
        auth_type="jwt",
        token_jwks_uri=None,
        token_public_key=None,
        token_secret_ref="",
        token_issuer="https://idp.test",
        token_audience="aud",
        token_algorithm="HS256",
    )
    with pytest.raises(SystemExit):
        _configure_jwt_auth(args)


def test_jwt_hmac_secret_resolved(monkeypatch):
    mock_client = MagicMock()
    mock_client.resolve_ref.return_value = "x" * 40
    monkeypatch.setattr(
        "agent_utilities.security.secrets_client.create_secrets_client",
        lambda: mock_client,
    )
    args = _base_args(
        auth_type="jwt",
        token_jwks_uri=None,
        token_public_key=None,
        token_secret_ref="env://SOME_HMAC_SECRET",
        token_issuer="https://idp.test",
        token_audience="aud",
        token_algorithm="HS256",
    )
    verifier = _configure_jwt_auth(args)
    assert verifier is not None


if __name__ == "__main__":
    raise SystemExit(pytest.main([__file__, "-v"]))
