"""Tests for the LeanIX metamodel → OWL compiler (CONCEPT:AU-KG.ingest.enterprise-source-extractor)."""

from __future__ import annotations

import pytest

from agent_utilities.knowledge_graph.ontology.leanix_metamodel import (
    apply_leanix_metamodel,
    compile_leanix_metamodel,
    export_leanix_ttl,
    sync_leanix_ontology,
)

# A realistic LeanIX ``/models/dataModel`` slice: two known types + one custom
# type with a custom field, plus relations (one to a known type, one to custom).
META_MODEL = {
    "factSheets": {
        "Application": {
            "fields": {
                "displayName": {"type": "STRING"},
                "businessCriticality": {"type": "SINGLE_SELECT"},
            },
            "relations": {
                "relApplicationToITComponent": {"targetFactSheetType": "ITComponent"},
                "relApplicationToDataCenter": {"targetFactSheetType": "DataCenter"},
                "lifecycle": {},  # not a relation field → ignored
            },
        },
        "ITComponent": {
            "fields": {"release": {"type": "STRING"}},
            "relations": {},
        },
        "DataCenter": {  # custom type, no ArchiMate crosswalk
            "fields": {"region": {"type": "STRING"}},
            "relations": {},
        },
    }
}


def test_compile_produces_classes_relations_fields():
    spec = compile_leanix_metamodel(META_MODEL)
    classes = {c.local: c for c in spec.classes}
    assert set(classes) == {"Application", "ITComponent", "DataCenter"}
    # Known type aligned to ArchiMate; custom type has no parent.
    assert classes["Application"].parent == "ApplicationComponent"
    assert classes["DataCenter"].parent is None

    props = {p.local: p for p in spec.object_properties}
    assert props["relApplicationToITComponent"].domain == "Application"
    assert props["relApplicationToITComponent"].range == "ITComponent"
    assert props["relApplicationToITComponent"].lpg_rel_type == (
        "REL_APPLICATION_TO_IT_COMPONENT"
    )

    dtp = {d.local for d in spec.datatype_properties}
    assert {"displayName", "businessCriticality", "release", "region"} <= dtp
    assert "factsheetName" in dtp  # always present

    assert spec.relation_map["relApplicationToDataCenter"] == (
        "REL_APPLICATION_TO_DATA_CENTER",
        "DataCenter",
    )


def test_export_ttl_is_valid_turtle_with_generated_marker():
    spec = compile_leanix_metamodel(META_MODEL)
    ttl = export_leanix_ttl(spec)
    assert "GENERATED by" in ttl
    assert "owl:imports <http://knuckles.team/kg>" in ttl
    assert ":Application a owl:Class" in ttl
    assert "rdfs:subClassOf :ApplicationComponent" in ttl
    assert ":relApplicationToITComponent a owl:ObjectProperty" in ttl

    # rdflib must parse it (proves it is well-formed OWL/Turtle).
    rdflib = pytest.importorskip("rdflib")
    g = rdflib.Graph()
    g.parse(data=ttl, format="turtle")
    assert len(g) > 0


def test_apply_dry_run_writes_nothing(tmp_path):
    target = tmp_path / "ontology_leanix.ttl"
    spec = compile_leanix_metamodel(META_MODEL)
    manifest = apply_leanix_metamodel(spec, ttl_path=target, dry_run=True)
    assert manifest["dry_run"] is True
    assert manifest["classes"] == 3
    assert "ttl_preview" in manifest
    assert not target.exists()


def test_apply_refuses_local_ttl_authority(tmp_path):
    target = tmp_path / "ontology_leanix.ttl"
    spec = compile_leanix_metamodel(META_MODEL)
    with pytest.raises(RuntimeError, match="SDK ConnectorContent pack"):
        apply_leanix_metamodel(spec, ttl_path=target, dry_run=False)
    assert not target.exists()


class _FakeClient:
    def meta_model(self):
        return META_MODEL


def test_sync_core_no_client_skips():
    out = sync_leanix_ontology(client=None, dry_run=True)
    # No LEANIX_URL/TOKEN configured in the test env → graceful skip.
    assert out["status"] == "skipped"


def test_sync_core_with_injected_client_is_preview_only(tmp_path):
    target = tmp_path / "ontology_leanix.ttl"
    out = sync_leanix_ontology(client=_FakeClient(), dry_run=True, ttl_path=target)
    assert out["status"] == "completed"
    assert out["classes"] == 3
    assert not target.exists()
