"""Capability cards — LLM semantic summaries (CONCEPT:KG-2.8 Phase 2, layer L2).

A capability card is the natural-language understanding of a symbol/file/feature:
what it does, its responsibilities, and how it's implemented. Generated by the
LLM, **cached by ``ast_hash``** so unchanged code is never re-summarised, and
``llm_fn`` is injectable so the pipeline is testable without a live model.

This is the layer that answers "how does feature X work" / "how is this
implemented" once stored on the graph.
"""

from __future__ import annotations

import json
import logging
import os
from collections.abc import Callable, Iterable
from concurrent.futures import ThreadPoolExecutor
from typing import Any

from pydantic import BaseModel, Field

from .models import CodeEntity

logger = logging.getLogger(__name__)

# prompt -> completion text
LLMFn = Callable[[str], str]


class CapabilityCard(BaseModel):
    id: str
    kind: str  # "symbol" | "file" | "feature"
    name: str
    file_path: str = ""
    ast_hash: str = ""
    summary: str = ""
    responsibilities: list[str] = Field(default_factory=list)
    patterns: list[str] = Field(default_factory=list)


_SYMBOL_PROMPT = """Document this Python {kind} named `{name}` from `{file_path}`.
Design-pattern tags (detected): {patterns}
Names it calls: {calls}
Methods/members: {methods}

Write a concrete 1-2 sentence explanation of WHAT it does and HOW it is
implemented (the approach, not line-by-line). Then list its distinct
responsibilities (1-4 short phrases).

Output ONLY a JSON object with keys "summary" (string) and "responsibilities"
(array of strings). Do not include any other text or placeholders."""


def build_symbol_prompt(c: CodeEntity, calls: list[str] | None = None) -> str:
    return _SYMBOL_PROMPT.format(
        kind=c.kind,
        name=c.name,
        file_path=c.file_path,
        patterns=", ".join(c.patterns) or "none",
        calls=", ".join((calls or [])[:20]) or "n/a",
        methods=", ".join(c.methods[:20]) or "n/a",
    )


def _parse_card_json(text: str) -> tuple[str, list[str]]:
    """Lenient parse of the LLM JSON; degrade to raw text as the summary."""
    try:
        start, end = text.index("{"), text.rindex("}") + 1
        data = json.loads(text[start:end])
        summary = str(data.get("summary", "")).strip()
        resp = [
            str(r).strip() for r in data.get("responsibilities", []) if str(r).strip()
        ]
        return summary, resp
    except (ValueError, json.JSONDecodeError):
        return text.strip()[:500], []


def generate_symbol_cards(
    entities: Iterable[CodeEntity],
    llm_fn: LLMFn,
    cache: dict[str, CapabilityCard] | None = None,
    calls_by_id: dict[str, list[str]] | None = None,
    max_workers: int = 8,
) -> list[CapabilityCard]:
    """Generate (or reuse cached) capability cards for code entities.

    Concurrency: per-entity LLM calls are fanned out across a bounded
    ``ThreadPoolExecutor`` (``max_workers``, default 8) so the research→spec/card
    loop scales instead of running one symbol at a time. Cache hits are served
    without spawning an LLM call, and each distinct uncached ``ast_hash`` is
    computed exactly once even if it appears multiple times in the batch (the LLM
    fn is invoked once per unique hash, results de-duped). The returned list
    preserves input order and the exact ``CapabilityCard`` contents.
    """
    cache = cache if cache is not None else {}
    calls_by_id = calls_by_id or {}
    materialized = list(entities)

    # Determine the distinct uncached ast_hashes; keep the first entity seen for
    # each as the representative used to build the prompt. This dedupes work so a
    # repeated ast_hash triggers exactly one LLM call.
    unique: dict[str, CodeEntity] = {}
    for c in materialized:
        if c.ast_hash in cache or c.ast_hash in unique:
            continue
        unique[c.ast_hash] = c

    def _build(c: CodeEntity) -> CapabilityCard:
        prompt = build_symbol_prompt(c, calls_by_id.get(c.id))
        try:
            summary, resp = _parse_card_json(llm_fn(prompt))
        except Exception as e:  # pragma: no cover - LLM transport failure
            logger.debug("card generation failed for %s: %s", c.id, e)
            summary, resp = "", []
        return CapabilityCard(
            id=c.id,
            kind="symbol",
            name=c.name,
            file_path=c.file_path,
            ast_hash=c.ast_hash,
            summary=summary,
            responsibilities=resp,
            patterns=c.patterns,
        )

    if unique:
        reps = list(unique.values())
        if len(reps) == 1 or max_workers <= 1:
            built = [_build(c) for c in reps]
        else:
            with ThreadPoolExecutor(max_workers=max_workers) as pool:
                built = list(pool.map(_build, reps))
        for card in built:
            cache[card.ast_hash] = card

    out: list[CapabilityCard] = []
    for c in materialized:
        cached = cache[c.ast_hash]
        # Re-key the cached card to this entity (same body, maybe new location).
        out.append(
            cached.model_copy(
                update={"id": c.id, "name": c.name, "file_path": c.file_path}
            )
        )
    return out


_FILE_PROMPT = """These are the components of the file `{file_path}`:
{components}

Summarise the file's overall responsibility and how its parts fit together in
1-2 sentences. Output ONLY a JSON object with keys "summary" (string) and
"responsibilities" (array of strings). No other text or placeholders."""


def summarize_file(
    file_path: str, symbol_cards: list[CapabilityCard], llm_fn: LLMFn
) -> CapabilityCard:
    """Roll up symbol cards into a file-level capability card (map-reduce)."""
    components = (
        "\n".join(f"- {c.name}: {c.summary}" for c in symbol_cards if c.summary)
        or "- (no documented components)"
    )
    prompt = _FILE_PROMPT.format(file_path=file_path, components=components[:6000])
    try:
        summary, resp = _parse_card_json(llm_fn(prompt))
    except Exception:  # pragma: no cover
        summary, resp = "", []
    return CapabilityCard(
        id=f"file:{file_path}",
        kind="file",
        name=file_path.split("/")[-1],
        file_path=file_path,
        summary=summary,
        responsibilities=resp,
    )


def make_lite_llm_fn() -> LLMFn:
    """Completion fn backed by the LITE chat model (fast, for routing/extraction).

    Concept extraction is a simple structured task — routing it to the lite model
    (e.g. qwen-lite) is markedly faster than the heavy KG model. (CONCEPT:KG-2.8)
    """
    try:
        from agent_utilities.core.config import config

        lite = config.lite_chat_model
        if lite:
            return make_llm_fn(model=lite.id, base_url=lite.base_url)
    except Exception:  # pragma: no cover - config/import issue
        pass
    return make_llm_fn()


def make_llm_fn(model: str | None = None, base_url: str | None = None) -> LLMFn:
    """Factory: a completion fn backed by the configured chat model (vllm.arpa).

    Kept lazy so importing this module never requires an LLM. Falls back to a
    no-op (empty string) if the client can't be built.
    """
    try:
        from openai import OpenAI

        from agent_utilities.core.config import config

        cfg = config.default_chat_model
        # Bounded timeout + retries: the OpenAI client defaults to a 600s (10min)
        # timeout, so a single stalled vLLM request would wedge a whole ingest
        # run indefinitely. Cap it (env-overridable) and let the client retry
        # transient failures; on exhaustion the caller's try/except degrades to
        # empty extraction for that item and ingestion proceeds. (CONCEPT:KG-2.8)
        try:
            _timeout = float(os.getenv("KG_LLM_TIMEOUT", "30"))
        except ValueError:
            _timeout = 30.0
        try:
            _retries = int(os.getenv("KG_LLM_MAX_RETRIES", "1"))
        except ValueError:
            _retries = 1
        client = OpenAI(
            base_url=base_url
            or (cfg.base_url if cfg else None)
            or "http://vllm.arpa/v1",
            api_key=(cfg.api_key if cfg else None) or "not-needed",
            timeout=_timeout,
            max_retries=_retries,
        )
        model_id = model or (cfg.id if cfg else None) or "default"

        from openai import BadRequestError

        def _fn(prompt: str) -> str:
            kwargs: dict[str, Any] = dict(
                model=model_id,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.0,
                max_tokens=512,
            )
            # Disable chain-of-thought on reasoning models (qwen/vLLM) so the
            # response is the JSON answer, not a "Thinking Process" preamble.
            #
            # The ``extra_body`` fallback must trigger ONLY when the server
            # rejects that field (HTTP 400) — NOT on a timeout/transport error.
            # Retrying on a timeout doubles the wall-clock cost and, combined
            # with client-level ``max_retries``, can wedge an ingest for minutes
            # on a single stalled request. Any non-400 failure degrades to empty
            # extraction so ingestion never blocks. (CONCEPT:KG-2.8)
            try:
                try:
                    resp = client.chat.completions.create(
                        **kwargs,
                        extra_body={"chat_template_kwargs": {"enable_thinking": False}},
                    )
                except BadRequestError:
                    resp = client.chat.completions.create(**kwargs)
                return resp.choices[0].message.content or ""
            except Exception as e:  # noqa: BLE001 — never let a bad call block ingest
                logger.debug("llm_fn call failed (%s); returning empty", e)
                return ""

        return _fn
    except Exception as e:  # pragma: no cover - missing dep / config
        logger.warning("make_llm_fn unavailable (%s); cards will be empty", e)
        return lambda _prompt: ""
