"""Capability cards — LLM semantic summaries (CONCEPT:EG-KG.storage.nonblocking-checkpoint Phase 2, layer L2).

A capability card is the natural-language understanding of a symbol/file/feature:
what it does, its responsibilities, and how it's implemented. Generated by the
LLM, **cached by ``ast_hash``** so unchanged code is never re-summarised, and
``llm_fn`` is injectable so the pipeline is testable without a live model.

This is the layer that answers "how does feature X work" / "how is this
implemented" once stored on the graph.
"""

from __future__ import annotations

import json
import logging
import threading
from collections.abc import Callable, Iterable
from concurrent.futures import ThreadPoolExecutor
from typing import Any

from pydantic import BaseModel, Field

from .models import CodeEntity

logger = logging.getLogger(__name__)

# Bounded LLM-card extraction limits (config discipline): the OpenAI client
# defaults to a 600s timeout, which would wedge a whole ingest on one stalled
# request — these are fixed sane caps, not per-deploy env knobs (replacing
# KG_LLM_TIMEOUT / KG_LLM_MAX_RETRIES).
_LLM_CARD_TIMEOUT_S = 30.0
_LLM_CARD_MAX_RETRIES = 1

# prompt -> completion text
LLMFn = Callable[[str], str]


class CapabilityCard(BaseModel):
    id: str
    kind: str  # "symbol" | "file" | "feature"
    name: str
    file_path: str = ""
    ast_hash: str = ""
    summary: str = ""
    responsibilities: list[str] = Field(default_factory=list)
    patterns: list[str] = Field(default_factory=list)


_SYMBOL_PROMPT = """Document this {language} {kind} named `{name}` from `{file_path}`.
Design-pattern tags (detected): {patterns}
Names it calls: {calls}
Methods/members: {methods}

Write a concrete 1-2 sentence explanation of WHAT it does and HOW it is
implemented (the approach, not line-by-line). Then list its distinct
responsibilities (1-4 short phrases).

Output ONLY a JSON object with keys "summary" (string) and "responsibilities"
(array of strings). Do not include any other text or placeholders."""


def build_symbol_prompt(c: CodeEntity, calls: list[str] | None = None) -> str:
    return _SYMBOL_PROMPT.format(
        language=(c.language or "source").strip() or "source",
        kind=c.kind,
        name=c.name,
        file_path=c.file_path,
        patterns=", ".join(c.patterns) or "none",
        calls=", ".join((calls or [])[:20]) or "n/a",
        methods=", ".join(c.methods[:20]) or "n/a",
    )


# Symbols not worth an LLM round-trip: trivial accessors/ctors/dunders whose
# behaviour is fully implied by their name. They still become Code nodes — just
# with an empty summary (no card). (CONCEPT:EG-KG.storage.nonblocking-checkpoint, #4)
_TRIVIAL_NAMES = {
    "__init__",
    "__repr__",
    "__str__",
    "__eq__",
    "__hash__",
    "__len__",
    "__enter__",
    "__exit__",
    "__iter__",
    "__next__",
    "__call__",
    "__del__",
    "toString",
    "hashCode",
    "equals",
    "Dispose",
    "Equals",
    "GetHashCode",
}
_TRIVIAL_PREFIXES = (
    "get",
    "set",
    "is",
    "has",
    "Get",
    "Set",
    "Is",
    "Has",
    "with_",
    "_get_",
    "_set_",
)


def _is_trivial_symbol(c: CodeEntity) -> bool:
    """True for getters/setters/constructors/dunders — skip the LLM card."""
    if c.kind not in ("function", "method", "constructor"):
        return False
    name = c.name or ""
    if c.kind == "constructor" or name in _TRIVIAL_NAMES:
        return True
    # get/set/is/has accessors with no/one trivial argument-ish body proxy: the
    # name alone documents them. Keep it conservative — only short accessor names.
    for p in _TRIVIAL_PREFIXES:
        rest = name[len(p) :]
        if (
            name.startswith(p) and rest[:1].isupper()
        ):  # getValue, setName, is_ready→False (not upper)
            return True
    return False


_BATCH_PROMPT = """Document each of these {language} symbols from a codebase. For
each, write a concrete 1-2 sentence explanation of WHAT it does and HOW it is
implemented, then list 1-4 distinct responsibilities.

Symbols:
{symbols}

Output ONLY a JSON array with one object per symbol IN THE SAME ORDER, each with
keys "name" (string, echo the symbol name), "summary" (string) and
"responsibilities" (array of strings). No other text or placeholders."""


def build_batch_prompt(
    entities: list[CodeEntity], calls_by_id: dict[str, list[str]] | None = None
) -> str:
    """One prompt documenting K symbols at once (cuts LLM calls ~K×, #2).

    Symbols share a language (the caller groups by language). Each is numbered so
    the model returns an ordered JSON array we can map back per-symbol.
    """
    calls_by_id = calls_by_id or {}
    language = (
        (entities[0].language or "source").strip() or "source" if entities else "source"
    )
    lines = []
    for i, c in enumerate(entities, 1):
        calls = ", ".join((calls_by_id.get(c.id) or [])[:12]) or "n/a"
        methods = ", ".join(c.methods[:12]) or "n/a"
        patterns = ", ".join(c.patterns) or "none"
        lines.append(
            f"{i}. {c.kind} `{c.name}` (file {c.file_path}) — "
            f"patterns: {patterns}; calls: {calls}; members: {methods}"
        )
    return _BATCH_PROMPT.format(language=language, symbols="\n".join(lines))


def _parse_batch_cards(text: str, n: int) -> list[tuple[str, list[str]]]:
    """Parse the JSON array of K cards; degrade to empty per missing slot."""
    out: list[tuple[str, list[str]]] = [("", []) for _ in range(n)]
    try:
        start, end = text.index("["), text.rindex("]") + 1
        arr = json.loads(text[start:end])
    except (ValueError, json.JSONDecodeError):
        return out
    for i, item in enumerate(arr[:n]):
        if not isinstance(item, dict):
            continue
        summary = str(item.get("summary", "")).strip()
        resp = [
            str(r).strip() for r in item.get("responsibilities", []) if str(r).strip()
        ]
        out[i] = (summary, resp)
    return out


def _parse_card_json(text: str) -> tuple[str, list[str]]:
    """Lenient parse of the LLM JSON; degrade to raw text as the summary."""
    try:
        start, end = text.index("{"), text.rindex("}") + 1
        data = json.loads(text[start:end])
        summary = str(data.get("summary", "")).strip()
        resp = [
            str(r).strip() for r in data.get("responsibilities", []) if str(r).strip()
        ]
        return summary, resp
    except (ValueError, json.JSONDecodeError):
        return text.strip()[:500], []


_CARD_LABEL = "CardCache"


def _is_engine_backend(backend: Any) -> bool:
    """True if ``backend`` can run arbitrary-label Cypher against the engine."""
    from ..backends.base import is_engine_authority_backend

    return is_engine_authority_backend(backend)


def _resolve_engine_backend() -> Any:
    """Acquire the engine-authority backend, raising a clear error if unreachable."""
    from ..backends.base import require_engine_authority_backend

    return require_engine_authority_backend("symbol-card cache (CONCEPT:AU-KG.backend.cache-lives-as)")


class CardStore:
    """Content-addressed persistent cache of symbol cards, keyed by ``ast_hash``.

    Identical code (same AST hash) is summarised by the LLM once *ever* — across
    ingest runs and across repos (vendored/copied code, re-ingests). Engine-only
    (CONCEPT:AU-KG.backend.cache-lives-as): the cache lives as ``:CardCache`` nodes on the **one
    epistemic-graph engine authority** (queryable, no extra local DB) — there is no
    SQLite fallback. When no engine backend is supplied the store acquires the
    active engine backend (the OS-5.63 resolver auto-starts the pi-tier engine in
    prod; the KG-2.238 fixture provides a real ephemeral one in tests), raising a
    clear error if the engine is genuinely unreachable. Thread-safe and
    best-effort on read/write: a transient query failure degrades to "no cache" so
    card generation still proceeds. (CONCEPT:EG-KG.storage.nonblocking-checkpoint, #3)
    """

    def __init__(self, backend: Any = None) -> None:
        self._lock = threading.Lock()
        self._backend: Any = backend if _is_engine_backend(backend) else None
        if self._backend is None:
            self._backend = _resolve_engine_backend()
        logger.debug("CardStore: engine mode via %s", type(self._backend).__name__)

    @staticmethod
    def _node_id(ast_hash: str) -> str:
        return f"cardcache:{ast_hash}"

    def get_many(self, hashes: list[str]) -> dict[str, tuple[str, list[str]]]:
        out: dict[str, tuple[str, list[str]]] = {}
        if not hashes:
            return out
        # Content-addressed by a deterministic node id, so each hash is an O(1)
        # keyed engine read (the engine's limited Cypher interpreter doesn't do
        # ``WHERE x IN $list``; keyed reads are the reliable engine primitive).
        for h in hashes:
            try:
                node = self._backend.get_node_properties(self._node_id(h))
            except Exception as e:  # noqa: BLE001 - cache is best-effort
                logger.debug("CardStore.get_many failed for %s: %s", h, e)
                continue
            if not node:
                continue
            try:
                resp = json.loads(node.get("responsibilities_json") or "[]")
            except (ValueError, json.JSONDecodeError):
                resp = []
            out[h] = (node.get("summary", ""), resp)
        return out

    def put_many(self, items: list[tuple[str, str, list[str]]]) -> None:
        if not items:
            return
        from datetime import UTC, datetime

        now = datetime.now(UTC).isoformat()
        try:
            with self._lock:
                for h, s, r in items:
                    self._backend.add_node(
                        self._node_id(h),
                        label=_CARD_LABEL,
                        ast_hash=h,
                        summary=s,
                        responsibilities_json=json.dumps(r),
                        updated_at=now,
                    )
        except Exception as e:  # noqa: BLE001 - cache is best-effort
            logger.debug("CardStore.put_many failed: %s", e)


def _card_for(c: CodeEntity, summary: str, resp: list[str]) -> CapabilityCard:
    return CapabilityCard(
        id=c.id,
        kind="symbol",
        name=c.name,
        file_path=c.file_path,
        ast_hash=c.ast_hash,
        summary=summary,
        responsibilities=resp,
        patterns=c.patterns,
    )


def _group_batches(reps: list[CodeEntity], batch_size: int) -> list[list[CodeEntity]]:
    """Chunk representative symbols into LLM batches, grouped by language so each
    batch prompt is single-language (#2)."""
    by_lang: dict[str, list[CodeEntity]] = {}
    for c in reps:
        by_lang.setdefault((c.language or "source").strip() or "source", []).append(c)
    batches: list[list[CodeEntity]] = []
    for items in by_lang.values():
        for i in range(0, len(items), max(1, batch_size)):
            batches.append(items[i : i + batch_size])
    return batches


def generate_symbol_cards(
    entities: Iterable[CodeEntity],
    llm_fn: LLMFn,
    cache: dict[str, CapabilityCard] | None = None,
    calls_by_id: dict[str, list[str]] | None = None,
    max_workers: int = 8,
    batch_size: int = 12,
    store: CardStore | None = None,
) -> list[CapabilityCard]:
    """Generate (or reuse cached) capability cards for code entities.

    Cost controls (CONCEPT:EG-KG.storage.nonblocking-checkpoint):
    - **dedup + in-memory cache** by ``ast_hash`` — a repeated/unchanged symbol is
      summarised once.
    - **persistent cache** (``store``, opt-in) — identical code summarised once
      *ever*, across runs/repos (#3).
    - **trivial-symbol skip** — getters/setters/ctors/dunders get an empty card,
      no LLM call (#4).
    - **multi-symbol batching** — up to ``batch_size`` symbols per LLM call, grouped
      by language, with the batches fanned out across a ``ThreadPoolExecutor``
      (``max_workers``) (#2). A 1-symbol batch uses the single-symbol prompt so the
      raw-text degrade path is preserved.

    The returned list preserves input order and the exact ``CapabilityCard`` contents.
    """
    cache = cache if cache is not None else {}
    calls_by_id = calls_by_id or {}
    materialized = list(entities)

    # Distinct uncached ast_hashes; first entity seen is the representative.
    unique: dict[str, CodeEntity] = {}
    for c in materialized:
        if c.ast_hash in cache or c.ast_hash in unique:
            continue
        unique[c.ast_hash] = c

    if unique:
        # (1) trivial symbols → empty card, no LLM.
        remaining: dict[str, CodeEntity] = {}
        for h, c in unique.items():
            if _is_trivial_symbol(c):
                cache[h] = _card_for(c, "", [])
            else:
                remaining[h] = c

        # (2) persistent store hits.
        if remaining and store is not None:
            for h, (summary, resp) in store.get_many(list(remaining)).items():
                cache[h] = _card_for(remaining[h], summary, resp)
                remaining.pop(h, None)

        # (3) LLM for the rest — batched by language, parallel across batches.
        if remaining:

            def _do_batch(group: list[CodeEntity]) -> list[CapabilityCard]:
                if len(group) == 1:
                    c = group[0]
                    prompt = build_symbol_prompt(c, calls_by_id.get(c.id))
                    try:
                        summary, resp = _parse_card_json(llm_fn(prompt))
                    except Exception as e:  # pragma: no cover - transport failure
                        logger.debug("card gen failed for %s: %s", c.id, e)
                        summary, resp = "", []
                    return [_card_for(c, summary, resp)]
                prompt = build_batch_prompt(group, calls_by_id)
                try:
                    parsed = _parse_batch_cards(llm_fn(prompt), len(group))
                except Exception as e:  # pragma: no cover - transport failure
                    logger.debug("batch card gen failed (%d syms): %s", len(group), e)
                    parsed = [("", []) for _ in group]
                return [
                    _card_for(c, s, r) for c, (s, r) in zip(group, parsed, strict=True)
                ]

            batches = _group_batches(list(remaining.values()), batch_size)
            if len(batches) <= 1 or max_workers <= 1:
                built_groups = [_do_batch(g) for g in batches]
            else:
                with ThreadPoolExecutor(max_workers=max_workers) as pool:
                    built_groups = list(pool.map(_do_batch, batches))

            fresh: list[CapabilityCard] = [c for grp in built_groups for c in grp]
            for card in fresh:
                cache[card.ast_hash] = card
            if store is not None:
                store.put_many(
                    [
                        (c.ast_hash, c.summary, c.responsibilities)
                        for c in fresh
                        if c.summary
                    ]
                )

    out: list[CapabilityCard] = []
    for c in materialized:
        cached = cache[c.ast_hash]
        # Re-key the cached card to this entity (same body, maybe new location).
        out.append(
            cached.model_copy(
                update={"id": c.id, "name": c.name, "file_path": c.file_path}
            )
        )
    return out


_FILE_PROMPT = """These are the components of the file `{file_path}`:
{components}

Summarise the file's overall responsibility and how its parts fit together in
1-2 sentences. Output ONLY a JSON object with keys "summary" (string) and
"responsibilities" (array of strings). No other text or placeholders."""


def summarize_file(
    file_path: str, symbol_cards: list[CapabilityCard], llm_fn: LLMFn
) -> CapabilityCard:
    """Roll up symbol cards into a file-level capability card (map-reduce)."""
    components = (
        "\n".join(f"- {c.name}: {c.summary}" for c in symbol_cards if c.summary)
        or "- (no documented components)"
    )
    prompt = _FILE_PROMPT.format(file_path=file_path, components=components[:6000])
    try:
        summary, resp = _parse_card_json(llm_fn(prompt))
    except Exception:  # pragma: no cover
        summary, resp = "", []
    return CapabilityCard(
        id=f"file:{file_path}",
        kind="file",
        name=file_path.split("/")[-1],
        file_path=file_path,
        summary=summary,
        responsibilities=resp,
    )


def make_lite_llm_fn() -> LLMFn:
    """Completion fn backed by the LITE chat model (fast, for routing/extraction).

    Concept extraction is a simple structured task — routing it to the lite model
    (e.g. qwen-lite) is markedly faster than the heavy KG model. (CONCEPT:EG-KG.storage.nonblocking-checkpoint)
    """
    try:
        from agent_utilities.core.config import config

        lite = config.lite_chat_model
        if lite:
            return make_llm_fn(model=lite.id, base_url=lite.base_url)
    except Exception:  # pragma: no cover - config/import issue
        pass
    return make_llm_fn()


def make_llm_fn(model: str | None = None, base_url: str | None = None) -> LLMFn:
    """Factory: a completion fn backed by the configured chat model (vllm.arpa).

    Kept lazy so importing this module never requires an LLM. Falls back to a
    no-op (empty string) if the client can't be built.
    """
    try:
        from openai import OpenAI

        from agent_utilities.core.config import config

        cfg = config.default_chat_model
        # Bounded timeout + retries: the OpenAI client defaults to a 600s (10min)
        # timeout, so a single stalled vLLM request would wedge a whole ingest
        # run indefinitely. Cap it and let the client retry transient failures;
        # on exhaustion the caller's try/except degrades to empty extraction for
        # that item and ingestion proceeds. Fixed bounded values (config
        # discipline: one correct value, not an env knob). (CONCEPT:EG-KG.storage.nonblocking-checkpoint)
        _timeout = _LLM_CARD_TIMEOUT_S
        _retries = _LLM_CARD_MAX_RETRIES
        client = OpenAI(
            base_url=base_url
            or (cfg.base_url if cfg else None)
            or "http://vllm.arpa/v1",
            api_key=(cfg.api_key if cfg else None) or "not-needed",
            timeout=_timeout,
            max_retries=_retries,
        )
        model_id = model or (cfg.id if cfg else None) or "default"

        from openai import BadRequestError

        def _fn(prompt: str) -> str:
            kwargs: dict[str, Any] = dict(
                model=model_id,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.0,
                max_tokens=512,
            )
            # Disable chain-of-thought on reasoning models (qwen/vLLM) so the
            # response is the JSON answer, not a "Thinking Process" preamble.
            #
            # The ``extra_body`` fallback must trigger ONLY when the server
            # rejects that field (HTTP 400) — NOT on a timeout/transport error.
            # Retrying on a timeout doubles the wall-clock cost and, combined
            # with client-level ``max_retries``, can wedge an ingest for minutes
            # on a single stalled request. Any non-400 failure degrades to empty
            # extraction so ingestion never blocks. (CONCEPT:EG-KG.storage.nonblocking-checkpoint)
            try:
                try:
                    resp = client.chat.completions.create(
                        **kwargs,
                        extra_body={"chat_template_kwargs": {"enable_thinking": False}},
                    )
                except BadRequestError:
                    resp = client.chat.completions.create(**kwargs)
                # Capture token usage into the active ingest profile (OS-5.69) —
                # a no-op when no ingest is being profiled.
                _u = getattr(resp, "usage", None)
                if _u is not None:
                    from ..core.ingest_profile import record_llm_usage

                    record_llm_usage(
                        getattr(_u, "prompt_tokens", 0),
                        getattr(_u, "completion_tokens", 0),
                    )
                return resp.choices[0].message.content or ""
            except Exception as e:  # noqa: BLE001 — never let a bad call block ingest
                logger.debug("llm_fn call failed (%s); returning empty", e)
                return ""

        return _fn
    except Exception as e:  # pragma: no cover - missing dep / config
        logger.warning("make_llm_fn unavailable (%s); cards will be empty", e)
        return lambda _prompt: ""
