"""Cypher-to-SQL Transpiler for PostgreSQL Backend.

Translates the specific Cypher query patterns generated by the
IntelligenceGraphEngine into PostgreSQL-compatible SQL statements.

This is NOT a general-purpose Cypher parser — it handles the ~15
distinct patterns the engine actually emits via regex matching.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

logger = logging.getLogger(__name__)

# All known node labels from the schema (used for table lookups)
_LABEL_PATTERN = re.compile(r"\((\w+):(\w+)", re.IGNORECASE)
_MATCH_BY_ID = re.compile(
    r"MATCH\s+\((\w+):(\w+)\)\s+WHERE\s+\1\.id\s*=\s*\$(\w+)",
    re.IGNORECASE,
)
_MATCH_ANY_BY_ID = re.compile(
    r"MATCH\s+\((\w+)\)\s+WHERE\s+\1\.id\s*=\s*\$(\w+)",
    re.IGNORECASE,
)
_CREATE_NODE = re.compile(r"CREATE\s+\((\w+):(\w+)\s*\{([^}]+)\}\)", re.IGNORECASE)
_SET_CLAUSE = re.compile(r"SET\s+(.+?)(?:RETURN|$)", re.IGNORECASE | re.DOTALL)
_RETURN_CLAUSE = re.compile(r"RETURN\s+(.+?)$", re.IGNORECASE | re.DOTALL)
_LIMIT_CLAUSE = re.compile(r"LIMIT\s+(\$?\w+)", re.IGNORECASE)
_ORDER_BY_CLAUSE = re.compile(
    r"ORDER\s+BY\s+(.+?)(?:LIMIT|$)", re.IGNORECASE | re.DOTALL
)
_MERGE_NODE = re.compile(
    r"MERGE\s+\((\w+):(\w+)\s*\{\s*id\s*:\s*\$(\w+)\s*\}\s*\)", re.IGNORECASE
)
_MERGE_REL = re.compile(
    r"MERGE\s+\((\w+)\)-\[(\w+):(\w+)(?:\s*\{([^}]+)\})?\]->\((\w+)\)", re.IGNORECASE
)
_MATCH_REL = re.compile(
    r"MATCH\s+\((\w+)(?::(\w+))?\s*(?:\{[^}]*\})?\)-\[(\w+)?:?(\w+)?\]->?\((\w+)(?::(\w+))?\s*(?:\{[^}]*\})?\)",
    re.IGNORECASE,
)
_CONTAINS = re.compile(
    r"toLower\((\w+)\.(\w+)\)\s+CONTAINS\s+toLower\(\$(\w+)\)",
    re.IGNORECASE,
)
_LABEL_FUNC = re.compile(r"label\((\w+)\)\s+as\s+(\w+)", re.IGNORECASE)
_COUNT_PATTERN = re.compile(r"count\((\w+)\)\s+as\s+(\w+)", re.IGNORECASE)
_DETACH_DELETE = re.compile(r"DETACH\s+DELETE\s+(\w+)", re.IGNORECASE)
_DELETE = re.compile(r"DELETE\s+(\w+)", re.IGNORECASE)
_COALESCE = re.compile(
    r"coalesce\((\w+)\.(\w+),\s*'([^']*)'\)\s*(<>|=)\s*'([^']*)'",
    re.IGNORECASE,
)


class QueryType(Enum):
    SELECT = "select"
    INSERT = "insert"
    UPDATE = "update"
    DELETE = "delete"
    UPSERT_EDGE = "upsert_edge"
    LABEL_LOOKUP = "label_lookup"
    COUNT = "count"
    UNKNOWN = "unknown"


@dataclass
class TranspiledQuery:
    """Result of transpiling a Cypher query to SQL."""

    sql: str
    params: list[Any] = field(default_factory=list)
    query_type: QueryType = QueryType.UNKNOWN
    return_columns: list[str] = field(default_factory=list)
    target_table: str | None = None
    node_alias: str | None = None


# Edge table name constant
EDGE_TABLE = "kg_edges"


def _param_key_to_positional(
    params: dict[str, Any], keys: list[str]
) -> tuple[list[Any], dict[str, int]]:
    """Convert named params to positional list, returning values and index map."""
    values = []
    index_map = {}
    for k in keys:
        if k.startswith("_"):
            continue
        if k in params:
            values.append(params[k])
            index_map[k] = len(values)
    return values, index_map


def _sanitize_param(v: Any) -> Any:
    """Make a node-property value safe to bind to a Postgres placeholder.

    - strip NUL (0x00) from strings: a TEXT/JSON column rejects them
      ("PostgreSQL text fields cannot contain NUL bytes").
    - JSON-encode ``dict`` values: psycopg cannot adapt a bare ``dict`` to ``%s``
      ("cannot adapt type 'dict'"); a JSON string round-trips for TEXT.
    - pass a SCALAR ``list`` through as a Python list: psycopg adapts it to a
      Postgres array, which is what ``STRING[]`` → ``TEXT[]`` columns expect.
      json.dumps'ing it ("[...]") made PG reject it ("malformed array literal" —
      PG array literals are "{...}"). A list containing dict/list can't be
      array-adapted, so JSON-encode those. (CONCEPT:KG-2.9 write-path hardening.)
    """
    if isinstance(v, str):
        return v.replace("\x00", "") if "\x00" in v else v
    if isinstance(v, dict):
        import json

        return json.dumps(v, default=str)
    if isinstance(v, list):
        if all(x is None or isinstance(x, str | int | float | bool) for x in v):
            return v  # psycopg → Postgres array (TEXT[] columns)
        import json

        return json.dumps(v, default=str)
    return v


def transpile(
    cypher: str,
    params: dict[str, Any] | None = None,
    known_tables: set[str] | None = None,
    node_tables: set[str] | None = None,
) -> TranspiledQuery:
    """Transpile a Cypher query into a PostgreSQL SQL statement.

    Args:
        cypher: The Cypher query string from the engine.
        params: Named parameters from the engine.
        known_tables: Set of known table names in the database (used to resolve
            label-specific matches to their table).
        node_tables: Subset of ``known_tables`` that carry the **universal node
            shape** (``id, name, type, properties, created_at``). A label-LESS
            fan-out (``MATCH (n {id: …})``) projects ``properties`` across a UNION,
            so it must only span node-shaped tables — typed/ontology tables
            (e.g. ``Account``) lack ``properties`` and would make the UNION fail
            with ``column "properties" does not exist``. Defaults to
            ``known_tables`` when not supplied (back-compatible).
    """
    params = params or {}
    known_tables = known_tables or set()
    node_tables = node_tables if node_tables is not None else known_tables
    cypher_stripped = cypher.strip().rstrip(";")

    # Remove internal params
    clean_params = {k: v for k, v in params.items() if not k.startswith("_")}

    # --- Pattern 1: CREATE (n:Label {props}) ---
    m = _CREATE_NODE.search(cypher_stripped)
    if m and cypher_stripped.upper().startswith("CREATE"):
        alias, label, props_str = m.group(1), m.group(2), m.group(3)
        # Parse "key: $param" pairs
        prop_pairs = re.findall(r"`?(\w+)`?\s*:\s*\$(\w+)", props_str)
        cols = [p[0] for p in prop_pairs]
        param_keys = [p[1] for p in prop_pairs]
        placeholders = ["%s" for _ in cols]
        values = [_sanitize_param(clean_params.get(k)) for k in param_keys]
        sql = f'INSERT INTO "{label}" ({", ".join(cols)}) VALUES ({", ".join(placeholders)}) ON CONFLICT (id) DO NOTHING'
        return TranspiledQuery(
            sql=sql, params=values, query_type=QueryType.INSERT, target_table=label
        )

    # --- Pattern 1b: MERGE (n:Label {id: $id}) [SET n.k = $props_k ...] → upsert ---
    m_merge_node = _MERGE_NODE.search(cypher_stripped)
    if m_merge_node and cypher_stripped.upper().startswith("MERGE"):
        alias, label, id_param = (
            m_merge_node.group(1),
            m_merge_node.group(2),
            m_merge_node.group(3),
        )
        m_set = _SET_CLAUSE.search(cypher_stripped)
        set_pairs = (
            re.findall(rf"{alias}\.`?(\w+)`?\s*=\s*\$(\w+)", m_set.group(1))
            if m_set
            else []
        )
        cols = ["id"] + [p[0] for p in set_pairs if p[0] != "id"]
        merge_values = [_sanitize_param(clean_params.get(id_param))] + [
            _sanitize_param(clean_params.get(p[1])) for p in set_pairs if p[0] != "id"
        ]
        col_list = ", ".join(f'"{c}"' for c in cols)
        placeholder_sql = ", ".join("%s" for _ in cols)
        update_cols = [c for c in cols if c != "id"]
        if update_cols:
            updates = ", ".join(f'"{c}" = EXCLUDED."{c}"' for c in update_cols)
            sql = (
                f'INSERT INTO "{label}" ({col_list}) VALUES ({placeholder_sql}) '
                f"ON CONFLICT (id) DO UPDATE SET {updates}"
            )
        else:
            sql = (
                f'INSERT INTO "{label}" ({col_list}) VALUES ({placeholder_sql}) '
                f"ON CONFLICT (id) DO NOTHING"
            )
        return TranspiledQuery(
            sql=sql,
            params=merge_values,
            query_type=QueryType.INSERT,
            target_table=label,
        )

    # --- Pattern 2: MATCH (n:Label) WHERE n.id = $id SET ... RETURN ---
    m_id = _MATCH_BY_ID.search(cypher_stripped)
    m_set = _SET_CLAUSE.search(cypher_stripped)
    if m_id and m_set:
        alias, label, id_param = m_id.group(1), m_id.group(2), m_id.group(3)
        set_str = m_set.group(1).strip()
        # Parse "n.key = $param" pairs
        set_pairs = re.findall(rf"{alias}\.`?(\w+)`?\s*=\s*\$(\w+)", set_str)
        if set_pairs:
            set_clauses = [f'"{p[0]}" = %s' for p in set_pairs]
            values = [clean_params.get(p[1]) for p in set_pairs]
            values.append(clean_params.get(id_param))
            sql = f'UPDATE "{label}" SET {", ".join(set_clauses)} WHERE id = %s'

            # Check for RETURN
            m_ret = _RETURN_CLAUSE.search(cypher_stripped)
            if m_ret:
                ret_str = m_ret.group(1).strip()
                if f"{alias}.id" in ret_str:
                    sql += " RETURNING id"
            return TranspiledQuery(
                sql=sql,
                params=values,
                query_type=QueryType.UPDATE,
                target_table=label,
                node_alias=alias,
            )

    # --- Pattern 3: MATCH (n) WHERE n.id = $id RETURN label(n) as lbl ---
    m_any = _MATCH_ANY_BY_ID.search(cypher_stripped)
    m_label = _LABEL_FUNC.search(cypher_stripped)
    if m_any and m_label:
        alias, id_param = m_any.group(1), m_any.group(2)
        lbl_alias = m_label.group(2)
        id_val = clean_params.get(id_param)
        # Search all known tables for this ID
        if known_tables:
            union_parts = []
            for tbl in sorted(known_tables):
                union_parts.append(
                    f"SELECT '{tbl}' AS {lbl_alias} FROM \"{tbl}\" WHERE id = %s"
                )
            sql = " UNION ALL ".join(union_parts) + " LIMIT 1"
            values = [id_val] * len(known_tables)
            return TranspiledQuery(
                sql=sql,
                params=values,
                query_type=QueryType.LABEL_LOOKUP,
                return_columns=[lbl_alias],
            )

    # --- Pattern 3.5: MATCH (s)-[r]->(t) (relationship select) ---
    m_rel = _MATCH_REL.search(cypher_stripped)
    if m_rel and not cypher_stripped.upper().startswith("MERGE"):
        s_alias = m_rel.group(1)
        m_rel.group(2)
        r_alias = m_rel.group(3) or "r"
        r_type = m_rel.group(4)
        t_alias = m_rel.group(5)
        m_rel.group(6)

        s_label = m_rel.group(2)
        t_label = m_rel.group(6)
        sid_param = _find_id_param(cypher_stripped, s_alias, clean_params)
        tid_param = _find_id_param(cypher_stripped, t_alias, clean_params)
        sid = clean_params.get(sid_param, clean_params.get("sid"))
        tid = clean_params.get(tid_param, clean_params.get("tid"))

        # Case B: general single-hop TRAVERSAL — endpoint ids unknown but both
        # labels present. Join the per-label node tables through ``kg_edges``.
        # (Case A below handles the "edge between two known ids" lookup.)
        # CONCEPT:KG-2.7 — vendor-agnostic traversal on the durable store.
        labels_ok = bool(s_label and t_label) and (
            not known_tables or (s_label in known_tables and t_label in known_tables)
        )
        if sid is None and tid is None and labels_ok:
            tq = _build_traversal(
                cypher_stripped,
                s_alias,
                s_label,
                r_type,
                t_alias,
                t_label,
                clean_params,
            )
            if tq is not None:
                return tq

        m_ret = _RETURN_CLAUSE.search(cypher_stripped)
        select_cols = []
        return_cols = []
        is_count = False
        if m_ret:
            ret_raw = m_ret.group(1).strip()
            items = [item.strip() for item in ret_raw.split(",")]
            for item in items:
                # ``RETURN count(r) AS c`` / ``count(*)`` — an aggregate over the matched
                # edges, not a property projection. Emit ``count(*) AS <alias>`` (mirrors
                # _build_traversal's count handling); without this branch the item matched
                # nothing and the projection silently fell back to ``SELECT properties``,
                # so ``rows[0]["c"]`` was a JSONB blob instead of the integer count.
                m_count = re.search(
                    r"count\s*\(\s*(?:\*|\w+)\s*\)\s*(?:AS\s+(\w+))?",
                    item,
                    re.IGNORECASE,
                )
                if m_count:
                    cnt_alias = m_count.group(1) or "count"
                    select_cols.append(f"count(*) AS {cnt_alias}")
                    return_cols.append(cnt_alias)
                    is_count = True
                    continue
                m_prop = re.search(
                    rf"{r_alias}\.(\w+)\s+(?:AS\s+)?(\w+)", item, re.IGNORECASE
                )
                if m_prop:
                    prop_name = m_prop.group(1)
                    prop_alias = m_prop.group(2)
                    select_cols.append(f"(properties->>'{prop_name}') AS {prop_alias}")
                    return_cols.append(prop_alias)
                else:
                    m_prop_simple = re.search(rf"{r_alias}\.(\w+)", item, re.IGNORECASE)
                    if m_prop_simple:
                        prop_name = m_prop_simple.group(1)
                        select_cols.append(
                            f"(properties->>'{prop_name}') AS {prop_name}"
                        )
                        return_cols.append(prop_name)
                    elif item == r_alias:
                        select_cols.append("properties")
                        return_cols.append(r_alias)

        if not select_cols:
            select_cols = ["properties"]
            return_cols = [r_alias]

        select_clause = ", ".join(select_cols)

        sql = f"SELECT {select_clause} FROM {EDGE_TABLE} WHERE source_id = %s AND target_id = %s"
        params_list = [sid, tid]
        if r_type:
            sql += " AND rel_type = %s"
            params_list.append(r_type)

        return TranspiledQuery(
            sql=sql,
            params=params_list,
            query_type=QueryType.COUNT if is_count else QueryType.SELECT,
            return_columns=return_cols,
        )

    # --- Pattern 4: MATCH (n:Label) WHERE ... RETURN n (with filters) ---
    if cypher_stripped.upper().startswith("MATCH"):
        m_label_match = _LABEL_PATTERN.search(cypher_stripped)
        label = m_label_match.group(2) if m_label_match else None
        alias = m_label_match.group(1) if m_label_match else "n"

        # Check for count
        m_cnt = _COUNT_PATTERN.search(cypher_stripped)
        if m_cnt:
            cnt_alias = m_cnt.group(2)
            where_sql, where_vals = _build_where(cypher_stripped, alias, clean_params)
            tbl = f'"{label}"' if label else _union_all_tables(node_tables)
            if label:
                sql = f"SELECT COUNT(*) AS {cnt_alias} FROM {tbl}"
                if where_sql:
                    sql += f" WHERE {where_sql}"
                return TranspiledQuery(
                    sql=sql,
                    params=where_vals,
                    query_type=QueryType.COUNT,
                    return_columns=[cnt_alias],
                )

        # Check for DETACH DELETE
        m_del = _DETACH_DELETE.search(cypher_stripped) or _DELETE.search(
            cypher_stripped
        )
        if m_del:
            where_sql, where_vals = _build_where(cypher_stripped, alias, clean_params)
            if label:
                sqls = []
                # Delete edges first
                sqls.append(
                    f'DELETE FROM {EDGE_TABLE} WHERE source_id IN (SELECT id FROM "{label}" WHERE {where_sql}) '
                    f'OR target_id IN (SELECT id FROM "{label}" WHERE {where_sql})'
                )
                sqls.append(f'DELETE FROM "{label}" WHERE {where_sql}')
                # We return the last statement; caller should handle cascade
                return TranspiledQuery(
                    sql=sqls[-1],
                    params=where_vals,
                    query_type=QueryType.DELETE,
                    target_table=label,
                )

        # Check for MERGE relationship
        m_merge = _MERGE_REL.search(cypher_stripped)
        if m_merge:
            s_alias = m_merge.group(1)
            _r_alias = m_merge.group(2)  # noqa: F841
            rel_type = m_merge.group(3)
            props_str = m_merge.group(4)
            t_alias = m_merge.group(5)
            # Extract source/target IDs from earlier MATCH
            sid_param = _find_id_param(cypher_stripped, s_alias, clean_params)
            tid_param = _find_id_param(cypher_stripped, t_alias, clean_params)
            sid = clean_params.get(sid_param, clean_params.get("sid"))
            tid = clean_params.get(tid_param, clean_params.get("tid"))
            sql = (
                f"INSERT INTO {EDGE_TABLE} (source_id, target_id, rel_type, properties) "
                f"VALUES (%s, %s, %s, %s::jsonb) "
                f"ON CONFLICT (source_id, target_id, rel_type) DO UPDATE SET properties = EXCLUDED.properties"  # nosec B608
            )
            # Collect edge properties (both inline literals and params)
            edge_props = {}
            if props_str:
                for pair in re.split(r",\s*", props_str):
                    parts = pair.split(":")
                    if len(parts) == 2:
                        k_prop = parts[0].strip()
                        v_raw = parts[1].strip()
                        if (v_raw.startswith("'") and v_raw.endswith("'")) or (
                            v_raw.startswith('"') and v_raw.endswith('"')
                        ):
                            edge_props[k_prop] = v_raw[1:-1]
                        else:
                            try:
                                if "." in v_raw:
                                    edge_props[k_prop] = float(v_raw)
                                else:
                                    edge_props[k_prop] = int(v_raw)
                            except ValueError:
                                edge_props[k_prop] = v_raw

            for k, v in clean_params.items():
                if k not in ("sid", "tid", "id", "source", "target"):
                    edge_props[k] = v

            import json

            return TranspiledQuery(
                sql=sql,
                params=[sid, tid, rel_type, json.dumps(edge_props, default=str)],
                query_type=QueryType.UPSERT_EDGE,
            )

        # Standard SELECT with filters
        where_sql, where_vals = _build_where(cypher_stripped, alias, clean_params)

        # Determine return columns
        m_ret = _RETURN_CLAUSE.search(cypher_stripped)
        sel_cols = "*"
        # ``projecting`` = the RETURN names specific properties (``RETURN n.x AS y, ...``)
        # rather than the whole node (``RETURN n``). A projection must yield FLAT,
        # alias-keyed rows; only a bare ``RETURN n`` is wrapped under the node alias by
        # the backend (execute's ``{node_alias: {...}}``). Node properties are stored as
        # top-level columns (the MERGE/INSERT auto-DDLs a column per property), so each
        # item maps to ``"<prop>" AS "<alias>"`` — carrying the RETURN alias (previously
        # dropped, which collapsed every projection into ``{'n': {...}}``).
        projecting = False
        if m_ret:
            ret_raw = m_ret.group(1).strip()
            # Remove ORDER BY / LIMIT from return
            ret_raw = re.sub(r"ORDER\s+BY.*$", "", ret_raw, flags=re.IGNORECASE).strip()
            ret_raw = re.sub(r"LIMIT\s+.*$", "", ret_raw, flags=re.IGNORECASE).strip()
            if ret_raw == alias:
                sel_cols = "*"
            elif f"{alias}." in ret_raw:
                cols_sql = []
                for item in [it.strip() for it in ret_raw.split(",")]:
                    m_item = re.search(
                        rf"{alias}\.`?(\w+)`?(?:\s+AS\s+(\w+))?", item, re.IGNORECASE
                    )
                    if not m_item:
                        continue
                    col = m_item.group(1)
                    out_alias = m_item.group(2) or col
                    cols_sql.append(f'"{col}" AS "{out_alias}"')
                if cols_sql:
                    sel_cols = ", ".join(cols_sql)
                    projecting = True

        if label:
            sql = f'SELECT {sel_cols} FROM "{label}"'
        else:
            # No label — search all tables
            sql = _union_all_tables(node_tables, sel_cols)

        if where_sql:
            if label:
                sql += f" WHERE {where_sql}"
            else:
                # For UNION ALL, wrap each with WHERE. Each branch repeats the
                # WHERE clause (and thus its ``%s`` placeholders), so the bound
                # params must be repeated once per table — otherwise psycopg
                # raises "the query has N placeholders but 1 parameters were
                # passed" (the id-by-label fan-out bug). (CONCEPT:KG-2.7)
                sql = _union_all_tables(node_tables, sel_cols, where_sql)
                # Params repeat once per UNION branch — branches span node_tables
                # (the property-shaped subset), so multiply by len(node_tables), NOT
                # len(known_tables); otherwise the placeholder/param counts diverge
                # ("N placeholders but M parameters"). (CONCEPT:KG-2.9)
                where_vals = where_vals * len(node_tables)

        # ORDER BY
        m_order = _ORDER_BY_CLAUSE.search(cypher_stripped)
        if m_order and label:
            order_raw = m_order.group(1).strip()
            order_raw = re.sub(rf"{alias}\.", "", order_raw)
            sql += f" ORDER BY {order_raw}"

        # LIMIT
        m_limit = _LIMIT_CLAUSE.search(cypher_stripped)
        if m_limit:
            limit_val = m_limit.group(1)
            if limit_val.startswith("$"):
                where_vals.append(clean_params.get(limit_val[1:], 100))
                sql += " LIMIT %s"
            else:
                sql += f" LIMIT {limit_val}"

        return TranspiledQuery(
            sql=sql,
            params=where_vals,
            query_type=QueryType.SELECT,
            target_table=label,
            # Only wrap a bare ``RETURN n`` under the node alias; a property projection
            # returns flat alias-keyed rows (node_alias=None).
            node_alias=None if projecting else alias,
        )

    # Fallback: unknown pattern
    logger.warning("Cypher transpiler: unrecognized pattern: %.200s", cypher_stripped)
    return TranspiledQuery(sql="SELECT 1 WHERE false", query_type=QueryType.UNKNOWN)


def _build_traversal(
    cypher: str,
    s_alias: str,
    s_label: str,
    r_type: str | None,
    t_alias: str,
    t_label: str,
    params: dict[str, Any],
) -> TranspiledQuery | None:
    """Single-hop traversal ``(s:L1)-[:R]->(t:L2)`` → JOIN over ``kg_edges``.

    Joins the per-label node tables (``"L1"`` / ``"L2"``) through the relational
    edge table. Supports ``RETURN count(...)`` (incl. ``DISTINCT``), ``alias.col``
    projections, and ``LIMIT``. Returns ``None`` for unsupported RETURN shapes so
    the caller can fall through. (CONCEPT:KG-2.7)
    """
    m_ret = _RETURN_CLAUSE.search(cypher)
    ret_raw = m_ret.group(1).strip() if m_ret else ""
    ret_raw = re.split(r"\bORDER\s+BY\b|\bLIMIT\b", ret_raw, flags=re.IGNORECASE)[
        0
    ].strip()

    join = (
        f'FROM "{s_label}" {s_alias} JOIN {EDGE_TABLE} e ON e.source_id = {s_alias}.id'
    )
    params_list: list[Any] = []
    if r_type:
        join += " AND e.rel_type = %s"
        params_list.append(r_type)
    join += f' JOIN "{t_label}" {t_alias} ON {t_alias}.id = e.target_id'

    limit_sql = ""
    m_lim = _LIMIT_CLAUSE.search(cypher)
    if m_lim:
        lim = m_lim.group(1)
        if lim.startswith("$"):
            lv = params.get(lim[1:])
            if isinstance(lv, int):
                limit_sql = f" LIMIT {int(lv)}"
        elif lim.isdigit():
            limit_sql = f" LIMIT {int(lim)}"

    # RETURN count(...)
    if re.search(r"\bcount\s*\(", ret_raw, re.IGNORECASE):
        mc = re.search(
            r"count\s*\(\s*(distinct\s+)?(\*|\w+)\s*\)\s*(?:as\s+(\w+))?",
            ret_raw,
            re.IGNORECASE,
        )
        alias = mc.group(3) if (mc and mc.group(3)) else "count"
        distinct = bool(mc and mc.group(1))
        tgt = mc.group(2) if mc else "*"
        if distinct and tgt == s_alias:
            expr = f"count(DISTINCT {s_alias}.id)"
        elif distinct and tgt == t_alias:
            expr = f"count(DISTINCT {t_alias}.id)"
        else:
            expr = "count(*)"
        return TranspiledQuery(
            sql=f"SELECT {expr} AS {alias} {join}",
            params=params_list,
            query_type=QueryType.COUNT,
            return_columns=[alias],
        )

    # RETURN alias.col [AS name], ...
    select_cols: list[str] = []
    return_cols: list[str] = []
    for item in [i.strip() for i in ret_raw.split(",") if i.strip()]:
        mp = re.match(
            rf"(?:{re.escape(s_alias)}|{re.escape(t_alias)})\.(\w+)\s*(?:as\s+(\w+))?$",
            item,
            re.IGNORECASE,
        )
        if mp:
            a = item.split(".")[0].strip()
            col = mp.group(1)
            al = mp.group(2) or col
            select_cols.append(f'{a}."{col}" AS {al}')
            return_cols.append(al)
        elif item in (s_alias, t_alias):
            select_cols.append(f"{item}.id AS {item}_id")
            return_cols.append(f"{item}_id")
    if not select_cols:
        return None
    return TranspiledQuery(
        sql=f"SELECT {', '.join(select_cols)} {join}{limit_sql}",
        params=params_list,
        query_type=QueryType.SELECT,
        return_columns=return_cols,
    )


def _build_where(
    cypher: str, alias: str, params: dict[str, Any]
) -> tuple[str, list[Any]]:
    """Extract WHERE conditions from Cypher and build SQL WHERE clause."""
    where_match = re.search(
        r"WHERE\s+(.+?)(?:SET|RETURN|MERGE|CREATE|DELETE|$)",
        cypher,
        re.IGNORECASE | re.DOTALL,
    )
    # ``where_raw`` is empty when there's no explicit WHERE keyword — but the
    # MATCH pattern may still carry an inline ``{id: $id}`` property filter, the
    # form the engine uses for deletes (e.g. ``MATCH (t:Task {id:$id}) DETACH
    # DELETE t``). Returning early here dropped that filter and produced an empty
    # WHERE (``DELETE FROM "Task" WHERE`` → syntax error → swallowed L3 mirror
    # failure → durable row never deleted). The inline-property block below scans
    # the full Cypher, so it must run even without a WHERE clause. (CONCEPT:KG-2.7)
    where_raw = where_match.group(1).strip() if where_match else ""
    sql_parts = []
    values: list[Any] = []

    # Handle CONTAINS patterns
    for m in _CONTAINS.finditer(where_raw):
        col = m.group(2)
        param_name = m.group(3)
        val = params.get(param_name, "")
        sql_parts.append(f'LOWER("{col}") LIKE %s')
        values.append(f"%{val}%")

    # Handle simple equality: n.prop = $param
    for m in re.finditer(rf"{alias}\.(\w+)\s*=\s*\$(\w+)", where_raw):
        col, param_name = m.group(1), m.group(2)
        if any(col in p for p in sql_parts):
            continue
        val = params.get(param_name)
        sql_parts.append(f'"{col}" = %s')
        values.append(val)

    # Handle property match: {id: $id}
    for m in re.finditer(r"\{(\w+)\s*:\s*\$(\w+)\}", cypher):
        col, param_name = m.group(1), m.group(2)
        if any(col in p for p in sql_parts):
            continue
        val = params.get(param_name)
        sql_parts.append(f'"{col}" = %s')
        values.append(val)

    # Handle coalesce
    for m in _COALESCE.finditer(where_raw):
        col, default, op, compare_val = m.group(2), m.group(3), m.group(4), m.group(5)
        sql_op = "!=" if op == "<>" else op
        sql_parts.append(f"COALESCE(\"{col}\", '{default}') {sql_op} '{compare_val}'")

    # Handle IN clause: n.type IN $types
    for m in re.finditer(rf"{alias}\.(\w+)\s+IN\s+\$(\w+)", where_raw):
        col, param_name = m.group(1), m.group(2)
        val = params.get(param_name, [])
        if isinstance(val, list) and val:
            placeholders = ", ".join(["%s"] * len(val))
            sql_parts.append(f'"{col}" IN ({placeholders})')
            values.extend(val)

    # Handle comparison: n.prop < value
    for m in re.finditer(rf"{alias}\.(\w+)\s*(<|>|<=|>=)\s*([\d.]+)", where_raw):
        col, op, val = m.group(1), m.group(2), m.group(3)
        if any(col in p for p in sql_parts):
            continue
        sql_parts.append(f'"{col}" {op} %s')
        values.append(float(val) if "." in val else int(val))

    # Handle status: n.status = 'value'
    for m in re.finditer(rf"{alias}\.(\w+)\s*=\s*'([^']*)'", where_raw):
        col, val = m.group(1), m.group(2)
        if any(col in p for p in sql_parts):
            continue
        sql_parts.append(f'"{col}" = %s')
        values.append(val)

    connector = (
        " AND "
        if " AND " in where_raw.upper()
        else " OR "
        if " OR " in where_raw.upper()
        else " AND "
    )
    return connector.join(sql_parts), values


def _find_id_param(cypher: str, alias: str, params: dict[str, Any]) -> str:
    """Find the parameter name used for an alias's ID in MATCH clauses."""
    m = re.search(rf"\b{alias}\b(?::\w+)?\s*\{{id:\s*\$(\w+)\}}", cypher)
    if m:
        return m.group(1)
    m = re.search(rf"\{{{alias}\w*\s*:\s*\$(\w+)\}}", cypher)
    if m:
        return m.group(1)
    m = re.search(rf"\b{alias}\b\.id\s*=\s*\$(\w+)", cypher)
    if m:
        return m.group(1)
    m = re.search(r"\{id:\s*\$(\w+)\}", cypher)
    if m:
        return m.group(1)
    return "id"


# Columns guaranteed present and identically-typed on EVERY durable node table
# (see PostgreSQLBackend.ensure_label_table). A bare ``SELECT *`` is unsafe across
# a UNION: per-label schema drift (ensure_column / the pgvector ``embedding`` /
# ``tenant_id``) gives tables different widths, so the branches' column counts
# mismatch and Postgres rejects the whole query ("each UNION query must have the
# same number of columns"). Projecting the fixed base set keeps every branch the
# same arity. The full node props still live in the ``properties`` JSONB column.
_UNION_BASE_COLS = '"id", "name", "type", "properties", "created_at"'


def _union_all_tables(tables: set[str], cols: str = "*", where: str = "") -> str:
    """Build a UNION ALL query across all known tables.

    A label-less fan-out (``cols == "*"``) projects the uniform base column set so
    every UNION branch has identical arity across heterogeneous node tables; an
    explicit ``cols`` (specific properties / aggregates) is assumed uniform and
    passes through unchanged.
    """
    if not tables:
        return "SELECT 1 WHERE false"
    select_cols = _UNION_BASE_COLS if cols == "*" else cols
    parts = []
    for tbl in sorted(tables):
        q = f"SELECT {select_cols}, '{tbl}' AS _table_label FROM \"{tbl}\""
        if where:
            q += f" WHERE {where}"
        parts.append(q)
    return " UNION ALL ".join(parts)
