"""Cypher-to-SQL Transpiler for PostgreSQL Backend.

Translates the specific Cypher query patterns generated by the
IntelligenceGraphEngine into PostgreSQL-compatible SQL statements.

This is NOT a general-purpose Cypher parser — it handles the ~15
distinct patterns the engine actually emits via regex matching.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

logger = logging.getLogger(__name__)

# All known node labels from the schema (used for table lookups)
_LABEL_PATTERN = re.compile(r"\((\w+):(\w+)", re.IGNORECASE)
_MATCH_BY_ID = re.compile(
    r"MATCH\s+\((\w+):(\w+)\)\s+WHERE\s+\1\.id\s*=\s*\$(\w+)",
    re.IGNORECASE,
)
_MATCH_ANY_BY_ID = re.compile(
    r"MATCH\s+\((\w+)\)\s+WHERE\s+\1\.id\s*=\s*\$(\w+)",
    re.IGNORECASE,
)
_CREATE_NODE = re.compile(r"CREATE\s+\((\w+):(\w+)\s*\{([^}]+)\}\)", re.IGNORECASE)
_SET_CLAUSE = re.compile(r"SET\s+(.+?)(?:RETURN|$)", re.IGNORECASE | re.DOTALL)
_RETURN_CLAUSE = re.compile(r"RETURN\s+(.+?)$", re.IGNORECASE | re.DOTALL)
_LIMIT_CLAUSE = re.compile(r"LIMIT\s+(\$?\w+)", re.IGNORECASE)
_ORDER_BY_CLAUSE = re.compile(
    r"ORDER\s+BY\s+(.+?)(?:LIMIT|$)", re.IGNORECASE | re.DOTALL
)
_MERGE_REL = re.compile(r"MERGE\s+\((\w+)\)-\[(\w+):(\w+)\]->\((\w+)\)", re.IGNORECASE)
_MATCH_REL = re.compile(
    r"MATCH\s+\((\w+)(?::(\w+))?\s*(?:\{[^}]*\})?\)-\[(\w+)?:?(\w+)?\]->?\((\w+)(?::(\w+))?\s*(?:\{[^}]*\})?\)",
    re.IGNORECASE,
)
_CONTAINS = re.compile(
    r"toLower\((\w+)\.(\w+)\)\s+CONTAINS\s+toLower\(\$(\w+)\)",
    re.IGNORECASE,
)
_LABEL_FUNC = re.compile(r"label\((\w+)\)\s+as\s+(\w+)", re.IGNORECASE)
_COUNT_PATTERN = re.compile(r"count\((\w+)\)\s+as\s+(\w+)", re.IGNORECASE)
_DETACH_DELETE = re.compile(r"DETACH\s+DELETE\s+(\w+)", re.IGNORECASE)
_DELETE = re.compile(r"DELETE\s+(\w+)", re.IGNORECASE)
_COALESCE = re.compile(
    r"coalesce\((\w+)\.(\w+),\s*'([^']*)'\)\s*(<>|=)\s*'([^']*)'",
    re.IGNORECASE,
)


class QueryType(Enum):
    SELECT = "select"
    INSERT = "insert"
    UPDATE = "update"
    DELETE = "delete"
    UPSERT_EDGE = "upsert_edge"
    LABEL_LOOKUP = "label_lookup"
    COUNT = "count"
    UNKNOWN = "unknown"


@dataclass
class TranspiledQuery:
    """Result of transpiling a Cypher query to SQL."""

    sql: str
    params: list[Any] = field(default_factory=list)
    query_type: QueryType = QueryType.UNKNOWN
    return_columns: list[str] = field(default_factory=list)
    target_table: str | None = None
    node_alias: str | None = None


# Edge table name constant
EDGE_TABLE = "kg_edges"


def _param_key_to_positional(
    params: dict[str, Any], keys: list[str]
) -> tuple[list[Any], dict[str, int]]:
    """Convert named params to positional list, returning values and index map."""
    values = []
    index_map = {}
    for k in keys:
        if k.startswith("_"):
            continue
        if k in params:
            values.append(params[k])
            index_map[k] = len(values)
    return values, index_map


def transpile(
    cypher: str,
    params: dict[str, Any] | None = None,
    known_tables: set[str] | None = None,
) -> TranspiledQuery:
    """Transpile a Cypher query into a PostgreSQL SQL statement.

    Args:
        cypher: The Cypher query string from the engine.
        params: Named parameters from the engine.
        known_tables: Set of known table names in the database.

    Returns:
        A TranspiledQuery with the SQL and positional parameters.
    """
    params = params or {}
    known_tables = known_tables or set()
    cypher_stripped = cypher.strip().rstrip(";")

    # Remove internal params
    clean_params = {k: v for k, v in params.items() if not k.startswith("_")}

    # --- Pattern 1: CREATE (n:Label {props}) ---
    m = _CREATE_NODE.search(cypher_stripped)
    if m and cypher_stripped.upper().startswith("CREATE"):
        alias, label, props_str = m.group(1), m.group(2), m.group(3)
        # Parse "key: $param" pairs
        prop_pairs = re.findall(r"(\w+)\s*:\s*\$(\w+)", props_str)
        cols = [p[0] for p in prop_pairs]
        param_keys = [p[1] for p in prop_pairs]
        placeholders = ["%s" for _ in cols]
        values = [clean_params.get(k) for k in param_keys]
        sql = f'INSERT INTO "{label}" ({", ".join(cols)}) VALUES ({", ".join(placeholders)}) ON CONFLICT (id) DO NOTHING'  # nosec B608
        return TranspiledQuery(
            sql=sql, params=values, query_type=QueryType.INSERT, target_table=label
        )

    # --- Pattern 2: MATCH (n:Label) WHERE n.id = $id SET ... RETURN ---
    m_id = _MATCH_BY_ID.search(cypher_stripped)
    m_set = _SET_CLAUSE.search(cypher_stripped)
    if m_id and m_set:
        alias, label, id_param = m_id.group(1), m_id.group(2), m_id.group(3)
        set_str = m_set.group(1).strip()
        # Parse "n.key = $param" pairs
        set_pairs = re.findall(rf"{alias}\.(\w+)\s*=\s*\$(\w+)", set_str)
        if set_pairs:
            set_clauses = [f'"{p[0]}" = %s' for p in set_pairs]
            values = [clean_params.get(p[1]) for p in set_pairs]
            values.append(clean_params.get(id_param))
            sql = f'UPDATE "{label}" SET {", ".join(set_clauses)} WHERE id = %s'  # nosec B608

            # Check for RETURN
            m_ret = _RETURN_CLAUSE.search(cypher_stripped)
            if m_ret:
                ret_str = m_ret.group(1).strip()
                if f"{alias}.id" in ret_str:
                    sql += " RETURNING id"
            return TranspiledQuery(
                sql=sql,
                params=values,
                query_type=QueryType.UPDATE,
                target_table=label,
                node_alias=alias,
            )

    # --- Pattern 3: MATCH (n) WHERE n.id = $id RETURN label(n) as lbl ---
    m_any = _MATCH_ANY_BY_ID.search(cypher_stripped)
    m_label = _LABEL_FUNC.search(cypher_stripped)
    if m_any and m_label:
        alias, id_param = m_any.group(1), m_any.group(2)
        lbl_alias = m_label.group(2)
        id_val = clean_params.get(id_param)
        # Search all known tables for this ID
        if known_tables:
            union_parts = []
            for tbl in sorted(known_tables):
                union_parts.append(
                    f"SELECT '{tbl}' AS {lbl_alias} FROM \"{tbl}\" WHERE id = %s"  # nosec B608
                )
            sql = " UNION ALL ".join(union_parts) + " LIMIT 1"
            values = [id_val] * len(known_tables)
            return TranspiledQuery(
                sql=sql,
                params=values,
                query_type=QueryType.LABEL_LOOKUP,
                return_columns=[lbl_alias],
            )

    # --- Pattern 4: MATCH (n:Label) WHERE ... RETURN n (with filters) ---
    if cypher_stripped.upper().startswith("MATCH"):
        m_label_match = _LABEL_PATTERN.search(cypher_stripped)
        label = m_label_match.group(2) if m_label_match else None
        alias = m_label_match.group(1) if m_label_match else "n"

        # Check for count
        m_cnt = _COUNT_PATTERN.search(cypher_stripped)
        if m_cnt:
            cnt_alias = m_cnt.group(2)
            where_sql, where_vals = _build_where(cypher_stripped, alias, clean_params)
            tbl = f'"{label}"' if label else _union_all_tables(known_tables)
            if label:
                sql = f"SELECT COUNT(*) AS {cnt_alias} FROM {tbl}"  # nosec B608
                if where_sql:
                    sql += f" WHERE {where_sql}"
                return TranspiledQuery(
                    sql=sql,
                    params=where_vals,
                    query_type=QueryType.COUNT,
                    return_columns=[cnt_alias],
                )

        # Check for DETACH DELETE
        m_del = _DETACH_DELETE.search(cypher_stripped) or _DELETE.search(
            cypher_stripped
        )
        if m_del:
            where_sql, where_vals = _build_where(cypher_stripped, alias, clean_params)
            if label:
                sqls = []
                # Delete edges first
                sqls.append(
                    f'DELETE FROM {EDGE_TABLE} WHERE source_id IN (SELECT id FROM "{label}" WHERE {where_sql}) '
                    f'OR target_id IN (SELECT id FROM "{label}" WHERE {where_sql})'  # nosec B608
                )
                sqls.append(f'DELETE FROM "{label}" WHERE {where_sql}')  # nosec B608
                # We return the last statement; caller should handle cascade
                return TranspiledQuery(
                    sql=sqls[-1],
                    params=where_vals,
                    query_type=QueryType.DELETE,
                    target_table=label,
                )

        # Check for MERGE relationship
        m_merge = _MERGE_REL.search(cypher_stripped)
        if m_merge:
            s_alias = m_merge.group(1)
            _r_alias = m_merge.group(2)  # noqa: F841
            rel_type = m_merge.group(3)
            t_alias = m_merge.group(4)
            # Extract source/target IDs from earlier MATCH
            sid_param = _find_id_param(cypher_stripped, s_alias, clean_params)
            tid_param = _find_id_param(cypher_stripped, t_alias, clean_params)
            sid = clean_params.get(sid_param, clean_params.get("sid"))
            tid = clean_params.get(tid_param, clean_params.get("tid"))
            sql = (
                f"INSERT INTO {EDGE_TABLE} (source_id, target_id, rel_type, properties) "
                f"VALUES (%s, %s, %s, %s::jsonb) "
                f"ON CONFLICT (source_id, target_id, rel_type) DO UPDATE SET properties = EXCLUDED.properties"  # nosec B608
            )
            # Collect edge properties
            edge_props = {
                k: v
                for k, v in clean_params.items()
                if k not in ("sid", "tid", "id", "source", "target")
            }
            import json

            return TranspiledQuery(
                sql=sql,
                params=[sid, tid, rel_type, json.dumps(edge_props, default=str)],
                query_type=QueryType.UPSERT_EDGE,
            )

        # Standard SELECT with filters
        where_sql, where_vals = _build_where(cypher_stripped, alias, clean_params)

        # Determine return columns
        m_ret = _RETURN_CLAUSE.search(cypher_stripped)
        select_cols = "*"
        if m_ret:
            ret_raw = m_ret.group(1).strip()
            # Remove ORDER BY / LIMIT from return
            ret_raw = re.sub(r"ORDER\s+BY.*$", "", ret_raw, flags=re.IGNORECASE).strip()
            ret_raw = re.sub(r"LIMIT\s+.*$", "", ret_raw, flags=re.IGNORECASE).strip()
            if ret_raw == alias:
                select_cols = "*"
            elif f"{alias}." in ret_raw:
                # Extract specific columns
                col_matches = re.findall(rf"{alias}\.(\w+)", ret_raw)
                if col_matches:
                    select_cols = ", ".join(f'"{c}"' for c in col_matches)

        if label:
            sql = f'SELECT {select_cols} FROM "{label}"'  # nosec B608
        else:
            # No label — search all tables
            sql = _union_all_tables(known_tables, select_cols)

        if where_sql:
            if label:
                sql += f" WHERE {where_sql}"
            else:
                # For UNION ALL, wrap each with WHERE
                sql = _union_all_tables(known_tables, select_cols, where_sql)

        # ORDER BY
        m_order = _ORDER_BY_CLAUSE.search(cypher_stripped)
        if m_order and label:
            order_raw = m_order.group(1).strip()
            order_raw = re.sub(rf"{alias}\.", "", order_raw)
            sql += f" ORDER BY {order_raw}"

        # LIMIT
        m_limit = _LIMIT_CLAUSE.search(cypher_stripped)
        if m_limit:
            limit_val = m_limit.group(1)
            if limit_val.startswith("$"):
                where_vals.append(clean_params.get(limit_val[1:], 100))
                sql += " LIMIT %s"
            else:
                sql += f" LIMIT {limit_val}"

        return TranspiledQuery(
            sql=sql,
            params=where_vals,
            query_type=QueryType.SELECT,
            target_table=label,
            node_alias=alias,
        )

    # Fallback: unknown pattern
    logger.warning("Cypher transpiler: unrecognized pattern: %.200s", cypher_stripped)
    return TranspiledQuery(sql="SELECT 1 WHERE false", query_type=QueryType.UNKNOWN)


def _build_where(
    cypher: str, alias: str, params: dict[str, Any]
) -> tuple[str, list[Any]]:
    """Extract WHERE conditions from Cypher and build SQL WHERE clause."""
    where_match = re.search(
        r"WHERE\s+(.+?)(?:SET|RETURN|MERGE|CREATE|DELETE|$)",
        cypher,
        re.IGNORECASE | re.DOTALL,
    )
    if not where_match:
        return "", []

    where_raw = where_match.group(1).strip()
    sql_parts = []
    values: list[Any] = []

    # Handle CONTAINS patterns
    for m in _CONTAINS.finditer(where_raw):
        col = m.group(2)
        param_name = m.group(3)
        val = params.get(param_name, "")
        sql_parts.append(f'LOWER("{col}") LIKE %s')
        values.append(f"%{val}%")

    # Handle simple equality: n.prop = $param
    for m in re.finditer(rf"{alias}\.(\w+)\s*=\s*\$(\w+)", where_raw):
        col, param_name = m.group(1), m.group(2)
        if any(col in p for p in sql_parts):
            continue
        val = params.get(param_name)
        sql_parts.append(f'"{col}" = %s')
        values.append(val)

    # Handle property match: {id: $id}
    for m in re.finditer(r"\{(\w+)\s*:\s*\$(\w+)\}", cypher):
        col, param_name = m.group(1), m.group(2)
        if any(col in p for p in sql_parts):
            continue
        val = params.get(param_name)
        sql_parts.append(f'"{col}" = %s')
        values.append(val)

    # Handle coalesce
    for m in _COALESCE.finditer(where_raw):
        col, default, op, compare_val = m.group(2), m.group(3), m.group(4), m.group(5)
        sql_op = "!=" if op == "<>" else op
        sql_parts.append(f"COALESCE(\"{col}\", '{default}') {sql_op} '{compare_val}'")

    # Handle IN clause: n.type IN $types
    for m in re.finditer(rf"{alias}\.(\w+)\s+IN\s+\$(\w+)", where_raw):
        col, param_name = m.group(1), m.group(2)
        val = params.get(param_name, [])
        if isinstance(val, list) and val:
            placeholders = ", ".join(["%s"] * len(val))
            sql_parts.append(f'"{col}" IN ({placeholders})')
            values.extend(val)

    # Handle comparison: n.prop < value
    for m in re.finditer(rf"{alias}\.(\w+)\s*(<|>|<=|>=)\s*([\d.]+)", where_raw):
        col, op, val = m.group(1), m.group(2), m.group(3)
        if any(col in p for p in sql_parts):
            continue
        sql_parts.append(f'"{col}" {op} %s')
        values.append(float(val) if "." in val else int(val))

    # Handle status: n.status = 'value'
    for m in re.finditer(rf"{alias}\.(\w+)\s*=\s*'([^']*)'", where_raw):
        col, val = m.group(1), m.group(2)
        if any(col in p for p in sql_parts):
            continue
        sql_parts.append(f'"{col}" = %s')
        values.append(val)

    connector = (
        " AND "
        if " AND " in where_raw.upper()
        else " OR "
        if " OR " in where_raw.upper()
        else " AND "
    )
    return connector.join(sql_parts), values


def _find_id_param(cypher: str, alias: str, params: dict[str, Any]) -> str:
    """Find the parameter name used for an alias's ID in MATCH clauses."""
    m = re.search(rf"\{{{alias}\w*\s*:\s*\$(\w+)\}}", cypher)
    if m:
        return m.group(1)
    m = re.search(rf"{alias}\.id\s*=\s*\$(\w+)", cypher)
    if m:
        return m.group(1)
    m = re.search(r"\{id:\s*\$(\w+)\}", cypher)
    if m:
        return m.group(1)
    return "id"


def _union_all_tables(tables: set[str], cols: str = "*", where: str = "") -> str:
    """Build a UNION ALL query across all known tables."""
    if not tables:
        return "SELECT 1 WHERE false"
    parts = []
    for tbl in sorted(tables):
        q = f"SELECT {cols}, '{tbl}' AS _table_label FROM \"{tbl}\""  # nosec B608
        if where:
            q += f" WHERE {where}"
        parts.append(q)
    return " UNION ALL ".join(parts)
