#!/usr/bin/env python3
"""OKF-CIS RDF generator (CONCEPT:AU-OS.governance.concept-2) — populate the dead governance model.

Reads the curated migration plan and emits ``ontology_concepts.ttl`` under the
canonical ``http://knuckles.team/kg#`` namespace, populating the classes that
``ontology.ttl`` (OS-5.76) declares but nothing filled:

* one ``:GovernedConcept`` individual per concept, with ``:dottedId`` and a
  ``:flatId`` for each legacy id it absorbs (a formerly-collided id like ``KG-2.7``
  appears as a ``:flatId`` on several distinct concepts — disambiguation in RDF);
* ``:partOf`` mereology concept -> domain -> pillar -> repo-scheme
  (``okf_part_of_edges``), and the matching ``skos:broader``;
* the 6 pillars as SHARED ``skos:Concept`` top nodes (no slug) so every repo's
  ``*-KG.*`` federates onto one ``.../pillar/KG`` node — cross-repo linking;
* each repo as a ``skos:ConceptScheme``.

The IRI is deterministic (``concept_hierarchy.concept_iri``) and mirrors the OKF
bundle path exactly. Consumed by the existing owlready2 ``_preload`` glob +
``check_ontology`` gate — no new loader.
"""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from agent_utilities.governance import concept_hierarchy as ch  # noqa: E402

NS = "http://knuckles.team/kg#"
HDR = """\
@prefix : <http://knuckles.team/kg#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix dct: <http://purl.org/dc/terms/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

<http://knuckles.team/kg/concepts> a owl:Ontology ;
    rdfs:label "OKF-CIS governed concepts (generated)" ;
    rdfs:comment "CONCEPT:AU-OS.governance.concept-2 — generated by scripts/build_concept_rdf.py. DO NOT EDIT." .
"""


def _lit(s: str) -> str:
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def build(plan_path: Path) -> str:
    plan = yaml.safe_load(plan_path.read_text(encoding="utf-8"))
    entries = plan["entries"]

    # legacy ids per new concept (from the plan: each entry's old_id)
    flat_ids: dict[str, set[str]] = defaultdict(set)
    parsed: dict[str, ch.OkfConceptId] = {}
    for e in entries:
        nid = e["new_id"]
        flat_ids[nid].add(e["old_id"])
        if nid not in parsed:
            parsed[nid] = ch.parse_okf_id(nid)

    lines = [HDR]
    pillars_used: set[str] = set()
    schemes: set[str] = set()
    domains: set[str] = set()

    for nid, p in sorted(parsed.items()):
        pillars_used.add(p.pillar)
        schemes.add(p.slug)
        domains.add(p.domain_iri)
        lines.append(f"<{p.iri}> a :GovernedConcept ;")
        lines.append(f"    :dottedId {_lit(nid)} ;")
        for fid in sorted(flat_ids[nid]):
            lines.append(f"    :flatId {_lit(fid)} ;")
        lines.append(f"    skos:prefLabel {_lit(p.concept.replace('-', ' '))} ;")
        lines.append(f"    skos:inScheme <{p.scheme_iri}> ;")
        lines.append(f"    skos:broader <{p.domain_iri}> ;")
        lines.append(f"    :partOf <{p.domain_iri}> .")

    # domain nodes -> pillar
    for diri in sorted(domains):
        # diri = .../concept/<SLUG>/<PILLAR>/<domain>
        slug, pillar, dom = diri.rsplit("/", 3)[1:]
        piri = f"{ch.PILLAR_IRI_BASE}/{pillar}"
        lines.append(f"<{diri}> a skos:Concept ;")
        lines.append(f"    skos:prefLabel {_lit(dom)} ;")
        lines.append(f"    skos:broader <{piri}> ;")
        lines.append(f"    :partOf <{piri}> .")

    # shared pillar top-concepts (no slug — federated across all repos)
    for pil in sorted(pillars_used):
        piri = f"{ch.PILLAR_IRI_BASE}/{pil}"
        lines.append(f"<{piri}> a :Pillar, skos:Concept ;")
        lines.append(f"    skos:prefLabel {_lit(pil)} .")

    # repo schemes
    for slug in sorted(schemes):
        siri = f"{ch.SCHEME_IRI_BASE}/{slug}"
        lines.append(f"<{siri}> a skos:ConceptScheme ;")
        lines.append(f"    skos:prefLabel {_lit(slug)} .")

    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--plan", required=True)
    ap.add_argument("--out", required=True, help="output ontology_concepts.ttl path")
    args = ap.parse_args()
    ttl = build(Path(args.plan))
    Path(args.out).write_text(ttl, encoding="utf-8")
    n_gc = ttl.count("a :GovernedConcept")
    n_pil = ttl.count("a :Pillar")
    n_sch = ttl.count("a skos:ConceptScheme")
    print(f"wrote {args.out}: {n_gc} GovernedConcepts, {n_pil} shared pillars, "
          f"{n_sch} schemes, {len(ttl)} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
