#!/usr/bin/env python3
"""Guardrail -- generated lock artifacts must mirror pyproject.toml's version.

CONCEPT: C2/B6 (plans/graph-os-completion-program/designs/REMAINING-ISSUES-DESIGNS.md).

Two related, previously-uncaught drift classes across the fleet:

  B6 -- a repo's OWN `uv.lock` entry (the self-package's pinned `version =`)
        silently falls behind `pyproject.toml` after a version bump, because
        `bump2version`/`bump-my-version` only rewrites files it is explicitly
        told about (`.bumpversion.cfg`), and `uv.lock` is never one of them --
        it is regenerated by `uv lock`, not text-substituted.

  C2 -- a repo's `requirements.txt` (a `uv export`/`uv pip compile`-generated
        second lockfile some repos ship for plain-`pip install` consumers)
        pins a dependency version/range that no longer matches what
        `pyproject.toml` itself declares for that same dependency -- most
        concretely, an `agent-utilities` floor that drifted stale enough to be
        unpublishable/unsatisfiable while nothing caught it, because the
        fleet's version/lockfile edict named `uv.lock` only.

Usage: python3 scripts/check_lockfile_version_mirrors.py [ROOT]   (default: repo root)
Exit 0 = mirrors agree (or the artifact is absent -- not every repo ships both).
Exit 1 = a generated lock artifact disagrees with pyproject.toml.
"""

from __future__ import annotations

import re
import sys
import tomllib
from pathlib import Path
from typing import Any

from packaging.requirements import InvalidRequirement, Requirement
from packaging.specifiers import SpecifierSet
from packaging.utils import canonicalize_name

ROOT_DEFAULT = Path(__file__).resolve().parents[1]
# Comment/continuation lines a `uv export`/`uv pip compile` output intersperses
# between real requirement lines -- never requirements themselves.
_SKIP_LINE = re.compile(r"^\s*(#|$)")


def _project_version(pyproject: dict[str, Any], root: Path) -> str | None:
    """The version this repo's own release surfaces must mirror.

    Prefers a literal `[project].version` string (the common case in this
    fleet). Falls back to `.bumpversion.cfg`'s `current_version` for the rare
    repo using a dynamic version -- that file is itself the bump authority, so
    it is a legitimate fallback source, not a duplicate one.
    """
    version = pyproject.get("project", {}).get("version")
    if isinstance(version, str) and version:
        return version
    cfg = root / ".bumpversion.cfg"
    try:
        text = cfg.read_text(encoding="utf-8")
    except OSError:
        return None
    for line in text.splitlines():
        if line.strip().startswith("current_version"):
            return line.split("=", 1)[1].strip()
    return None


def _pyproject_requirements(pyproject: dict[str, Any]) -> dict[str, list[SpecifierSet]]:
    """Every dependency `pyproject.toml` itself declares, by canonical name.

    Scoped to `[project.dependencies]` -- the surface `requirements.txt` is
    meant to mirror -- not the optional-dependency extras, which routinely
    carry a wider or narrower range for a dev/test-only consumer and are not
    what a plain `pip install -r requirements.txt` represents.
    """
    declared: dict[str, list[SpecifierSet]] = {}
    for raw in pyproject.get("project", {}).get("dependencies", []) or []:
        try:
            requirement = Requirement(raw)
        except InvalidRequirement:
            continue
        declared.setdefault(canonicalize_name(requirement.name), []).append(
            requirement.specifier
        )
    return declared


def _check_uv_lock(root: Path, self_name: str, version: str) -> list[str]:
    lock_path = root / "uv.lock"
    if not lock_path.is_file():
        return []
    try:
        lock = tomllib.loads(lock_path.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError) as exc:
        return [f"uv.lock: unreadable/invalid TOML ({exc})"]
    self_packages = [
        package
        for package in lock.get("package", [])
        if canonicalize_name(str(package.get("name", ""))) == self_name
    ]
    if len(self_packages) != 1:
        # Not every checkout has a self-referencing lock entry (e.g. one built
        # before `uv lock` ever ran here); that is a different defect than a
        # version mismatch and out of scope for this gate.
        return []
    locked_version = self_packages[0].get("version")
    if locked_version != version:
        return [
            f"uv.lock: self-package version {locked_version!r} != "
            f"pyproject.toml version {version!r}"
        ]
    return []


def _check_requirements_txt(
    root: Path, declared: dict[str, list[SpecifierSet]]
) -> list[str]:
    req_path = root / "requirements.txt"
    if not req_path.is_file() or not declared:
        return []
    findings: list[str] = []
    try:
        lines = req_path.read_text(encoding="utf-8").splitlines()
    except OSError as exc:
        return [f"requirements.txt: unreadable ({exc})"]
    for raw_line in lines:
        if _SKIP_LINE.match(raw_line):
            continue
        # `uv pip compile`/`uv export` append a same-line `# via ...`
        # provenance comment to real requirement lines -- strip it before
        # parsing, it is not part of the requirement.
        line = raw_line.split(" #", 1)[0].strip()
        if not line:
            continue
        try:
            requirement = Requirement(line)
        except InvalidRequirement:
            continue
        name = canonicalize_name(requirement.name)
        pyproject_specs = declared.get(name)
        if pyproject_specs is None:
            continue  # transitive dep or one pyproject.toml doesn't declare directly
        req_spec = requirement.specifier
        pinned = [c for c in req_spec if c.operator == "=="]
        if pinned:
            pinned_version = pinned[0].version
            if not all(spec.contains(pinned_version) for spec in pyproject_specs):
                findings.append(
                    f"requirements.txt: {requirement.name} pinned to "
                    f"{pinned_version!r}, which does not satisfy pyproject.toml's "
                    f"{' / '.join(str(spec) for spec in pyproject_specs)}"
                )
            continue
        # Not a pin: this line is expected to mirror pyproject.toml's own
        # range exactly (that is what "generated from pyproject.toml"
        # means for a range dependency, as opposed to a pip-compile pin).
        if str(req_spec) and all(
            str(req_spec) != str(spec) for spec in pyproject_specs
        ):
            findings.append(
                f"requirements.txt: {requirement.name} declares {req_spec!s}, "
                f"pyproject.toml declares "
                f"{' / '.join(str(spec) for spec in pyproject_specs)}"
            )
    return findings


def validate(root: Path) -> list[str]:
    pyproject_path = root / "pyproject.toml"
    try:
        pyproject = tomllib.loads(pyproject_path.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError) as exc:
        return [f"pyproject.toml: unreadable/invalid TOML ({exc})"]
    version = _project_version(pyproject, root)
    if not version:
        return ["pyproject.toml: no resolvable [project].version"]
    self_name = canonicalize_name(str(pyproject.get("project", {}).get("name", "")))
    findings = list(_check_uv_lock(root, self_name, version))
    findings.extend(_check_requirements_txt(root, _pyproject_requirements(pyproject)))
    return findings


def main() -> int:
    root = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT_DEFAULT
    findings = validate(root)
    if findings:
        print("lockfile version mirrors: FAIL", file=sys.stderr)
        for finding in findings:
            print(f"  - {finding}", file=sys.stderr)
        return 1
    print("lockfile version mirrors: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
