#!/usr/bin/env python3
"""Gate: ``genesis.yaml`` is in sync with its generator.

``genesis.yaml`` is generated by ``scripts/gen_genesis_manifest.py`` from the MCP
fleet registry + the deployment profiles/recipes. This check regenerates it in
memory and fails if the committed file drifts — the same contract
``check_concepts.py`` enforces for the concept registry.

Run:  python scripts/check_genesis_manifest.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import gen_genesis_manifest as gen  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "genesis.yaml"


def main() -> int:
    if not MANIFEST.exists():
        print(
            "FAIL: genesis.yaml is missing. Run "
            "`python scripts/gen_genesis_manifest.py --out genesis.yaml`.",
            file=sys.stderr,
        )
        return 1
    expected = gen.render()
    actual = MANIFEST.read_text(encoding="utf-8")
    if expected != actual:
        print(
            "FAIL: genesis.yaml is out of date with its sources. Regenerate:\n"
            "  python scripts/gen_genesis_manifest.py --out genesis.yaml",
            file=sys.stderr,
        )
        return 1
    print("OK: genesis.yaml is in sync with gen_genesis_manifest.py.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
