#!/usr/bin/env python3
"""Gate: ``genesis.yaml`` is in sync with its generator.

``genesis.yaml`` is generated by ``scripts/gen_genesis_manifest.py`` from the MCP
fleet registry + the deployment profiles/recipes. This check regenerates it in
memory and fails if the committed file drifts — the same contract
``check_concepts.py`` enforces for the concept registry.

Run:  python scripts/check_genesis_manifest.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import gen_genesis_manifest as gen  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "genesis.yaml"


def main() -> int:
    if not MANIFEST.exists():
        print(
            "FAIL: genesis.yaml is missing. Run "
            "`python scripts/gen_genesis_manifest.py --out genesis.yaml`.",
            file=sys.stderr,
        )
        return 1
    expected = gen.render()
    actual = MANIFEST.read_text(encoding="utf-8")
    if expected != actual:
        print(
            "FAIL: genesis.yaml is out of date with its sources. Regenerate:\n"
            "  python scripts/gen_genesis_manifest.py --out genesis.yaml",
            file=sys.stderr,
        )
        return 1
    manifest = gen.build()
    if "engine_tiers" in manifest or "engine_tier" in actual:
        print(
            "FAIL: genesis must select only an engine deployment shape; alternate "
            "engine artifacts are forbidden.",
            file=sys.stderr,
        )
        return 1
    profiles = manifest.get("profiles", {})
    if not profiles or any(
        profile.get("engine") not in {"autostart", "container", "remote"}
        for profile in profiles.values()
    ):
        print(
            "FAIL: every genesis profile must select a supported full-engine deployment shape.",
            file=sys.stderr,
        )
        return 1
    engine = manifest.get("engine", {})
    if engine.get("version") != "epistemic-graph[full]>=2.23.1,<3.0.0":
        print("FAIL: genesis does not require the approved full engine.", file=sys.stderr)
        return 1
    forbidden = ("agent-utilities[engine]", "pi-tier", "pi-max", "lean tier")
    if any(token in actual for token in forbidden):
        print("FAIL: genesis contains a retired engine artifact contract.", file=sys.stderr)
        return 1
    print("OK: genesis.yaml is in sync with gen_genesis_manifest.py.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
