#!/usr/bin/env python3
"""Regenerate AGENTS.md and the separate project-structure reference.

The concise contributor contract lives in ``AGENTS.head.md`` and is copied to
``AGENTS.md`` without an appended inventory. A pruned tracked-file tree is
generated separately at ``docs/project_structure.md`` so repository growth does
not inflate the instruction surface every agent loads.

Run:  python scripts/gen_agents_md.py
"""

from __future__ import annotations

import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HEAD_PATH = ROOT / "AGENTS.head.md"
OUT_PATH = ROOT / "AGENTS.md"

# Keep the generated inventory separate from the concise contributor contract.
PROJECT_STRUCTURE_PATH = ROOT / "docs" / "project_structure.md"

# Directories that must never appear in the generated tree.
EXCLUDE_DIRS = {
    ".hypothesis",
    ".venv",
    "venv",
    "node_modules",
    "target",
    "__pycache__",
    ".git",
    ".ruff_cache",
    ".mypy_cache",
    ".pytest_cache",
    ".pytest_tmp",
    ".tmp",
    ".agent_data",
    ".agent",
    ".agents",
    ".cache",
}

# Any directory with more than this many direct children is summarized.
MAX_ENTRIES = 40
# Maximum recursion depth for the tree (keeps output bounded).
MAX_DEPTH = 3


def _tracked_index(root: Path) -> tuple[set[str], set[str]]:
    """Return tracked files and directories for a privacy-safe project tree."""
    try:
        result = subprocess.run(
            ["git", "-C", str(root), "ls-files", "-z"],
            check=True,
            capture_output=True,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        raise RuntimeError(
            "tracked project tree requires a readable git index"
        ) from exc

    files = {
        raw.decode("utf-8", errors="strict")
        for raw in result.stdout.split(b"\0")
        if raw
    }
    directories: set[str] = set()
    for name in files:
        parent = Path(name).parent
        while parent != Path("."):
            directories.add(parent.as_posix())
            parent = parent.parent
    return files, directories


TRACKED_FILES, TRACKED_DIRS = _tracked_index(ROOT)


def _children(path: Path) -> list[Path]:
    try:
        entries = list(path.iterdir())
    except (PermissionError, OSError):
        return []
    tracked: list[Path] = []
    for entry in entries:
        relative = entry.relative_to(ROOT).as_posix()
        if entry.is_dir() and relative in TRACKED_DIRS:
            tracked.append(entry)
        elif entry.is_file() and relative in TRACKED_FILES:
            tracked.append(entry)
    return sorted(tracked, key=lambda p: (p.is_file(), p.name.lower()))


def _render_tree(path: Path, prefix: str, depth: int, lines: list[str]) -> None:
    if depth > MAX_DEPTH:
        return
    entries = [e for e in _children(path) if e.name not in EXCLUDE_DIRS]
    for i, entry in enumerate(entries):
        is_last = i == len(entries) - 1
        connector = "└── " if is_last else "├── "
        if entry.is_dir():
            child_entries = [c for c in _children(entry) if c.name not in EXCLUDE_DIRS]
            if len(child_entries) > MAX_ENTRIES:
                lines.append(
                    f"{prefix}{connector}{entry.name}/ ({len(child_entries)} entries)"
                )
                continue
            lines.append(f"{prefix}{connector}{entry.name}/")
            if depth < MAX_DEPTH:
                extension = "    " if is_last else "│   "
                _render_tree(entry, prefix + extension, depth + 1, lines)
        else:
            lines.append(f"{prefix}{connector}{entry.name}")


def project_tree_section() -> str:
    lines: list[str] = []
    _render_tree(ROOT, "", 1, lines)
    body = "\n".join(lines)
    return (
        "## Project Structure (generated)\n\n"
        "_Auto-generated by `scripts/gen_agents_md.py`. "
        "Only version-controlled paths are included; large directories are summarized._\n\n"
        "```text\n" + body + "\n```\n"
    )


def build() -> str:
    """Return the concise contributor contract exactly as authored."""
    return HEAD_PATH.read_text(encoding="utf-8").rstrip() + "\n"


def build_project_structure_doc() -> str:
    header = (
        "# Project Structure\n\n"
        "_Auto-generated by `scripts/gen_agents_md.py` — DO NOT EDIT by hand, run "
        "`python scripts/gen_agents_md.py` to regenerate. Only version-controlled "
        "paths are included and large directories are summarized. Contributor "
        "instructions remain in [`AGENTS.md`](../AGENTS.md)._\n\n"
    )
    lines: list[str] = []
    _render_tree(ROOT, "", 1, lines)
    body = "\n".join(lines)
    return header + "```text\n" + body + "\n```\n"


def main() -> None:
    content = build()
    # Exactly one trailing newline so the end-of-file-fixer hook is a no-op.
    content = content.rstrip("\n") + "\n"
    OUT_PATH.write_text(content, encoding="utf-8")
    size = len(content.encode("utf-8"))
    has_hypothesis = ".hypothesis" in content
    print(
        f"Wrote {OUT_PATH.relative_to(ROOT)}: {size} bytes "
        f"({size / 1024:.1f} KiB). .hypothesis present: {has_hypothesis}"
    )

    tree_content = build_project_structure_doc()
    tree_content = tree_content.rstrip("\n") + "\n"
    PROJECT_STRUCTURE_PATH.write_text(tree_content, encoding="utf-8")
    tree_size = len(tree_content.encode("utf-8"))
    print(
        f"Wrote {PROJECT_STRUCTURE_PATH.relative_to(ROOT)}: {tree_size} bytes "
        f"({tree_size / 1024:.1f} KiB)."
    )


if __name__ == "__main__":
    main()
