#!/usr/bin/env python3
"""Regenerate AU's session-scope allowlist from the EG scope registry (IDM-05).

epistemic-graph publishes every scope it (or a domain app) authorizes, with its
class, as ``epistemic_graph/contract/scopes.json`` (generated by EG's
``gen_contract`` beside the capability ledger). The scopes a verified identity
may project into a GraphSession are exactly that registry -- this script renders
it into ``agent_utilities/security/scope_registry.py``, replacing the
hand-maintained exact-scope list. A scope EG does not register never reaches a
session; a scope EG adds reaches it after one regeneration, never by hand.

Usage::

    python scripts/gen_scope_registry.py --write
    python scripts/gen_scope_registry.py --check
    python scripts/gen_scope_registry.py --write --source /path/to/scopes.json
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from importlib.resources import files
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "agent_utilities" / "security" / "scope_registry.py"
CLASSES = ("user", "domain", "service-only", "approver", "admin")


def installed_registry_bytes() -> bytes:
    """The registry shipped in the installed ``epistemic_graph`` package."""
    return files("epistemic_graph").joinpath("contract", "scopes.json").read_bytes()


def render(source: bytes) -> str:
    """The generated module for one registry document (deterministic)."""
    registry = json.loads(source)
    entries = sorted(registry["scopes"], key=lambda entry: entry["scope"])
    unknown = sorted({entry["class"] for entry in entries} - set(CLASSES))
    if unknown:
        raise ValueError(f"unknown scope classes in the EG registry: {unknown}")
    digest = hashlib.sha256(source).hexdigest()
    lines = [
        '"""GENERATED by scripts/gen_scope_registry.py from the EG scope registry.',
        "",
        "DO NOT EDIT: regenerate with ``python scripts/gen_scope_registry.py --write``.",
        "The source is ``epistemic_graph/contract/scopes.json`` (IDM-05); the",
        "class rules it carries are enforced by the EG identity store.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "EG_SCOPE_REGISTRY_SHA256 = (",
        f'    "{digest}"',
        ")",
        "",
        "#: scope -> class (user | domain | service-only | approver | admin).",
        "SCOPE_CLASSES: dict[str, str] = {",
    ]
    lines += [f'    "{entry["scope"]}": "{entry["class"]}",' for entry in entries]
    lines += [
        "}",
        "",
        "#: approver-class scope -> the one built-in group that confers it.",
        "APPROVER_GROUPS: dict[str, str] = {",
    ]
    lines += [
        f'    "{entry["scope"]}": "{entry["approver_group"]}",'
        for entry in entries
        if entry.get("approver_group")
    ]
    lines += [
        "}",
        "",
        "#: Every registered scope: what a verified identity may project into a",
        "#: GraphSession.",
        "SESSION_SCOPES: frozenset[str] = frozenset(SCOPE_CLASSES)",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    parser.add_argument(
        "--source", type=Path, help="a scopes.json (default: installed EG)"
    )
    args = parser.parse_args(argv)
    source = args.source.read_bytes() if args.source else installed_registry_bytes()
    rendered = render(source)
    if args.write:
        TARGET.write_text(rendered, encoding="utf-8")
        return 0
    current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
    if current != rendered:
        print(
            f"{TARGET.relative_to(ROOT)} is stale: run scripts/gen_scope_registry.py --write"
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
