#!/usr/bin/env python3
"""Generate ``genesis.yaml`` — the single index an agent loops to self-deploy.

``genesis.yaml`` is the machine-readable contract behind the one-link deploy: an
agent (or ``scripts/install.sh``) reads it to pick a profile, run the host
preflight, install, then wire the MCP fleet and any chosen UI components. It
**composes** sources that already exist rather than duplicating them:

* the MCP fleet + per-service profiles come from ``deploy/mcp-fleet.registry.yml``
  (itself generated by ``gen_mcp_fleet_registry.py``);
* the deployment profiles mirror ``agent_utilities.deployment.config_generator.PROFILES``
  and the ``docs/recipes/*`` runbooks;
* the preflight describes ``agent-utilities-doctor --preflight``;
* the IDE targets mirror the ``install-skills`` / ``mcp-installer`` tool sets.

Because it is generated, drift is caught by ``scripts/check_genesis_manifest.py``
(a CI gate) — never hand-edit ``genesis.yaml``.

Usage:
    python scripts/gen_genesis_manifest.py --out genesis.yaml
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "deploy" / "mcp-fleet.registry.yml"
RECIPES = ROOT / "docs" / "recipes"

# Deployment profiles — mirror config_generator.PROFILES (tiny|single-node-prod|enterprise).
# Kept here (not imported) so the generator runs without importing the package.
PROFILES_META = {
    "tiny": {
        "summary": "zero-infra, all-local (laptop / Raspberry Pi) — homelab quick start",
        "docker": False,
        "secrets": "dotenv",
        "servers": "none",
        "skill": "agent-utilities-deployment",
        # Step 0 run-plan defaults (the operator overrides only the exceptions).
        "orchestrator": "docker-compose",
        "install_mode": "deploy-baremetal",
        "idp": "none",
        "ontology_host": "local",
    },
    "single-node-prod": {
        "summary": "one durable, secured host (Postgres/pg-age) + the core MCP connectors",
        "docker": True,
        "secrets": "openbao-or-dotenv",
        "servers": "core",
        "skill": "agent-utilities-deployment",
        "orchestrator": "docker-swarm",
        "install_mode": "deploy-container",
        "idp": "keycloak",
        "ontology_host": "local",
    },
    "enterprise": {
        "summary": "multi-host Docker Swarm, full integration (Vault/SSO/DNS/ingress/observability + all connectors)",
        "docker": True,
        "secrets": "openbao",
        "servers": "all",
        "skill": "agent-os-genesis",
        # Enterprises default to Kubernetes (Step 0 note).
        "orchestrator": "kubernetes",
        "install_mode": "deploy-container",
        "idp": "keycloak",
        "ontology_host": "stardog",
    },
}

# Step 0 adaptive run-plan axes — the choices the genesis questionnaire offers per
# capability/connector. Profiles seed the defaults above; these are the allowed values.
RUN_PLAN = {
    "actions": ["deploy-container", "deploy-baremetal", "use-existing", "skip"],
    "orchestrators": [
        "docker-compose",
        "docker-swarm",
        "podman",
        "podman-compose",
        "kubernetes",
    ],
    "podman_modes": ["rootful", "rootless"],
    "idp": ["keycloak", "okta", "other-oidc", "none"],
    "secrets_store": ["vault", "env"],
    "ontology_hosts": ["stardog", "apache-jena", "local"],
    "install_modes": ["deploy-container", "deploy-baremetal", "use-existing", "skip"],
    # prod = PyPI image / uvx; dev = editable: `pip/uv install -e` (baremetal) OR the
    # package's compose.dev.yml source-mounted container (edits live on restart).
    "install_variants": ["prod", "dev"],
    # Agent->user messaging (CONCEPT:ECO-4.0). channels = MESSAGING_ENABLED_BACKENDS;
    # reach_mode last-active works today, broadcast fans out to all (engine fan-out).
    "messaging": {
        "channels": [
            "slack",
            "teams",
            "telegram",
            "mattermost",
            "discord",
            "whatsapp",
            "matrix",
            "signal",
        ],
        "reach_modes": ["last-active", "broadcast"],
    },
    # Single-package skill-guided deploy: genesis with a one-item run plan; the entry
    # point each agents/* README references. Reuses the connector catalog + install
    # modes/variants + vault_sync.
    "single_package_deploy": {
        "invoke": "deploy <package> with agent-os-genesis",
        "catalog": "universal-skills agent-os-genesis references/connector-catalog.md",
    },
    "provisioner_by_orchestrator": {
        "docker-swarm": "swarm-mesh-provisioner",
        "kubernetes": "kubernetes-mesh-provisioner",
        "podman": "podman-mesh-provisioner",
        "podman-compose": "podman-mesh-provisioner",
        "docker-compose": "docker-compose-operator",
    },
}

# Opt-in UI components — each is preflighted before it is wired (see preflight.py).
COMPONENTS = {
    "agent-terminal-ui": {
        "connect": "http",
        "deps": ["python>=3.11"],
        "container": True,
        "note": "thin Textual TUI over the gateway; many fit on a Pi-class node",
    },
    "agent-webui": {
        "connect": "http",
        "deps": ["node>=18", "pnpm>=10"],
        "container": "needs-dockerfile",
        "note": "React/Vite SPA + FastAPI; talks to the gateway over /api/*",
    },
    "geniusbot": {
        "connect": "import",
        "deps": ["python>=3.11", "PySide6/Qt6", "libGL", "libxcb", "display"],
        "container": False,
        "note": "PySide6 desktop app; needs an X11/Wayland display — not headless/cloud",
    },
}

# IDE / agent-tool targets the bootstrap can wire skills + MCP config into
# (`install-skills --all-detected` / `mcp-installer --all-detected`). Mirrors the
# union of those installers' TOOL_PATHS.
IDE_TARGETS = [
    "claude",
    "claude-desktop",
    "windsurf",
    "opencode",
    "openclaw",
    "antigravity",
    "codex",
    "devin",
    "cursor",
    "zed",
    "agent-utilities",
    "agent-terminal-ui",
]


def _load_registry() -> list[dict]:
    if not REGISTRY.exists():
        print(
            f"error: {REGISTRY} missing — run gen_mcp_fleet_registry.py",
            file=sys.stderr,
        )
        raise SystemExit(2)
    data = yaml.safe_load(REGISTRY.read_text(encoding="utf-8")) or {}
    return data.get("services", [])


def build() -> dict:
    services = _load_registry()
    core = sorted(
        s["name"] for s in services if "single-node-prod" in (s.get("profiles") or [])
    )
    profiles = {}
    for name, meta in PROFILES_META.items():
        recipe = RECIPES / f"{name}.md"
        profiles[name] = {
            "summary": meta["summary"],
            "recipe": recipe.relative_to(ROOT).as_posix() if recipe.exists() else None,
            "docker": meta["docker"],
            "secrets": meta["secrets"],
            "servers": meta["servers"],
            "skill": meta["skill"],
            # Step 0 run-plan defaults for this profile (overridable per item).
            "orchestrator": meta["orchestrator"],
            "install_mode": meta["install_mode"],
            "idp": meta["idp"],
            "ontology_host": meta["ontology_host"],
        }

    return {
        "version": 1,
        "entrypoints": {
            "preflight": "agent-utilities-doctor --preflight --profile <profile> [--component <c>]",
            "install": "scripts/install.sh (Windows: scripts/install.ps1)",
            "config": "setup-config generate --profile <profile>",
            "verify": "agent-utilities-doctor",
            "single_node_skill": "agent-utilities-deployment",
            "multi_node_skill": "agent-os-genesis",
        },
        "profiles": profiles,
        "run_plan": RUN_PLAN,
        "preflight": {
            "command": "agent-utilities-doctor --preflight",
            "mcp_action": "graph_configure action=preflight config_key=<profile>",
            "always": [
                "python>=3.11,<3.15",
                "uv-or-pip",
                "epistemic-graph-server (from the agent-utilities wheel; Rust only as a fallback)",
            ],
            "docker_when": "profile != tiny",
        },
        "components": COMPONENTS,
        "ide_targets": {
            "install_skills": "install-skills --all-detected",
            "install_mcp": "mcp-installer --all-detected",
            # CONCEPT:OS-5.40 — governance-derived Claude Code permission fence.
            "harness_fence": "setup-config harness-fence --target ~/.claude",
            "tools": IDE_TARGETS,
        },
        "servers": {
            "source": REGISTRY.relative_to(ROOT).as_posix(),
            "transport": "streamable-http",
            "count": len(services),
            "core_count": len(core),
            "core": core,
        },
    }


HEADER = (
    "# Genesis Manifest — generated by scripts/gen_genesis_manifest.py. Do NOT edit by hand.\n"
    "#\n"
    "# The single index an agent (or scripts/install.sh) loops to deploy agent-utilities:\n"
    "#   1. pick a `profile`            (tiny | single-node-prod | enterprise)\n"
    "#   2. run `preflight`             (does this host have the runtimes/tools?)\n"
    "#   3. install + generate config   (scripts/install.sh -> setup-config)\n"
    "#   4. wire the MCP `servers`      (via the profile's `skill`)\n"
    "#   5. wire any `components` + `ide_targets`, then `verify`\n"
    "#\n"
    "# Composes existing sources (mcp-fleet.registry.yml, config profiles, docs/recipes/*,\n"
    "# the deployment preflight) — it does not duplicate them. Regenerate after changing\n"
    "# any of those; scripts/check_genesis_manifest.py gates drift.\n"
)


def render() -> str:
    body = yaml.safe_dump(
        build(),
        sort_keys=False,
        default_flow_style=False,
        width=100,
        allow_unicode=True,
    )
    return HEADER + body


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--out", type=Path, default=None, help="Output path (default: stdout)."
    )
    args = ap.parse_args()
    text = render()
    if args.out:
        args.out.write_text(text, encoding="utf-8")
        print(f"Wrote {args.out}", file=sys.stderr)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
