#!/usr/bin/env python3
"""Regenerate AGENTS.md from AGENTS.head.md plus generated sections.

The hand-written prose, conventions, commands and safety rules live in
``AGENTS.head.md``. This script appends two machine-generated sections:

  1. **Project Structure** — a pruned file tree that excludes build/cache
     directories and summarizes any directory with more than ``MAX_ENTRIES``
     children as ``<dir>/ (N entries)`` so the file stays small.
  2. **Concept Reference** — a compact per-pillar table sourced from
     ``docs/concepts.yaml`` (the single source of truth).

Run:  python scripts/gen_agents_md.py
"""

from __future__ import annotations

import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
HEAD_PATH = ROOT / "AGENTS.head.md"
OUT_PATH = ROOT / "AGENTS.md"
CONCEPTS_PATH = ROOT / "docs" / "concepts.yaml"

# Directories that must never appear in the generated tree.
EXCLUDE_DIRS = {
    ".hypothesis",
    ".venv",
    "venv",
    "node_modules",
    "target",
    "__pycache__",
    ".git",
    ".ruff_cache",
    ".mypy_cache",
    ".pytest_cache",
    ".pytest_tmp",
    ".tmp",
    ".agent_data",
    ".agent",
    ".agents",
    ".cache",
}

# Any directory with more than this many direct children is summarized.
MAX_ENTRIES = 40
# Maximum recursion depth for the tree (keeps output bounded).
MAX_DEPTH = 3

NUM_RE = re.compile(r"\d+")


def _children(path: Path) -> list[Path]:
    try:
        entries = list(path.iterdir())
    except (PermissionError, OSError):
        return []
    return sorted(entries, key=lambda p: (p.is_file(), p.name.lower()))


def _render_tree(path: Path, prefix: str, depth: int, lines: list[str]) -> None:
    if depth > MAX_DEPTH:
        return
    entries = [e for e in _children(path) if e.name not in EXCLUDE_DIRS]
    for i, entry in enumerate(entries):
        is_last = i == len(entries) - 1
        connector = "└── " if is_last else "├── "
        if entry.is_dir():
            child_entries = [c for c in _children(entry) if c.name not in EXCLUDE_DIRS]
            if len(child_entries) > MAX_ENTRIES:
                lines.append(
                    f"{prefix}{connector}{entry.name}/ ({len(child_entries)} entries)"
                )
                continue
            lines.append(f"{prefix}{connector}{entry.name}/")
            if depth < MAX_DEPTH:
                extension = "    " if is_last else "│   "
                _render_tree(entry, prefix + extension, depth + 1, lines)
        else:
            lines.append(f"{prefix}{connector}{entry.name}")


def project_tree_section() -> str:
    lines: list[str] = []
    _render_tree(ROOT, "", 1, lines)
    body = "\n".join(lines)
    return (
        "## Project Structure (generated)\n\n"
        "_Auto-generated by `scripts/gen_agents_md.py`. "
        "Build/cache directories are excluded; large directories are summarized._\n\n"
        "```text\n" + body + "\n```\n"
    )


def _id_sort_key(cid: str):
    return ([int(n) for n in NUM_RE.findall(cid)], cid)


def concepts_section() -> str:
    data = yaml.safe_load(CONCEPTS_PATH.read_text(encoding="utf-8")) or {}
    concepts = data.get("concepts", [])
    total = len(concepts)

    by_pillar: dict[str, list[dict]] = {}
    for c in concepts:
        by_pillar.setdefault(c["pillar"], []).append(c)
    pillars = sorted(by_pillar)

    lines = [
        "## Concept Reference (generated)",
        "",
        "_Auto-generated from `docs/concepts.yaml` (single source of truth). "
        f"{total} concepts across {len(pillars)} pillars._",
        "",
        "| Pillar | Count | Domains |",
        "|:------|:---:|:------|",
    ]
    for pillar in pillars:
        members = by_pillar[pillar]
        # OKF-CIS ids are <SLUG>-<PILLAR>.<domain>.<concept>; summarize by the
        # closed domain set (compact + surfaces the taxonomy) rather than listing
        # every id (908 long ids would bloat AGENTS.md far past its size gate).
        doms = sorted({
            c["id"].split(".")[1]
            for c in members
            if "." in c["id"] and "-" in c["id"].split(".")[0]
        })
        summary = ", ".join(doms) if doms else f"{len(members)} concept(s)"
        lines.append(f"| **{pillar}** | {len(members)} | {summary} |")
    lines.append("")
    lines.append("_Full id list + code paths: `docs/concepts.yaml`._")
    lines.append("")
    return "\n".join(lines)


# Marker-delimited so it can be regenerated in place without disturbing the rest
# of the file. The SAME block (modulo path) is injected into every per-package
# AGENTS.md by agent-packages/scripts/generate_ecosystem_docs.py.
CONCEPT_POINTER_BEGIN = "<!-- BEGIN concept-coordination (generated) -->"
CONCEPT_POINTER_END = "<!-- END concept-coordination (generated) -->"


def concept_protocol_section(doc_path: str = "docs/concept_coordination.md") -> str:
    """A short pointer to the one canonical multi-session coordination protocol."""
    return "\n".join(
        [
            CONCEPT_POINTER_BEGIN,
            "## Concept-ID Coordination (multi-session)",
            "",
            "Working in parallel with other sessions/worktrees? **Reserve a concept id "
            "before you write its `CONCEPT:` marker** so two sessions never collide:",
            "",
            "```bash",
            "agent-utilities --json concept reserve --ns KG-2   # or a package prefix, e.g. KEY",
            "```",
            "",
            f"Full protocol (ledger, merge=union, reconcile, MCP/REST): [`{doc_path}`]"
            f"(../agent-utilities/{doc_path}).",
            CONCEPT_POINTER_END,
        ]
    )


def build() -> str:
    head = HEAD_PATH.read_text(encoding="utf-8").rstrip()
    parts = [
        head,
        "",
        project_tree_section().rstrip(),
        "",
        # The canonical doc lives in this very repo, so link to it relatively.
        concept_protocol_section()
        .replace("../agent-utilities/docs/", "docs/")
        .rstrip(),
        "",
        concepts_section().rstrip(),
        "",
    ]
    return "\n".join(parts) + "\n"


def main() -> None:
    content = build()
    # Exactly one trailing newline so the end-of-file-fixer hook is a no-op.
    content = content.rstrip("\n") + "\n"
    OUT_PATH.write_text(content, encoding="utf-8")
    size = len(content.encode("utf-8"))
    has_hypothesis = ".hypothesis" in content
    print(
        f"Wrote {OUT_PATH.relative_to(ROOT)}: {size} bytes "
        f"({size / 1024:.1f} KiB). .hypothesis present: {has_hypothesis}"
    )


if __name__ == "__main__":
    main()
