#!/usr/bin/env python3
"""Generate ``genesis.yaml`` — the single index an agent loops to self-deploy.

``genesis.yaml`` is the machine-readable contract behind the one-link deploy: an
agent (or ``scripts/install.sh``) reads it to pick a profile, run the host
preflight, install, then wire the MCP fleet and any chosen UI components. It
**composes** sources that already exist rather than duplicating them:

* the MCP fleet + per-service profiles come from ``deploy/mcp-fleet.registry.yml``
  (itself generated by ``gen_mcp_fleet_registry.py``);
* the deployment profiles mirror ``agent_utilities.deployment.config_generator.PROFILES``
  and the ``docs/recipes/*`` runbooks;
* the preflight describes ``agent-utilities-doctor --preflight``;
* the IDE targets mirror the ``install-skills`` / ``mcp-installer`` tool sets.

Because it is generated, drift is caught by ``scripts/check_genesis_manifest.py``
(a CI gate) — never hand-edit ``genesis.yaml``.

Usage:
    python scripts/gen_genesis_manifest.py --out genesis.yaml
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "deploy" / "mcp-fleet.registry.yml"
RECIPES = ROOT / "docs" / "recipes"

# The standard operator-owned PRIVATE repo set + generalized CI templates genesis
# provisions per profile (CONCEPT:OS-5.74 / OS-5.75). Sourced from
# agent_utilities/deployment/repo_templates.py so genesis.yaml never drifts from the
# templates. Loaded by file path (no package __init__ side effects) — abstract by
# construction, so no operator-specific env enters the manifest.
import importlib.util as _ilu  # noqa: E402

_RT_PATH = ROOT / "agent_utilities" / "deployment" / "repo_templates.py"
_rt_spec = _ilu.spec_from_file_location("_genesis_repo_templates", _RT_PATH)
_repo_templates = _ilu.module_from_spec(_rt_spec)
# Register before exec so dataclass introspection can resolve __module__.
sys.modules[_rt_spec.name] = _repo_templates
_rt_spec.loader.exec_module(_repo_templates)
_repo_manifest_summary = _repo_templates.manifest_summary

# Deployment profiles — mirror config_generator.PROFILES (tiny|single-node-prod|enterprise).
# Kept here (not imported) so the generator runs without importing the package.
PROFILES_META = {
    "tiny": {
        "summary": "zero-infra, all-local (laptop / Raspberry Pi) — homelab quick start",
        "docker": False,
        # Embedded engine-encrypted __secrets__ graph (CONCEPT:OS-5.66) is the
        # default app-secret store; .env only carries the bootstrap model key +
        # EPISTEMIC_GRAPH_ENCRYPTION_KEY.
        "secrets": "engine-encrypted-or-dotenv",
        "servers": "none",
        "skill": "agent-utilities-deployment",
        # Step 0 run-plan defaults (the operator overrides only the exceptions).
        "orchestrator": "docker-compose",
        "install_mode": "deploy-baremetal",
        "idp": "none",
        "ontology_host": "local",
        # The ONE engine authority is AUTO-STARTED on demand by the single
        # resolver (CONCEPT:OS-5.63) from a prebuilt multi-arch wheel — a Pi
        # NEVER compiles. It is the pi-max tier binary (lean pure-Rust: graph +
        # cypher + ann + rdf/sparql/owl + tsdb + blob + streaming + security/
        # encryption-at-rest; NO DataFusion/C). NOT in-process, NOT a cache: a
        # detached, redb-authoritative durable engine, reference-counted
        # (self-stops ~60s after the last client disconnects; set
        # engine_lifecycle=persistent for a long-living engine). Every entrypoint
        # on the host shares the one engine.
        "engine": "autostart",
        "engine_tier": "pi-max",
        "engine_lifecycle": "refcounted",
        "engine_idle_shutdown_secs": 60,
    },
    "single-node-prod": {
        "summary": "one durable, secured host (Postgres/pg-age) + the core MCP connectors",
        "docker": True,
        "secrets": "openbao-or-engine-encrypted",
        "servers": "core",
        "skill": "agent-utilities-deployment",
        "orchestrator": "docker-swarm",
        "install_mode": "deploy-container",
        "idp": "keycloak",
        "ontology_host": "local",
        # Engine runs as its own multi-arch Docker image (engine-as-a-DB) on the
        # host — the `node` tier (pi-max + SQL/DataFusion + GraphQL + Tantivy text
        # + reasoning + wasm-udf + federation). `full` is the size-optimized
        # all-single-node variant.
        "engine": "container",
        "engine_tier": "node",
    },
    "enterprise": {
        "summary": "multi-host Docker Swarm, full integration (Vault/SSO/DNS/ingress/observability + all connectors)",
        "docker": True,
        "secrets": "openbao",
        "servers": "all",
        "skill": "agent-os-genesis",
        # Enterprises default to Kubernetes (Step 0 note).
        "orchestrator": "kubernetes",
        "install_mode": "deploy-container",
        "idp": "keycloak",
        "ontology_host": "stardog",
        # Shared/remote engine reached via GRAPH_SERVICE_ENDPOINTS; the `cluster`
        # tier (node + multi-Raft replication + pgwire + distributed Pregel /
        # cross-shard 2PC) runs as the engine-as-a-DB container; mirrors fan out.
        "engine": "remote",
        "engine_tier": "cluster",
    },
}

# Step 0 adaptive run-plan axes — the choices the genesis questionnaire offers per
# capability/connector. Profiles seed the defaults above; these are the allowed values.
RUN_PLAN = {
    "actions": ["deploy-container", "deploy-baremetal", "use-existing", "skip"],
    "orchestrators": [
        "docker-compose",
        "docker-swarm",
        "podman",
        "podman-compose",
        "kubernetes",
    ],
    "podman_modes": ["rootful", "rootless"],
    "idp": ["keycloak", "okta", "other-oidc", "none"],
    # secrets_store precedence: `engine` = the engine's encrypted __secrets__ graph
    # (CONCEPT:OS-5.66, the default embedded app-secret store, sealed by the engine's
    # encryption-at-rest under EPISTEMIC_GRAPH_ENCRYPTION_KEY); `vault` = OpenBao/Vault
    # (enterprise fleet source of truth); `env` = .env fallback.
    "secrets_store": ["engine", "vault", "env"],
    "ontology_hosts": ["stardog", "apache-jena", "local"],
    # epistemic-graph is the ONE multi-model store at EVERY scale (not a cache).
    # Deployment SHAPE: autostart = the resolver auto-starts the pi-tier binary
    # from a prebuilt wheel (tiny, CONCEPT:OS-5.63); container = the engine-as-a-DB
    # Docker image (single-node-prod); remote = shared engine via
    # GRAPH_SERVICE_ENDPOINTS (enterprise).
    "engine": ["autostart", "container", "remote"],
    # Engine TIER = which prebuilt feature bundle to ship (size grows with features).
    # pi (~6.46MB lean Pi-3: graph+cypher+ann+rdf/sparql/owl+streaming, pure-Rust);
    # pi-max (~6.96MB: pi + tsdb+blob+security/encryption-at-rest, still no DataFusion/C);
    # node (pi-max + SQL/DataFusion+GraphQL+Tantivy text+reasoning+wasm-udf+federation);
    # cluster (node + multi-Raft+pgwire+distributed/cross-shard-2PC); full (all single-node).
    # Multi-arch prebuilt WHEELS (linux x86_64/aarch64, macOS x86_64/arm64, windows) ship
    # so a Pi `pip install`s and NEVER compiles; engine-as-a-DB Docker image for node/cluster.
    "engine_tiers": ["pi", "pi-max", "node", "cluster", "full"],
    "install_modes": ["deploy-container", "deploy-baremetal", "use-existing", "skip"],
    # prod = PyPI image / uvx; dev = editable: `pip/uv install -e` (baremetal) OR the
    # package's compose.dev.yml source-mounted container (edits live on restart).
    "install_variants": ["prod", "dev"],
    # Agent->user messaging (CONCEPT:ECO-4.0). channels = MESSAGING_ENABLED_BACKENDS;
    # reach_mode last-active works today, broadcast fans out to all (engine fan-out).
    "messaging": {
        "channels": [
            "slack",
            "teams",
            "telegram",
            "mattermost",
            "discord",
            "whatsapp",
            "matrix",
            "signal",
        ],
        "reach_modes": ["last-active", "broadcast"],
    },
    # Single-package skill-guided deploy: genesis with a one-item run plan; the entry
    # point each agents/* README references. Reuses the connector catalog + install
    # modes/variants + vault_sync.
    "single_package_deploy": {
        "invoke": "deploy <package> with agent-os-genesis",
        "catalog": "universal-skills agent-os-genesis references/connector-catalog.md",
    },
    "provisioner_by_orchestrator": {
        "docker-swarm": "swarm-mesh-provisioner",
        "kubernetes": "kubernetes-mesh-provisioner",
        "podman": "podman-mesh-provisioner",
        "podman-compose": "podman-mesh-provisioner",
        "docker-compose": "docker-compose-operator",
    },
}

# Opt-in UI components — each is preflighted before it is wired (see preflight.py).
COMPONENTS = {
    "agent-terminal-ui": {
        "connect": "http",
        "deps": ["python>=3.11"],
        "container": True,
        "note": "thin Textual TUI over the gateway; many fit on a Pi-class node",
    },
    "agent-webui": {
        "connect": "http",
        "deps": ["node>=18", "pnpm>=10"],
        "container": "needs-dockerfile",
        "note": "React/Vite SPA + FastAPI; talks to the gateway over /api/*",
    },
    "geniusbot": {
        "connect": "import",
        "deps": ["python>=3.11", "PySide6/Qt6", "libGL", "libxcb", "display"],
        "container": False,
        "note": "PySide6 desktop app; needs an X11/Wayland display — not headless/cloud",
    },
}

# IDE / agent-tool targets the bootstrap can wire skills + MCP config into
# (`install-skills --all-detected` / `mcp-installer --all-detected`). Mirrors the
# union of those installers' TOOL_PATHS.
IDE_TARGETS = [
    "claude",
    "claude-desktop",
    "windsurf",
    "opencode",
    "openclaw",
    "antigravity",
    "codex",
    "devin",
    "cursor",
    "zed",
    "agent-utilities",
    "agent-terminal-ui",
]


def _load_registry() -> list[dict]:
    if not REGISTRY.exists():
        print(
            f"error: {REGISTRY} missing — run gen_mcp_fleet_registry.py",
            file=sys.stderr,
        )
        raise SystemExit(2)
    data = yaml.safe_load(REGISTRY.read_text(encoding="utf-8")) or {}
    return data.get("services", [])


def build() -> dict:
    services = _load_registry()
    core = sorted(
        s["name"] for s in services if "single-node-prod" in (s.get("profiles") or [])
    )
    profiles = {}
    for name, meta in PROFILES_META.items():
        recipe = RECIPES / f"{name}.md"
        profiles[name] = {
            "summary": meta["summary"],
            "recipe": recipe.relative_to(ROOT).as_posix() if recipe.exists() else None,
            "docker": meta["docker"],
            "secrets": meta["secrets"],
            "servers": meta["servers"],
            "skill": meta["skill"],
            # Step 0 run-plan defaults for this profile (overridable per item).
            "orchestrator": meta["orchestrator"],
            "install_mode": meta["install_mode"],
            "idp": meta["idp"],
            "ontology_host": meta["ontology_host"],
            # epistemic-graph engine deployment shape (autostart|container|remote).
            "engine": meta["engine"],
            # Prebuilt engine tier to ship for this profile (pi|pi-max|node|cluster|full).
            "engine_tier": meta["engine_tier"],
            # Autostarted-engine lifecycle (CONCEPT:OS-5.63): refcounted (shared,
            # auto-stops when idle — tiny default) vs persistent (long-living).
            "engine_lifecycle": meta.get("engine_lifecycle", "refcounted"),
            "engine_idle_shutdown_secs": meta.get("engine_idle_shutdown_secs", 60),
        }

    return {
        "version": 1,
        "entrypoints": {
            "preflight": "agent-utilities-doctor --preflight --profile <profile> [--component <c>]",
            "install": "scripts/install.sh (Windows: scripts/install.ps1)",
            "config": "setup-config generate --profile <profile>",
            "verify": "agent-utilities-doctor",
            "single_node_skill": "agent-utilities-deployment",
            "multi_node_skill": "agent-os-genesis",
        },
        "profiles": profiles,
        "run_plan": RUN_PLAN,
        "preflight": {
            "command": "agent-utilities-doctor --preflight",
            "mcp_action": "graph_configure action=preflight config_key=<profile>",
            "always": [
                "python>=3.11,<3.15",
                "uv-or-pip",
                "epistemic-graph>=1.0.0 — a prebuilt multi-arch WHEEL (linux x86_64/aarch64,"
                " macOS, windows); a Pi pip-installs the lean pi/pi-max tier and NEVER"
                " compiles. Rust toolchain only as a build-from-source fallback.",
            ],
            "docker_when": "profile != tiny",
        },
        # The ONE multi-model store at every scale (CONCEPT:OS-5.63 resolver). It is NOT
        # a cache — it is durable, redb-authoritative by default (an acked write survives
        # kill -9), spanning graph + vector/ANN + SQL + RDF/SPARQL + OWL-2 reasoning +
        # time-series + blob + text + multi-Raft + cross-shard 2PC + streaming/CDC +
        # RLS/encryption-at-rest/audit + federation + GraphQL.
        "engine": {
            "version": "epistemic-graph>=1.0.0",
            "extra": "pip install 'agent-utilities[engine]'  (bumps to the published wheel)",
            "authority": "redb-authoritative durable by default (CONCEPT:KG-2.195)",
            "resolver": "CONCEPT:OS-5.63 — remote -> share-running-local -> autostart the"
            " pi-tier binary; refcounted (auto-stops idle) or persistent lifecycle",
            "wheels": "prebuilt multi-arch (linux x86_64/aarch64, macOS x86_64/arm64,"
            " windows) — the Pi tiers never compile",
            "docker_image": "engine-as-a-DB multi-arch image (linux/amd64+arm64) for"
            " container/remote shapes (single-node-prod, enterprise)",
            "tiers": {
                "pi": "~6.46MB lean Pi-3: graph+cypher+ann+rdf/sparql/owl+streaming (pure-Rust, no DataFusion/C)",
                "pi-max": "~6.96MB: pi + tsdb+blob+security/encryption-at-rest (still pure-Rust, no DataFusion/C)",
                "node": "pi-max + SQL/DataFusion+GraphQL+Tantivy text+reasoning+wasm-udf+federation",
                "cluster": "node + multi-Raft replication+pgwire+distributed/cross-shard-2PC (HA)",
                "full": "all single-node features, size-optimized (no raft/pgwire)",
            },
            # The embedded app-secret store (CONCEPT:OS-5.66): :Secret nodes in the
            # __secrets__ graph, values sealed by the engine's encryption-at-rest. The
            # encryption key is itself a genesis-provisioned secret (Step 8).
            "secret_store": {
                "graph": "__secrets__",
                "label": "Secret",
                "encryption_key_env": "EPISTEMIC_GRAPH_ENCRYPTION_KEY",
                "note": "default embedded secret store (OS-5.66); needs a security-feature"
                " tier (pi-max/node/cluster/full). Local SQLite caches (registry graph,"
                " card cache, time-series) also route to the engine — no SQLite fallback.",
            },
        },
        "components": COMPONENTS,
        "ide_targets": {
            "install_skills": "install-skills --all-detected",
            "install_mcp": "mcp-installer --all-detected",
            # CONCEPT:OS-5.40 — governance-derived Claude Code permission fence.
            "harness_fence": "setup-config harness-fence --target ~/.claude",
            "tools": IDE_TARGETS,
        },
        "servers": {
            "source": REGISTRY.relative_to(ROOT).as_posix(),
            "transport": "streamable-http",
            "count": len(services),
            "core_count": len(core),
            "core": core,
        },
        # Standard operator-owned PRIVATE repos genesis provisions (Step 9b). The
        # operator's environment (inventory/workspace/secrets) lives ONLY in these
        # private repos + the XDG config — never in this public repo. Abstract,
        # templated, profile-scaled (CONCEPT:OS-5.74 / OS-5.75).
        "private_repos": _repo_manifest_summary(),
    }


HEADER = (
    "# Genesis Manifest — generated by scripts/gen_genesis_manifest.py. Do NOT edit by hand.\n"
    "#\n"
    "# The single index an agent (or scripts/install.sh) loops to deploy agent-utilities:\n"
    "#   1. pick a `profile`            (tiny | single-node-prod | enterprise)\n"
    "#   2. run `preflight`             (does this host have the runtimes/tools?)\n"
    "#   3. install + generate config   (scripts/install.sh -> setup-config)\n"
    "#   4. wire the MCP `servers`      (via the profile's `skill`)\n"
    "#   5. wire any `components` + `ide_targets`, then `verify`\n"
    "#\n"
    "# Composes existing sources (mcp-fleet.registry.yml, config profiles, docs/recipes/*,\n"
    "# the deployment preflight) — it does not duplicate them. Regenerate after changing\n"
    "# any of those; scripts/check_genesis_manifest.py gates drift.\n"
)


def render() -> str:
    body = yaml.safe_dump(
        build(),
        sort_keys=False,
        default_flow_style=False,
        width=100,
        allow_unicode=True,
    )
    return HEADER + body


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--out", type=Path, default=None, help="Output path (default: stdout)."
    )
    args = ap.parse_args()
    text = render()
    if args.out:
        args.out.write_text(text, encoding="utf-8")
        print(f"Wrote {args.out}", file=sys.stderr)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
