#!/usr/bin/env python3
"""Generate the MCP fleet registry from the agents/* connector packages.

Scans an ``agent-packages/agents`` directory for packages that expose a
streamable-http-capable MCP server (an ``mcp_server.py`` whose ``mcp_server``
console script is declared in ``pyproject.toml``) and emits a deterministic
``mcp-fleet.registry.yml``: one entry per service with its console script,
package, container port, a unique host port, and the deployment profiles that
enable it.

This registry is the single source of truth consumed by ``portainer-sync-agent``
(GitOps deploy) and rendered into the day-0 service+port table. It is generated,
not hand-edited.

Usage:
    python scripts/gen_mcp_fleet_registry.py \
        --agents-dir /path/to/agent-packages/agents \
        --out deploy/mcp-fleet.registry.yml
"""

from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path

# Connectors that form the infra/control core — enabled from the single-node-prod
# profile upward (everything else is enterprise-only by default).
CORE_CONNECTORS = {
    "openbao-mcp",
    "keycloak-agent",
    "technitium-dns-mcp",
    "portainer-agent",
    "container-manager-mcp",
    "caddy-mcp",
    "repository-manager",
    "vector-mcp",
    "systems-manager",
    "tunnel-manager",
}

CONTAINER_PORT = 8000
HOST_PORT_BASE = 8200  # 8100 is reserved for the REST gateway (graph-os-daemon)


def _find_mcp_console_script(pyproject: Path) -> tuple[str, str] | None:
    """Return (console_script, package_name) if this package exposes an MCP server."""
    try:
        data = tomllib.loads(pyproject.read_text())
    except (OSError, tomllib.TOMLDecodeError):
        return None
    project = data.get("project", {})
    scripts = project.get("scripts", {})
    pkg = project.get("name", "")
    for script_name, target in scripts.items():
        # Standard entry: "<pkg>.mcp_server:mcp_server"
        if str(target).endswith("mcp_server:mcp_server"):
            return script_name, pkg
    return None


def discover(agents_dir: Path) -> list[dict]:
    services: list[dict] = []
    for pkg_dir in sorted(p for p in agents_dir.iterdir() if p.is_dir()):
        pyproject = pkg_dir / "pyproject.toml"
        if not pyproject.exists():
            continue
        # Require a non-venv mcp_server.py in the package source.
        has_server = any(
            ".venv" not in str(p) and "site-packages" not in str(p)
            for p in pkg_dir.rglob("mcp_server.py")
        )
        if not has_server:
            continue
        found = _find_mcp_console_script(pyproject)
        if not found:
            continue
        console_script, package = found
        services.append(
            {
                "name": console_script,
                "package": package,
                "console_script": console_script,
                "dir": pkg_dir.name,
            }
        )
    # Deterministic host-port assignment.
    for idx, svc in enumerate(services):
        svc["host_port"] = HOST_PORT_BASE + idx
        svc["profiles"] = (
            ["single-node-prod", "enterprise"]
            if svc["name"] in CORE_CONNECTORS
            else ["enterprise"]
        )
    return services


def render(services: list[dict]) -> str:
    lines = [
        "# MCP Fleet Registry — generated by scripts/gen_mcp_fleet_registry.py.",
        "# Do not edit by hand. One entry per agents/* connector exposing a",
        "# streamable-http MCP server. Consumed by portainer-sync-agent + day0.",
        "version: 1",
        "defaults:",
        "  transport: streamable-http",
        "  host: 0.0.0.0",
        f"  container_port: {CONTAINER_PORT}",
        "  image_registry: docker.io/knucklessg1",
        "services:",
    ]
    for svc in services:
        profiles = ", ".join(svc["profiles"])
        lines += [
            f"  - name: {svc['name']}",
            f"    package: {svc['package']}",
            f"    console_script: {svc['console_script']}",
            f"    image: knucklessg1/{svc['package']}:latest",
            f"    container_port: {CONTAINER_PORT}",
            f"    host_port: {svc['host_port']}",
            f"    profiles: [{profiles}]",
        ]
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--agents-dir", required=True, type=Path)
    ap.add_argument("--out", type=Path, default=None)
    args = ap.parse_args()

    if not args.agents_dir.is_dir():
        print(f"error: {args.agents_dir} is not a directory", file=sys.stderr)
        return 2

    services = discover(args.agents_dir)
    out_text = render(services)
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(out_text)
        print(f"Wrote {args.out}: {len(services)} MCP services.", file=sys.stderr)
    else:
        sys.stdout.write(out_text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
