#!/usr/bin/env python3
"""Generate the privacy-safe connector/skill ecosystem catalog.

Only neutral package names and repository-relative capability state enter the
document.  Repository URLs, filesystem roots, credentials, and source profiles
are deliberately excluded.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from urllib.parse import urlparse

import yaml

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_AGENTS_ROOT = ROOT.parent / "agents"
DEFAULT_WORKSPACE = (
    DEFAULT_AGENTS_ROOT
    / "repository-manager"
    / "repository_manager"
    / "workspace.yml"
)
DEFAULT_OUTPUT = ROOT / "docs" / "ecosystem-capability-fleet.md"


def _agent_entries(workspace: Path) -> list[dict]:
    data = yaml.safe_load(workspace.read_text(encoding="utf-8"))
    return list(
        data["subdirectories"]["agent-packages"]["subdirectories"]["agents"]
        ["repositories"]
    )


def _package_name(entry: dict) -> str:
    path = urlparse(str(entry["url"])).path.rstrip("/")
    return Path(path).name.removesuffix(".git")


def _canonical_skills(repository: Path) -> list[Path]:
    return sorted(
        path
        for path in repository.glob("*/skills/*/SKILL.md")
        if "__pycache__" not in path.parts
    )


def _status(value: bool) -> str:
    return "yes" if value else "missing"


def render(workspace: Path, agents_root: Path) -> str:
    packages = sorted(_package_name(entry) for entry in _agent_entries(workspace))
    rows: list[str] = []
    complete = 0
    source_connectors = 0
    for package in packages:
        repository = agents_root / package
        skills = _canonical_skills(repository)
        provider_root = skills[0].parents[2] if skills else repository / "missing"
        openai = bool(skills and (skills[0].parent / "agents" / "openai.yaml").is_file())
        manifest = (repository / "connector_manifest.yml").is_file()
        bundle = all(
            (provider_root / "ontology" / name).exists()
            for name in (
                "shapes",
                "mappings",
                "fixtures",
                "migrations",
                "certification.json",
            )
        )
        presets = (
            provider_root / "connectors" / "mcp_source_presets.json"
        ).is_file()
        schema = (
            provider_root / "connectors" / "tool_schema_fingerprints.json"
        ).is_file()
        source_connectors += int(presets)
        mkdocs = (repository / "mkdocs.yml").is_file()
        one_skill = len(skills) == 1
        is_complete = (
            repository.is_dir()
            and manifest
            and bundle
            and (schema if presets else True)
            and one_skill
            and openai
        )
        complete += int(is_complete)
        rows.append(
            "| "
            + " | ".join(
                (
                    f"`{package}`",
                    _status(manifest),
                    _status(bundle),
                    "yes" if presets else "n/a",
                    _status(schema) if presets else "n/a",
                    "one" if one_skill else f"{len(skills)}",
                    _status(openai),
                    _status(mkdocs),
                )
            )
            + " |"
        )

    return "\n".join(
        [
            "# Ecosystem capability and skill fleet",
            "",
            "> Generated by `scripts/generate_ecosystem_capability_catalog.py`; do not edit by hand.",
            "",
            "The repository-manager workspace manifest is the package authority. Each provider",
            "repository contributes one comprehensive canonical skill; former specialist skills",
            "are retained as `WORKFLOW.md` references inside that skill rather than separately",
            "advertised capabilities. This keeps discovery compact while preserving deep procedures.",
            "",
            "Every governed connector also owns a capability bundle: signed manifest, ontology,",
            "SHACL shapes, mappings, fixtures, migrations, exact live tool-schema fingerprints,",
            "and certification metadata. Agent Utilities carries pinned manifest fallbacks for",
            "standalone GraphOS deployments, but the connector-owned bundle remains authoritative.",
            "",
            f"Current package coverage: **{complete}/{len(packages)} complete packages**; "
            f"**{source_connectors}/{len(packages)}** expose governed source-sync presets.",
            "",
            "| Package | Manifest | Bundle | Source sync | Tool schema | Canonical skills | OpenAI metadata | MkDocs |",
            "|---|---:|---:|---:|---:|---:|---:|---:|",
            *rows,
            "",
            "## Validation contract",
            "",
            "A release fails when a package is absent, advertises more than one canonical skill,",
            "has invalid skill metadata, lacks a signed bundle, or its live MCP tool schema differs",
            "from the connector-owned fingerprint. Direct skill execution and GraphOS-delegated",
            "execution are certified separately in the release validation matrix; this catalog",
            "describes packaged coverage, not a fabricated live result.",
            "",
            "Runtime configuration stores only neutral aliases and secret references. Endpoints,",
            "credentials, raw identities, workstation names, and filesystem locations must never",
            "enter this generated page, capability manifests, trace attributes, or certification",
            "summaries.",
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--workspace", type=Path, default=DEFAULT_WORKSPACE)
    parser.add_argument("--agents-root", type=Path, default=DEFAULT_AGENTS_ROOT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render(args.workspace, args.agents_root)
    if args.check:
        return (
            0
            if args.output.is_file()
            and args.output.read_text(encoding="utf-8") == content
            else 1
        )
    args.output.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
