#!/usr/bin/env python3
"""Generate the connector / ingestor / enricher inventory (CONCEPT:KG-2.9).

Introspects the LIVE registries — the single sources of truth — and rewrites the
auto-generated inventory block in
``docs/architecture/kg_connectors_and_ingestion.md`` so the map never drifts:

* delta handlers          ``core/source_sync.py``      → ``_DELTA_HANDLERS``
* capability hydrate       ``core/hydration.py``        → ``CAPABILITY_REGISTRY``
* materialize extractors   ``enrichment/materialize.py``→ ``MATERIALIZE_SOURCES``
* document-ingest presets  ``…/connectors/mcp_tool.py`` → ``MCP_TOOL_PRESETS``
* writeback sinks          ``enrichment/writeback/``    → ``list_sinks()``

Usage:  python scripts/generate_connector_map.py [--check]
``--check`` exits non-zero if the doc is stale (for CI), writing nothing.
"""

from __future__ import annotations

import sys
from pathlib import Path

BEGIN = "<!-- BEGIN:CONNECTOR-INVENTORY (generated by scripts/generate_connector_map.py) -->"
END = "<!-- END:CONNECTOR-INVENTORY -->"
DOC = (
    Path(__file__).resolve().parent.parent
    / "docs"
    / "architecture"
    / "kg_connectors_and_ingestion.md"
)


def _load() -> dict[str, list[str]]:
    import agent_utilities.knowledge_graph.enrichment.writeback  # noqa: F401 (register)
    from agent_utilities.knowledge_graph.core.hydration import CAPABILITY_REGISTRY
    from agent_utilities.knowledge_graph.core.source_sync import _DELTA_HANDLERS
    from agent_utilities.knowledge_graph.enrichment.materialize import (
        MATERIALIZE_SOURCES,
    )
    from agent_utilities.knowledge_graph.enrichment.writeback.core import list_sinks
    from agent_utilities.protocols.source_connectors.connectors.mcp_tool import (
        list_tool_presets,
    )

    return {
        "delta": sorted(_DELTA_HANDLERS),
        "capability": sorted(CAPABILITY_REGISTRY),
        "materialize": sorted(MATERIALIZE_SOURCES),
        "presets": sorted(list_tool_presets()),
        "sinks": sorted(list_sinks()),
    }


def _matrix(reg: dict[str, list[str]]) -> str:
    delta, cap, mat, sinks = (
        set(reg["delta"]),
        set(reg["capability"]),
        set(reg["materialize"]),
        set(reg["sinks"]),
    )
    names = sorted(delta | cap | mat | sinks)
    tick = lambda b: "✅" if b else "—"  # noqa: E731
    rows = [
        "| Connector | Delta (in) | Hydrate (in) | Materialize (in) | Writeback (out) |",
        "|---|:--:|:--:|:--:|:--:|",
    ]
    for n in names:
        rows.append(
            f"| `{n}` | {tick(n in delta)} | {tick(n in cap)} "
            f"| {tick(n in mat)} | {tick(n in sinks)} |"
        )
    return "\n".join(rows)


def _presets(reg: dict[str, list[str]]) -> str:
    return "\n".join(f"- `{p}`" for p in reg["presets"])


def _block(reg: dict[str, list[str]]) -> str:
    counts = {k: len(v) for k, v in reg.items()}
    total = len(
        set(reg["delta"])
        | set(reg["capability"])
        | set(reg["materialize"])
        | set(reg["sinks"])
    )
    return (
        f"{BEGIN}\n\n"
        f"_Auto-generated — do not edit by hand. Run `python scripts/generate_connector_map.py`._\n\n"
        f"**{total} distinct connectors** across the ingestion/enrichment paths: "
        f"{counts['delta']} delta handlers · {counts['capability']} capability-hydrate · "
        f"{counts['materialize']} materialize extractors · {counts['sinks']} writeback sinks · "
        f"{counts['presets']} document-ingest presets.\n\n"
        f"### Connector × path matrix\n\n"
        f"`in` = ingests into the KG · `out` = writes KG intelligence back to the system.\n\n"
        f"{_matrix(reg)}\n\n"
        f"### Document-ingest presets (`MCP_TOOL_PRESETS`)\n\n"
        f"Declarative connectors that pull records/files/search-results as Documents "
        f"through the generic `McpToolSourceConnector`:\n\n"
        f"{_presets(reg)}\n\n"
        f"{END}"
    )


def main() -> int:
    check = "--check" in sys.argv
    reg = _load()
    block = _block(reg)
    text = DOC.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        print(f"markers not found in {DOC}", file=sys.stderr)
        return 2
    pre = text.split(BEGIN)[0]
    post = text.split(END)[1]
    new = pre + block + post
    if check:
        if new != text:
            print("connector map is STALE — run scripts/generate_connector_map.py")
            return 1
        print("connector map up to date")
        return 0
    DOC.write_text(new, encoding="utf-8")
    print(f"wrote {DOC}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
