#!/usr/bin/env python3
"""Check every Git push ref, then run the unmodified pre-commit push checks."""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

if __package__:
    from . import check_liveness_source as liveness
else:
    import check_liveness_source as liveness


def install(repo: Path) -> None:
    """Adapt only pre-commit's generated hook; preserve its driver and legacy hooks."""
    path = Path(liveness._git(repo, "rev-parse", "--git-path", "hooks/pre-push"))
    if not path.is_absolute():
        path = repo / path
    if path.is_symlink():
        raise liveness.CannotRun("refusing a symlinked pre-push hook")
    source = path.read_text()
    if "# ID: 138fd403232d2ddd5efb44317e38bf03" not in source:
        raise liveness.CannotRun("pre-push hook is not generated by pre-commit")
    if "scripts/pre_push.py" in source:
        return
    replacements = {
        'exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"': 'exec scripts/hook_python.sh scripts/pre_push.py "$INSTALL_PYTHON" "${ARGS[@]}"',
        'exec pre-commit "${ARGS[@]}"': 'exec scripts/hook_python.sh scripts/pre_push.py "" "${ARGS[@]}"',
    }
    for before, after in replacements.items():
        if source.count(before) != 1:
            raise liveness.CannotRun("unrecognized pre-commit hook template")
        source = source.replace(before, after)
    path.write_text(source)


def check_refs(repo: Path, remote: str, payload: str) -> int:
    if remote != "origin":
        raise liveness.CannotRun("source push must use origin for fresh-main evidence")
    rows = []
    for line in payload.splitlines():
        fields = line.split()
        if len(fields) != 4:
            raise liveness.CannotRun("malformed Git push ref input")
        _, local, target, previous = fields
        if not all(
            re.fullmatch(r"[0-9a-f]{40}|[0-9a-f]{64}", oid) for oid in (local, previous)
        ):
            raise liveness.CannotRun("push input lacks immutable object IDs")
        if set(local) == {"0"}:  # deletion publishes no candidate tree
            continue
        if not target.startswith(("refs/heads/", "refs/tags/")):
            raise liveness.CannotRun("unsupported outgoing ref namespace")
        candidate = liveness._git(repo, "rev-parse", "--verify", f"{local}^{{commit}}")
        rows.append((candidate, target.startswith("refs/tags/")))
    base = liveness._remote_main(repo)
    for candidate, release in dict.fromkeys(rows):
        result = liveness.run(repo, base, candidate, release=release)
        if result:
            return result
    return 0


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    try:
        if args == ["--install"]:
            install(liveness.REPO)
            return 0
        driver, *hook_args = args
        remote_args = hook_args[hook_args.index("--") + 1 :]
        if len(remote_args) != 2:
            raise liveness.CannotRun("missing native Git push remote arguments")
        payload = sys.stdin.buffer.read()
        result = check_refs(liveness.REPO, remote_args[0], payload.decode())
        if result:
            return result
        if driver and os.access(driver, os.X_OK):
            command = [driver, "-m", "pre_commit", *hook_args]
        else:
            executable = shutil.which("pre-commit")
            if executable is None:
                raise liveness.CannotRun("normal pre-commit driver is unavailable")
            command = [executable, *hook_args]
        return subprocess.run(command, input=payload, check=False).returncode
    except (liveness.CannotRun, OSError, ValueError) as exc:
        print(f"Push liveness CANNOT RUN: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
