#!/usr/bin/python
"""Unified Graph Schema Definition.

This module defines the structural schema for the knowledge graph,
which can be used by different backends (Ladybug, Neo4j, FalkorDB)
to initialize tables or indices.
"""

from .knowledge_graph import GraphSchemaDefinition, RelDefinition, TableDefinition

SCHEMA = GraphSchemaDefinition(
    nodes=[
        # Core Registry Nodes
        TableDefinition(
            name="Agent",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "description": "STRING",
                "agent_type": "STRING",
                "system_prompt": "STRING",
                "capabilities": "STRING[]",
                "tool_count": "INT64",
                "mcp_server": "STRING",
                "last_sync": "INT64",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Tool",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "description": "STRING",
                "mcp_server": "STRING",
                "relevance_score": "INT64",
                "tags": "STRING[]",
                "requires_approval": "BOOLEAN",
                "last_sync": "INT64",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Server",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "url": "STRING",
                "status": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Prompt",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "description": "STRING",
                "system_prompt": "STRING",
                "capabilities": "STRING[]",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "json_blueprint": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Skill",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "description": "STRING",
                "version": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Code",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "description": "STRING",
                "file_path": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Memory",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "description": "STRING",
                "category": "STRING",
                "timestamp": "STRING",
                "tags": "STRING[]",
                "importance_score": "FLOAT",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        # User & Environment Nodes
        TableDefinition(
            name="Client",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "description": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="User",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "role": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Preference",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "category": "STRING",
                "value": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Job",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "schedule": "STRING",
                "command": "STRING",
                "last_run": "STRING",
                "next_approx": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Log",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "timestamp": "STRING",
                "task_id": "STRING",
                "task_name": "STRING",
                "status": "STRING",
                "output": "STRING",
                "chat_id": "STRING",
                "importance_score": "FLOAT",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Thread",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "title": "STRING",
                "created_at": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Message",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "role": "STRING",
                "content": "STRING",
                "timestamp": "STRING",
                "embedding": "FLOAT[]",
                "importance_score": "FLOAT",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Heartbeat",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "agent_name": "STRING",
                "timestamp": "STRING",
                "status": "STRING",
                "issues": "STRING[]",
                "raw_data": "STRING",
                "importance_score": "FLOAT",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="ChatSummary",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "summary_text": "STRING",
                "original_count": "INT64",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        # Enhanced Memory & Reasoning Nodes (Neo4j/MAGMA style)
        TableDefinition(
            name="ReasoningTrace",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "thought": "STRING",
                "reflection": "STRING",
                "confidence": "FLOAT",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="ToolCall",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "tool_name": "STRING",
                "args": "STRING",
                "result": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Entity",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "entity_type": "STRING",
                "properties": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Event",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "timestamp": "STRING",
                "event_type": "STRING",
                "importance_score": "FLOAT",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Reflection",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "content": "STRING",
                "confidence": "FLOAT",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Goal",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "goal_text": "STRING",
                "status": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Episode",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "timestamp": "STRING",
                "source": "STRING",
                "description": "STRING",
                "importance_score": "FLOAT",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Fact",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "content": "STRING",
                "certainty": "FLOAT",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Concept",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Capability",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        # Callable Resources & Dynamic Agents
        TableDefinition(
            name="ToolMetadata",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "tags": "STRING[]",
                "prompt_template": "STRING",
                "resources": "STRING",
                "capabilities": "STRING[]",
                "auth_requirements": "STRING",
                "version": "STRING",
                "source": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="CallableResource",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "resource_type": "STRING",
                "endpoint": "STRING",
                "agent_card": "STRING",
                "skill_code_path": "STRING",
                "metadata_id": "STRING",
                "embedding": "FLOAT[]",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="SpawnedAgent",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "system_prompt": "STRING",
                "tool_ids": "STRING[]",
                "parent_task_id": "STRING",
                "created_at": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="SystemPrompt",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "content": "STRING",
                "version": "STRING",
                "tags": "STRING[]",
                "parameters": "STRING",
                "embedding": "FLOAT[]",
                "source": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        # Self-Improvement & Learning (Agent Lightning style)
        TableDefinition(
            name="OutcomeEvaluation",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "reward": "FLOAT",
                "success_criteria_met": "STRING[]",
                "feedback_text": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Critique",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "textual_gradient": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="SelfEvaluation",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "confidence_calibration": "FLOAT",
                "task_difficulty": "FLOAT",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Experiment",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "status": "STRING",
                "importance_score": "FLOAT",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="ProposedSkill",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "code_content": "STRING",
                "frontmatter": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        # Knowledge Base Nodes
        TableDefinition(
            name="KnowledgeBase",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "topic": "STRING",
                "description": "STRING",
                "source_type": "STRING",
                "source_count": "INT64",
                "article_count": "INT64",
                "status": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Article",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "summary": "STRING",
                "content": "STRING",
                "word_count": "INT64",
                "tags": "STRING[]",
                "embedding": "FLOAT[]",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="RawSource",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "file_path": "STRING",
                "source_type": "STRING",
                "content_hash": "STRING",
                "file_size": "INT64",
                "status": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="KBConcept",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "description": "STRING",
                "embedding": "FLOAT[]",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="KBFact",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "content": "STRING",
                "certainty": "FLOAT",
                "source_ids": "STRING[]",
                "embedding": "FLOAT[]",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="KBIndex",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "content": "STRING",
                "kb_id": "STRING",
                "article_count": "INT64",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Checkpoint",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "label": "STRING",
                "turn": "INT64",
                "message_count": "INT64",
                "message_data": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Team",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "status": "STRING",
                "member_count": "INT64",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Task",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "content": "STRING",
                "status": "STRING",
                "assigned_to": "STRING",
                "created_by": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Policy",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "policy_id": "STRING",
                "name": "STRING",
                "description": "STRING",
                "condition": "STRING",
                "action": "STRING",
                "priority": "INT64",
                "applies_to": "STRING[]",
                "version": "STRING",
                "created_at": "STRING",
                "valid_from": "STRING",
                "valid_to": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="ProcessFlow",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "flow_id": "STRING",
                "name": "STRING",
                "goal": "STRING",
                "start_step": "STRING",
                "version": "STRING",
                "created_at": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="ProcessStep",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "step_id": "STRING",
                "name": "STRING",
                "step_type": "STRING",
                "tool": "STRING",
                "condition": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="KnowledgeBaseTopic",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "topic_id": "STRING",
                "name": "STRING",
                "description": "STRING",
                "source": "STRING",
                "embedding": "FLOAT[]",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Source",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "source_id": "STRING",
                "title": "STRING",
                "doi": "STRING",
                "url": "STRING",
                "publication_date": "STRING",
                "authors": "STRING[]",
                "is_permanent": "BOOLEAN",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
            },
        ),
        TableDefinition(
            name="Evidence",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "evidence_id": "STRING",
                "claim": "STRING",
                "confidence_score": "FLOAT",
                "is_permanent": "BOOLEAN",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
            },
        ),
        TableDefinition(
            name="Person",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "person_id": "STRING",
                "name": "STRING",
                "expertise": "STRING[]",
                "affiliation": "STRING",
                "is_permanent": "BOOLEAN",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
            },
        ),
        TableDefinition(
            name="PatternTemplate",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "pattern_type": "STRING",
                "content": "STRING",
                "success_rate": "FLOAT",
                "tags": "STRING[]",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Codemap",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "prompt": "STRING",
                "mode": "STRING",
                "hierarchy": "STRING",
                "nodes": "STRING",
                "edges": "STRING",
                "repo_root": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Organization",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "description": "STRING",
                "org_id": "STRING",
                "legal_name": "STRING",
                "domain": "STRING",
                "org_type": "STRING",
                "parent_org_id": "STRING",
                "website": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Role",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "description": "STRING",
                "role_id": "STRING",
                "title": "STRING",
                "responsibilities": "STRING[]",
                "organization_id": "STRING",
                "seniority": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Place",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "description": "STRING",
                "place_id": "STRING",
                "kind": "STRING",
                "address": "STRING",
                "parent_place_id": "STRING",
                "geo_lat": "DOUBLE",
                "geo_lon": "DOUBLE",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Phase",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "description": "STRING",
                "phase_id": "STRING",
                "started_at": "STRING",
                "ended_at": "STRING",
                "phase_kind": "STRING",
                "parent_phase_id": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Decision",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "description": "STRING",
                "decision_id": "STRING",
                "statement": "STRING",
                "motivation": "STRING[]",
                "alternatives_considered": "STRING[]",
                "chosen_alternative": "STRING",
                "confidence": "FLOAT",
                "decided_by": "STRING[]",
                "decided_at": "STRING",
                "reversible": "BOOLEAN",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Incident",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "description": "STRING",
                "incident_id": "STRING",
                "severity": "STRING",
                "detected_at": "STRING",
                "resolved_at": "STRING",
                "status": "STRING",
                "postmortem_article_id": "STRING",
                "affected_system_ids": "STRING[]",
                "root_cause_summary": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="System",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "description": "STRING",
                "system_id": "STRING",
                "tech_stack": "STRING[]",
                "owner_role_ids": "STRING[]",
                "owner_org_id": "STRING",
                "depends_on_system_ids": "STRING[]",
                "repo_urls": "STRING[]",
                "criticality": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Belief",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "description": "STRING",
                "statement": "STRING",
                "confidence": "FLOAT",
                "evidence_node_ids": "STRING[]",
                "contradicted_by_node_ids": "STRING[]",
                "supported_by_node_ids": "STRING[]",
                "last_reviewed": "STRING",
                "source_agent_id": "STRING",
                "scope_node_ids": "STRING[]",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Hypothesis",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "description": "STRING",
                "prediction": "STRING",
                "preconditions_node_ids": "STRING[]",
                "observation_outcome_ids": "STRING[]",
                "falsifiable": "BOOLEAN",
                "verdict": "STRING",
                "confidence_prior": "FLOAT",
                "confidence_posterior": "FLOAT",
                "expires_at": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Principle",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "description": "STRING",
                "principle_id": "STRING",
                "statement": "STRING",
                "scope_node_ids": "STRING[]",
                "exceptions": "STRING[]",
                "derived_from_decision_ids": "STRING[]",
                "derived_from_episode_ids": "STRING[]",
                "strength": "FLOAT",
                "review_cadence_days": "INT64",
                "last_reviewed": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        # Standard Ontology Nodes (BFO, Schema.org, PROV-O, DC, FIBO)
        TableDefinition(
            name="Document",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "description": "STRING",
                "title": "STRING",
                "creator": "STRING",
                "date": "STRING",
                "subject": "STRING",
                "identifier": "STRING",
                "format": "STRING",
                "language": "STRING",
                "content": "STRING",
                "word_count": "INT64",
                "tags": "STRING[]",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="CreativeWork",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "description": "STRING",
                "title": "STRING",
                "creator": "STRING",
                "date_published": "STRING",
                "genre": "STRING",
                "content": "STRING",
                "tags": "STRING[]",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Dataset",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "description": "STRING",
                "distribution_url": "STRING",
                "temporal_coverage": "STRING",
                "spatial_coverage": "STRING",
                "format": "STRING",
                "record_count": "INT64",
                "license": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="SoftwareProject",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "description": "STRING",
                "repo_url": "STRING",
                "language": "STRING",
                "license": "STRING",
                "version": "STRING",
                "stars": "INT64",
                "tech_stack": "STRING[]",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="MedicalEntity",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "description": "STRING",
                "entity_type": "STRING",
                "icd_code": "STRING",
                "snomed_id": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Procedure",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "description": "STRING",
                "steps": "STRING[]",
                "required_tools": "STRING[]",
                "safety_notes": "STRING[]",
                "estimated_duration": "STRING",
                "category": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Regulation",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "description": "STRING",
                "jurisdiction": "STRING",
                "effective_date": "STRING",
                "expiry_date": "STRING",
                "authority": "STRING",
                "regulation_type": "STRING",
                "compliance_status": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="FinancialInstrument",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "description": "STRING",
                "instrument_type": "STRING",
                "ticker": "STRING",
                "issuer": "STRING",
                "currency": "STRING",
                "isin": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="FinancialTransaction",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "description": "STRING",
                "transaction_type": "STRING",
                "amount": "FLOAT",
                "currency": "STRING",
                "counterparty": "STRING",
                "executed_at": "STRING",
                "status": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
        TableDefinition(
            name="Account",
            columns={
                "id": "STRING PRIMARY KEY",
                "type": "STRING",
                "name": "STRING",
                "description": "STRING",
                "account_type": "STRING",
                "institution": "STRING",
                "currency": "STRING",
                "status": "STRING",
                "importance_score": "FLOAT",
                "timestamp": "STRING",
                "metadata": "STRING",
                "is_permanent": "BOOLEAN",
            },
        ),
    ],
    edges=[
        # Core Relationships
        RelDefinition(
            type="PROVIDES",
            connections=[
                {"from": "Agent", "to": "Tool"},
                {"from": "Skill", "to": "Tool"},
                {"from": "Server", "to": "Tool"},
                {"from": "Server", "to": "CallableResource"},
            ],
        ),
        RelDefinition(
            type="DEPENDS_ON",
            connections=[
                {"from": "Agent", "to": "Agent"},
                {"from": "Code", "to": "Code"},
                {"from": "Skill", "to": "Skill"},
            ],
        ),
        RelDefinition(type="CONTAINS", connections=[{"from": "Code", "to": "Code"}]),
        RelDefinition(
            type="RELATED_TO",
            connections=[
                {"from": "Memory", "to": "Memory"},
                {"from": "Memory", "to": "Code"},
                {"from": "Memory", "to": "Agent"},
                {"from": "Memory", "to": "User"},
            ],
        ),
        RelDefinition(
            type="BELONGS_TO", connections=[{"from": "User", "to": "Client"}]
        ),
        RelDefinition(
            type="PREFERS", connections=[{"from": "User", "to": "Preference"}]
        ),
        RelDefinition(
            type="EXECUTED_BY",
            connections=[
                {"from": "Log", "to": "Job"},
                {"from": "Episode", "to": "SpawnedAgent"},
                {"from": "Episode", "to": "Agent"},
                {"from": "ReasoningTrace", "to": "SpawnedAgent"},
                {"from": "ReasoningTrace", "to": "Agent"},
            ],
        ),
        RelDefinition(
            type="PART_OF",
            connections=[
                {"from": "Message", "to": "Thread"},
                {"from": "ChatSummary", "to": "Thread"},
            ],
        ),
        RelDefinition(
            type="REPLY_TO", connections=[{"from": "Message", "to": "Message"}]
        ),
        RelDefinition(
            type="HEARTBEAT_OF", connections=[{"from": "Heartbeat", "to": "Agent"}]
        ),
        RelDefinition(
            type="USES",
            connections=[
                {"from": "Agent", "to": "Prompt"},
                {"from": "Agent", "to": "Skill"},
                {"from": "SpawnedAgent", "to": "CallableResource"},
                {"from": "SpawnedAgent", "to": "SystemPrompt"},
                {"from": "Episode", "to": "SystemPrompt"},
            ],
        ),
        # Enhanced Memory & Reasoning Relationships
        RelDefinition(
            type="HAS_REASONING",
            connections=[
                {"from": "Message", "to": "ReasoningTrace"},
                {"from": "Episode", "to": "ReasoningTrace"},
            ],
        ),
        RelDefinition(
            type="USED_TOOL", connections=[{"from": "ReasoningTrace", "to": "ToolCall"}]
        ),
        RelDefinition(
            type="AFFECTS", connections=[{"from": "ToolCall", "to": "Entity"}]
        ),
        RelDefinition(
            type="CAUSED_BY",
            connections=[
                {"from": "ReasoningTrace", "to": "ReasoningTrace"},
                {"from": "Event", "to": "Event"},
            ],
        ),
        RelDefinition(
            type="INFLUENCED",
            connections=[{"from": "Reflection", "to": "ReasoningTrace"}],
        ),
        RelDefinition(
            type="CONTRADICTS",
            connections=[
                {"from": "Fact", "to": "Fact"},
                {"from": "ReasoningTrace", "to": "ReasoningTrace"},
            ],
        ),
        RelDefinition(
            type="UPDATED_BELIEF", connections=[{"from": "Reflection", "to": "Fact"}]
        ),
        RelDefinition(
            type="HAS_EVIDENCE",
            connections=[
                {"from": "Fact", "to": "Message"},
                {"from": "Fact", "to": "Episode"},
            ],
        ),
        RelDefinition(
            type="TEMPORALLY_PRECEDES",
            connections=[
                {"from": "Episode", "to": "Episode"},
                {"from": "Event", "to": "Event"},
            ],
        ),
        RelDefinition(
            type="OCCURRED_DURING", connections=[{"from": "Event", "to": "Episode"}]
        ),
        RelDefinition(
            type="EVOLVED_INTO", connections=[{"from": "Concept", "to": "Concept"}]
        ),
        RelDefinition(
            type="ENABLES", connections=[{"from": "Capability", "to": "Tool"}]
        ),
        RelDefinition(type="IMPLIES", connections=[{"from": "Fact", "to": "Fact"}]),
        RelDefinition(type="INDEXES", connections=[{"from": "Concept", "to": "Fact"}]),
        RelDefinition(
            type="CONSOLIDATES_INTO",
            connections=[{"from": "Episode", "to": "ChatSummary"}],
        ),
        RelDefinition(
            type="SELF_REFLECTS_ON",
            connections=[{"from": "Agent", "to": "ReasoningTrace"}],
        ),
        # Callable Resource & Agent Relationships
        RelDefinition(
            type="HAS_METADATA",
            connections=[{"from": "CallableResource", "to": "ToolMetadata"}],
        ),
        RelDefinition(
            type="PROVIDES_CAPABILITY",
            connections=[{"from": "CallableResource", "to": "Capability"}],
        ),
        RelDefinition(
            type="DELEGATES_TO", connections=[{"from": "Agent", "to": "Agent"}]
        ),
        RelDefinition(
            type="DISCOVERED_VIA", connections=[{"from": "Agent", "to": "Server"}]
        ),
        RelDefinition(
            type="USED_RESOURCE",
            connections=[{"from": "ReasoningTrace", "to": "CallableResource"}],
        ),
        RelDefinition(
            type="USES_BASE_PROMPT",
            connections=[{"from": "SpawnedAgent", "to": "SystemPrompt"}],
        ),
        RelDefinition(
            type="EVOLVED_FROM",
            connections=[{"from": "SystemPrompt", "to": "SystemPrompt"}],
        ),
        RelDefinition(
            type="PROVEN_WITH",
            connections=[{"from": "SystemPrompt", "to": "CallableResource"}],
        ),
        RelDefinition(
            type="DERIVED_FROM_PROMPT",
            connections=[{"from": "ToolMetadata", "to": "SystemPrompt"}],
        ),
        # Self-Improvement Relationships
        RelDefinition(
            type="PRODUCED_OUTCOME",
            connections=[
                {"from": "Episode", "to": "OutcomeEvaluation"},
                {"from": "ReasoningTrace", "to": "OutcomeEvaluation"},
            ],
        ),
        RelDefinition(
            type="SCORED_BY",
            connections=[{"from": "OutcomeEvaluation", "to": "SpawnedAgent"}],
        ),
        RelDefinition(
            type="GENERATED_CRITIQUE",
            connections=[{"from": "ReasoningTrace", "to": "Critique"}],
        ),
        RelDefinition(
            type="LED_TO", connections=[{"from": "Critique", "to": "SystemPrompt"}]
        ),
        RelDefinition(
            type="SUPERSEDES",
            connections=[
                {"from": "Fact", "to": "Fact"},
                {"from": "SystemPrompt", "to": "SystemPrompt"},
            ],
        ),
        # Knowledge Base Relationships
        RelDefinition(
            type="BELONGS_TO_KB",
            connections=[
                {"from": "Article", "to": "KnowledgeBase"},
                {"from": "KBConcept", "to": "KnowledgeBase"},
                {"from": "KBFact", "to": "KnowledgeBase"},
                {"from": "RawSource", "to": "KnowledgeBase"},
                {"from": "KBIndex", "to": "KnowledgeBase"},
            ],
        ),
        RelDefinition(
            type="COMPILED_FROM", connections=[{"from": "Article", "to": "RawSource"}]
        ),
        RelDefinition(
            type="ABOUT", connections=[{"from": "Article", "to": "KBConcept"}]
        ),
        RelDefinition(
            type="CITES",
            connections=[
                {"from": "Article", "to": "RawSource"},
                {"from": "KBFact", "to": "RawSource"},
            ],
        ),
        RelDefinition(
            type="BACKLINKS", connections=[{"from": "Article", "to": "Article"}]
        ),
        RelDefinition(
            type="CONTRADICTS_KB", connections=[{"from": "KBFact", "to": "KBFact"}]
        ),
        RelDefinition(
            type="INDEXES_KB", connections=[{"from": "KBIndex", "to": "Article"}]
        ),
        RelDefinition(
            type="SNAPSHOT_OF", connections=[{"from": "Checkpoint", "to": "Episode"}]
        ),
        RelDefinition(
            type="FORKED_FROM", connections=[{"from": "Checkpoint", "to": "Checkpoint"}]
        ),
        RelDefinition(
            type="ASSIGNED_TO_AGENT",
            connections=[
                {"from": "Task", "to": "Agent"},
                {"from": "Task", "to": "SpawnedAgent"},
            ],
        ),
        RelDefinition(
            type="BLOCKED_BY_TASK", connections=[{"from": "Task", "to": "Task"}]
        ),
        RelDefinition(
            type="BELONGS_TO_TEAM",
            connections=[
                {"from": "Task", "to": "Team"},
                {"from": "Agent", "to": "Team"},
                {"from": "SpawnedAgent", "to": "Team"},
            ],
        ),
        RelDefinition(
            type="APPLIES_TO",
            connections=[
                {"from": "Policy", "to": "Entity"},
                {"from": "Policy", "to": "Agent"},
                {"from": "Policy", "to": "ProcessFlow"},
            ],
        ),
        RelDefinition(
            type="HAS_START",
            connections=[{"from": "ProcessFlow", "to": "ProcessStep"}],
        ),
        RelDefinition(
            type="NEXT",
            connections=[{"from": "ProcessStep", "to": "ProcessStep"}],
        ),
        RelDefinition(
            type="GROUNDED_IN",
            connections=[{"from": "KnowledgeBaseTopic", "to": "Policy"}],
        ),
        RelDefinition(
            type="REFERENCES",
            connections=[
                {"from": "KnowledgeBaseTopic", "to": "ProcessFlow"},
                {"from": "KnowledgeBaseTopic", "to": "ProcessStep"},
            ],
        ),
        RelDefinition(
            type="AUTHORED",
            connections=[{"from": "Person", "to": "Source"}],
        ),
        RelDefinition(
            type="SUPPORTS",
            connections=[
                {"from": "Source", "to": "Evidence"},
                {"from": "Source", "to": "Concept"},
                {"from": "Evidence", "to": "Concept"},
            ],
        ),
        RelDefinition(
            type="HAS_ROLE",
            connections=[{"from": "Person", "to": "Role"}],
        ),
        RelDefinition(
            type="PLAYED_ROLE_DURING",
            connections=[{"from": "Person", "to": "Role"}],
        ),
        RelDefinition(
            type="OCCURRED_AT_PLACE",
            connections=[
                {"from": "Event", "to": "Place"},
                {"from": "Decision", "to": "Place"},
                {"from": "Incident", "to": "Place"},
                {"from": "Episode", "to": "Place"},
            ],
        ),
        RelDefinition(
            type="OCCURRED_DURING_PHASE",
            connections=[
                {"from": "Event", "to": "Phase"},
                {"from": "Decision", "to": "Phase"},
                {"from": "Incident", "to": "Phase"},
                {"from": "Episode", "to": "Phase"},
            ],
        ),
        RelDefinition(
            type="DECIDED_BY",
            connections=[
                {"from": "Decision", "to": "Person"},
                {"from": "Decision", "to": "Agent"},
            ],
        ),
        RelDefinition(
            type="MOTIVATED_BY",
            connections=[
                {"from": "Decision", "to": "Goal"},
                {"from": "Decision", "to": "Belief"},
                {"from": "Decision", "to": "Fact"},
            ],
        ),
        RelDefinition(
            type="RESULTED_IN",
            connections=[
                {"from": "Decision", "to": "Event"},
                {"from": "Decision", "to": "Incident"},
                {"from": "Decision", "to": "OutcomeEvaluation"},
            ],
        ),
        RelDefinition(
            type="SUPPORTS_BELIEF",
            connections=[
                {"from": "Fact", "to": "Belief"},
                {"from": "Episode", "to": "Belief"},
                {"from": "Article", "to": "Belief"},
                {"from": "Evidence", "to": "Belief"},
            ],
        ),
        RelDefinition(
            type="CONTRADICTS_BELIEF",
            connections=[
                {"from": "Fact", "to": "Belief"},
                {"from": "Episode", "to": "Belief"},
                {"from": "Article", "to": "Belief"},
            ],
        ),
        RelDefinition(
            type="GENERALIZES_TO",
            connections=[
                {"from": "Episode", "to": "Principle"},
                {"from": "Episode", "to": "Concept"},
                {"from": "Decision", "to": "Principle"},
                {"from": "Event", "to": "Principle"},
            ],
        ),
        RelDefinition(
            type="INSTANCE_OF_PATTERN",
            connections=[
                {"from": "Decision", "to": "PatternTemplate"},
                {"from": "Incident", "to": "PatternTemplate"},
                {"from": "Episode", "to": "PatternTemplate"},
            ],
        ),
        RelDefinition(
            type="CAUSED_INCIDENT",
            connections=[
                {"from": "Decision", "to": "Incident"},
                {"from": "Event", "to": "Incident"},
                {"from": "Code", "to": "Incident"},
                {"from": "System", "to": "Incident"},
            ],
        ),
        RelDefinition(
            type="RESOLVED_INCIDENT",
            connections=[
                {"from": "Decision", "to": "Incident"},
                {"from": "Agent", "to": "Incident"},
                {"from": "Person", "to": "Incident"},
            ],
        ),
        RelDefinition(
            type="OWNS_SYSTEM",
            connections=[
                {"from": "Role", "to": "System"},
                {"from": "Organization", "to": "System"},
                {"from": "Person", "to": "System"},
            ],
        ),
        RelDefinition(
            type="DEPENDS_ON_SYSTEM",
            connections=[{"from": "System", "to": "System"}],
        ),
        RelDefinition(
            type="PREDICTS",
            connections=[
                {"from": "Hypothesis", "to": "Event"},
                {"from": "Hypothesis", "to": "Incident"},
                {"from": "Hypothesis", "to": "Fact"},
            ],
        ),
        RelDefinition(
            type="OBSERVES",
            connections=[
                {"from": "Episode", "to": "Hypothesis"},
                {"from": "Incident", "to": "Hypothesis"},
                {"from": "Fact", "to": "Hypothesis"},
            ],
        ),
        RelDefinition(
            type="SUPERSEDES_BY",
            connections=[
                {"from": "Entity", "to": "Organization"},
                {"from": "Entity", "to": "Place"},
                {"from": "Entity", "to": "System"},
                {"from": "Entity", "to": "Role"},
                {"from": "Event", "to": "Decision"},
                {"from": "Event", "to": "Incident"},
            ],
        ),
        RelDefinition(
            type="BELONGS_TO_ORGANIZATION",
            connections=[
                {"from": "Role", "to": "Organization"},
                {"from": "Person", "to": "Organization"},
                {"from": "System", "to": "Organization"},
            ],
        ),
        RelDefinition(
            type="EMPLOYS",
            connections=[{"from": "Organization", "to": "Person"}],
        ),
        # Standard Ontology Relationships (PROV-O, SKOS, Dublin Core, FIBO)
        RelDefinition(
            type="WAS_GENERATED_BY",
            connections=[
                {"from": "Memory", "to": "Episode"},
                {"from": "Document", "to": "Action"},
                {"from": "Fact", "to": "Episode"},
                {"from": "Evidence", "to": "ReasoningTrace"},
            ],
        ),
        RelDefinition(
            type="WAS_DERIVED_FROM",
            connections=[
                {"from": "Document", "to": "Document"},
                {"from": "Article", "to": "RawSource"},
                {"from": "Fact", "to": "Evidence"},
                {"from": "CreativeWork", "to": "Document"},
            ],
        ),
        RelDefinition(
            type="WAS_ATTRIBUTED_TO",
            connections=[
                {"from": "Document", "to": "Person"},
                {"from": "Document", "to": "Organization"},
                {"from": "CreativeWork", "to": "Person"},
                {"from": "Dataset", "to": "Organization"},
            ],
        ),
        RelDefinition(
            type="HAS_TEMPORAL_EXTENT",
            connections=[
                {"from": "Event", "to": "Phase"},
                {"from": "Episode", "to": "Phase"},
                {"from": "Incident", "to": "Phase"},
            ],
        ),
        RelDefinition(
            type="BROADER",
            connections=[
                {"from": "Concept", "to": "Concept"},
                {"from": "KBConcept", "to": "KBConcept"},
                {"from": "Fact", "to": "Concept"},
            ],
        ),
        RelDefinition(
            type="NARROWER",
            connections=[
                {"from": "Concept", "to": "Concept"},
                {"from": "KBConcept", "to": "KBConcept"},
            ],
        ),
        RelDefinition(
            type="RELATED_CONCEPT",
            connections=[
                {"from": "Concept", "to": "Concept"},
                {"from": "KBConcept", "to": "KBConcept"},
            ],
        ),
        RelDefinition(
            type="EXACT_MATCH",
            connections=[{"from": "Concept", "to": "Concept"}],
        ),
        RelDefinition(
            type="CLOSE_MATCH",
            connections=[{"from": "Concept", "to": "Concept"}],
        ),
        RelDefinition(
            type="BROAD_MATCH",
            connections=[{"from": "Concept", "to": "Concept"}],
        ),
        RelDefinition(
            type="CREATOR",
            connections=[
                {"from": "Document", "to": "Person"},
                {"from": "CreativeWork", "to": "Person"},
                {"from": "Dataset", "to": "Person"},
                {"from": "SoftwareProject", "to": "Person"},
            ],
        ),
        RelDefinition(
            type="CITES_SOURCE",
            connections=[
                {"from": "Document", "to": "Source"},
                {"from": "Article", "to": "Source"},
                {"from": "Evidence", "to": "Source"},
            ],
        ),
        RelDefinition(
            type="HAS_FINANCIAL_INSTRUMENT",
            connections=[{"from": "Account", "to": "FinancialInstrument"}],
        ),
        RelDefinition(
            type="EXECUTED_TRANSACTION",
            connections=[
                {"from": "Agent", "to": "FinancialTransaction"},
                {"from": "Person", "to": "FinancialTransaction"},
                {"from": "Organization", "to": "FinancialTransaction"},
            ],
        ),
    ],
)
